### ISSUE TITLE
Send email by linet or by 3dparty

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#277]
Hi,
just look on the api doc at: http://www.linet.org.il/support/dev-guide/3-api
and didn't find any way to set if send an email from linet with the doc or not
For example, when you generate an invoice
please add the option / doc / both so we can set if send the doc from lient template or get the Source pdf from linet "מסמך מקור" and send if from the 3dparty platform, for example from magento transactional emails or whmcs email templates, etc...

Best Regards,
Star Network

**Comment by shahafbs** [comment]
in addition to that when printing an invoice to email (gmail for ex) email araives empty with no attached file

**Comment by aribhour** [comment]
Not within the scope curent version.
Too much work with integrating third party applications

**Comment by starnetwork** [comment]
Hi Ari, PLease check with Adam, as good as I know it's should work with this version (it's work for me), and just need to be clear in the API Doc

**Comment by aribhour** [comment]
What works for you?

**Comment by adam2314** [comment]
we do support third party smtp solutions with ssl and all

**Comment by aribhour** [comment]
No aditional tasks here

**Comment by starnetwork** [comment]
just make sure this option (get PDF via api) is explained in API Docs

**Comment by adam2314** [comment]
in the API look for the print action.
http://www.linet.org.il/support/dev-guide/3-api
