### ISSUE TITLE
Totals issue when working with both Taxable and none taxable Items

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#397]
Hi,
Please check for example star.speedcomp doc view 89
First item is 113.56 include tax
second item is 93.79 without tax
סה"כ סכומים חייבים במע"מ
show 207.35
instead of 113.56
http://awesomescreenshot.com/090441u6ae

**Comment by starnetwork** [comment]
Hi Ari,
1. maybe it's not so common but it's still in use, for example for shipping or other service that can be without tax in some cases for taxable item / service
2. I see it on HTML and PDF also, so it's not only "confusing", it's Incorrect can case the customer that getting this doc to send incorrect tax report based on this incorrect data.

**Comment by aribhour** [comment]
Sorry. my mistake. It is a serious thing and apparently, after talking about it with Adam,  it is not so hard to fix as I thought in first place and for sure is not duplicate with other issue as I thought.
So Adam will work on a fix to this issue after this weekend...

**Comment by adam2314** [comment]
done
