### ISSUE TITLE
 linux...

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#398]
למשדרגים מלינוקס. 
האם האופציה החידה היא לקמפל מקוד מקור??
ולא ממש הבנתי איפה הקבצים
האם תיהיה התקנה פשוטה גם למשתשמשי לינוקס?

תודה רבה
שחף

**Comment by aribhour** [comment]
By the way. We have an add on module that has the ability to manage tenants for a multitenant, single instance installation of linet 3 .(Supported functions: Create, delete, suspend,cancel suspend, backup, restore tenants, setting up document creating quota per tenant and upgrade the whole instance on behalf of all tenants from a central management GUI or through API. The API is specially useful for merging Linet SAAS hosting management within central management system -like WHMCS- for web hosting companies ).
We are selling this module if you or somebody else you know is interested.

**Comment by shahafbs** [comment]
ok :-) i will
BTW do u think my account manager can use linet? or is it just for the busןness?

**Comment by aribhour** [comment]
Yes fcourse.
