### ISSUE TITLE
Issue with total when Prices Including Tax

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#399]
Hi,
Total price include tax is 870NIS
Linet totals add duplicated tax, and it's show incorrect totals:
1026.60 instead of 870NIS

Screenshot: http://awesomescreenshot.com/0cc44aa773

**Comment by aribhour** [comment]
Double check yourself. The total of 870 doesn't include VAT....

**Comment by starnetwork** [comment]
Please check the Columns
Price / Tax / Total on each line
prices are including tax
for example, 49NIS is include tax, no?

**Comment by starnetwork** [comment]
you right, it's was exclude tax and not included, just the "סך הכל" text
was confused me
