### ISSUE TITLE
Hello, I sent an invoice by e-mail, I received a message that email was sent but received nothing. 

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#406]
Email addresses are correct.
Where am I wrong ?
How long should reach the mail ?

**Comment by aribhour** [comment]
Does the virtual computer have access to the internet?
You can check it up by trying to browse the internet with an internet browser within the virtual linux os.

**Comment by shaulmani** [comment]
השלמת שדות רלוונטים בהגדרות פתר את זה
