### ISSUE TITLE
New Company PDF

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#407]
Hi,
got the error
 openssl_pkcs12_export_to_file(): error opening file /var/www/linet3admin/protected/tenants/60/CA3_/cert/1.p12 Back 
when I try to create the first PDF Doc for New Company

**Comment by adam2314** [comment]
first company PDF with PNG icon:
http://awesomescreenshot.com/0544587716

please provide some more input on your setup

**Comment by starnetwork** [comment]
it's not local setup, but hosted on speedcomp.co.il, as you can see, tenants/60

**Comment by adam2314** [comment]
all the tenets on speedcomp.co.il are not updated until we will finish the testing on dev.speedcomp...
i can see the documents you are trying to make(using the API) and they are not valid.
if you will use the GUI you will see it works.
