### ISSUE TITLE
Logo on Docs and HTML view

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#408]
Hi,
we uploading png 3kb logo
Dimensions: 94pxx94px
but in both docs view and PDF it's show the "logo" text instead of the logo
http://awesomescreenshot.com/033453dpa2

Regards,

**Comment by aribhour** [comment]
Try to upload a jpg format image . It works

**Comment by adam2314** [comment]
PNG,JPG,GIF,SVG works. please retry or provide the file for inspection
