### ISSUE TITLE
Tax for Invoice and Invoice ID

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#415]
Hi,
Please check why the invoice table show 0 and tax free show the price: http://awesomescreenshot.com/01f45mmddf

Also, this doc has no ID: http://awesomescreenshot.com/03945mn860
tenant ID: 60

Regards,

**Comment by adam2314** [comment]
hello 
the doc has ID. it has no doc number becouse accourding to linet it isn't a valid doc.
try sending it without novat_total shuld be ok and will take care of the other prablom.
....,"sub_total":0,"novat_total":189,"vat":0,"total":"170.1000",....

also the request returns an error saying the sum does not much(becouse of the novat_total)
