### ISSUE TITLE
Installing linet3 on Ubuntu

### ISSUE THREAD

**Issue by bablat** [adam2314/linet3#416]
First, thanks for building linet! I appreciate the effort and hope I can contribute in the future.

I'm having some issues with installing linet3 on Ubuntu.
I've set up the requirements properly, once I launch my browser for the initial configuration the application redirects me to /install which is a document which doesn't exist and I get a 404 error.

I believe that some of the installation notes are unclear, should yii be copied over content already existing under protected?
also, I got the following error after installation:
Warning: require_once(/var/www/yii/framework/yii.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 13
I've also changed /protected/config/yii.php in the following way:
$yii=dirname(__FILE__).'/../yii/framework/yii.php';
this solved that issue, but lead me to the missing /install page, which is where I'm stuck now.

Not sure what I'm missing, but hopefully someone can help.

**Comment by bablat** [comment]
Absolutely. Tried to follow it as accurately as I could, but as I said I believe there are a few discrepancies. Let me point at specific issues:

* In the prerequisites I believe you are missing the PDO MySQL extension, which I installed as well to get PHP to support MySQL connectivity.

* I've cloned the linet git repository to /var/www/html, this creates a /var/www/html/linet3 folder, I assumed the contents of linet3 folder should be in the webserver root, so I've moved everything there and properly chown'd to www-data

* Next step is to download YII 1.1 and extract it into /var/www/html/protected. Once you do that, you get the following error:

`Warning: require_once(/var/www/html/protected/config/../../../yii/framework/yii.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 13`
`Fatal error: require_once(): Failed opening required '/var/www/html/protected/config/../../../yii/framework/yii.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/index.php on line 13`

This is obviously a bug, the reference is coming from:  /protected/config/yii.php `$yii=dirname(__FILE__).'/../../../yii/framework/yii.php';`
So I've changed it to the following:
`$yii=dirname(__FILE__).'/../framework/yii.php';`
Which should work.

* At this point I point my browser to the index.php page, which gets properly redirected to /install, and as I noted before the browser is redirected to /install and fails with 404 page not found.

As you can see I've tried following these directions as much as I could, but I don't think that anyone would be successful following them on a clean ubuntu system. It may work on a linux server which had a previous version installed, and maybe that includes the missing steps. Hope you can help!

**Comment by aribhour** [comment]
Sorry bablat )-: 
The man with the answers on issues concerning Linux and programming will return from vacation next Sunday (18/1/14)  
I can assure you'll get some answers then.

**Comment by dan-omniscience** [comment]
Hello Bablat,

RE:the reference is coming from: /protected/config/yii.php 
```php
$yii=dirname(__FILE__).'/../../../yii/framework/yii.php';
```
So I've changed it to the following:
```php
$yii=dirname(__FILE__).'/../framework/yii.php';
```
I agree with you , this should be solved either by changing the code or changing the install manual.

about the 404 isssue, I don't know how to help with it, more info is needed to solve it, I also experienced issues when tried to install the system(before the manual was created) in the end what I think worked out for me was to take the yii files and the directories structure from the windows installer.

**Comment by aribhour** [comment]
Hey Dan
Nice to have you on board as a man with the answer...
 :-)
Tell me what exactly to change in the manual and I'll do that.
Do you mean that Yii files should be copied to /protected/config instead of /protected directly?

**Comment by bablat** [comment]
What do you mean by "take the yii files and the directories structure from the windows installer"?
Which folders need to be taken and where should they be placed?

I think that the linux install is plain broken, perhaps it's just the http://[ip]/install that doesn't work. Can the configuration step be skipped? What does the install step create? can I simply create the configuration files it outputs and skip the install step?

**Comment by aribhour** [comment]
I hoped what Dan suggested would help you. Apparently it didn't. 
Sorry, in this case I am reverting back to my first comment on this issue:
You are kindly advised to wait for the man with the answers on that issue till next week first days.

**Comment by dan-omniscience** [comment]
Hey Ari,
I wanted to try and follow the install guide myself before I tell you to change something in the manual.
unfortunately I got into issues myself in the process(others from what bablat reported) my issues where due probably because of my own server settings(i'm using nginx and the installer script is looking for apache stuff) 
but in spite of my own server configs I must agree with bablat about the install process/manual for linux we should make it much more simple for linux users. I'll be happy to contribute my help together with Adam to form a simple setup process and configuration manual for linux servers with apache or nginx.

**Comment by aribhour** [comment]
OK what suits everybody best.
We wait then.

**Comment by bablat** [comment]
I'm happy to help Linux work out as well, I'm fairly experienced with the platform.
Need to better understand the folder layout. Currently it seems yii is a mess :)

**Comment by adam2314** [comment]
hello to all
Apache mod_rewrite isn't enabled probably
try accessing /index.php?r=install
if you get the wizard using the url please enable it  else update us

**Comment by bablat** [comment]
Gave it a shot.

I first enabled the apache rewrite module, but it didn't allow the /install url.
index.php?r=install did work, and brought me to the reqs screen.
PHP Curl was missing, so I installed it and fixed the missing dependency (should be added to the install guide).
Once I tried moving to the next step of the wizard, I got a blank error dialog box, so this is where I'm stuck now.

![image](https://cloud.githubusercontent.com/assets/10455889/5696568/fe3b9064-99dd-11e4-866f-bfcabf5a2fe6.png)

**Comment by bablat** [comment]
Quick update, it looks like browser is trying to post to /install, which is still missing.
How can that be addressed (besides enabling mod-rewrite, which I already have). Is there some configuration missing?

**Comment by bablat** [comment]
Alright, I got around the issues, it seems that the Apache site configuration requires some tweaking. I've written a rewrite rule to redirect /install to /index.php?r=install and enabled .htaccess with AllowOverride.

So, I believe that accurate Apache site configuration is missing from the manual.

**Comment by aribhour** [comment]
Bablat, I am glad to see that you succeeded to overcome the issues and got Linet up and running at last.
Can you give me some detailed description of Linux installation steps missing in the guide?
I'll will be glad to add the missing steps to the guide ASAP in order to prevent others face the obstacle that you already cracked.

**Comment by shahafbs** [comment]
bablat can you please explain what u did to go around the last issue in a simpler way :-)
thanx
shahaf

**Comment by danreznik** [comment]
hi bablat,

could you please share the rewrite rule to redirect /install to /index.php?r=install that you wrote.

Thank's
Dan.
