### ISSUE TITLE
בהפקת מסמך תצוגה מקדימה לא מגיב לאחר העדכון

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#417]

**Comment by aribhour** [comment]
נכון

**Comment by aribhour** [comment]
גם שמירת טיוטא מוציא הודעת שגיאה

**Comment by shaulmani** [comment]
דווקא אצלי בסדר גם בחלונות וגם בלינוקס
ניסיתי לשמור טיוטה ה.מחיר וחשבונית ולא הייתה בעיה

2015-01-12 19:46 GMT+02:00 aribhour <notifications@github.com>:

**Comment by adam2314** [comment]
סגור
