### ISSUE TITLE
gmail recognize linet docs as spam and stop recive them. at walla mail it works

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#418]
does any one know how to prevent gmail recognize it as spam ?

**Comment by adam2314** [comment]
setting outbound smtp settings will take care of it.

**Comment by shaulmani** [comment]
Please  tell me what to do. I dont understand. Thanks
בתאריך 19 בינו' 2015 18:16, ‏"adam2314" <notifications@github.com> כתב:

**Comment by adam2314** [comment]
בהגדרות
פרטי שרת דוא"ל יוצא
תגדיר  
 את החשבון של ספק האינטרנט שלך
וזה יסתדר.

**Comment by shaulmani** [comment]
בדיוק מה שעשיתי ולא עובד תחת לינוקס וירטואלי.תודה
בתאריך 20 בינו' 2015 10:13, ‏"adam2314" <notifications@github.com> כתב:
