### ISSUE TITLE
התקנה

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#419]
<p>בזמן התקנת גרסה 3, שם הקישור שנוצא על שולחן העבודה נשמר בשם של גרסה 2.</p>

**Comment by aribhour** [comment]
נכון שהשם של קיצור הדרך לא משתנה, אבל אם הסרת את לינט 2 כראוי (הפעלת את תוכנית ההסרה כאדמיניסטראטור) ואם התקנת את לינט 3 כראוי (הפעלת את תוכנית ההתקנה כאדמיניסטראטור) התוכנה אמורה לעבוד גם באמצעות הפעלת קיצור הדרך "לינט 2" . לכן, כל מה שנותר לעשות, זה לשנות את השם של קיצור הדרך באופן ידני . בהצלחה
