### ISSUE TITLE
 כאשר החברה שייכת למשתמש מוצג שם המשתמש בלבד, לא ניתן לדעת באיזה שנה עובדים.

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#420]
הסבר : בעסק שלי 2014+2015 מופיע שם משתמש בלבד, למרות שבהגדרות רשום שם ושנה.
עשיתי בדיוק באותה טכניקה בכל העסקים. אצל לקוח מופיע שם חברה אצל משתמש לא.

**Comment by aribhour** [comment]
אתה מתכוון אולי שהקמת חברה כאשר השנה היא חלק מהשם שלה?

**Comment by shaulmani** [comment]
כן, לדוגמה : חברה 1 - שאול 2014, חברה 2 - שאול 2015.

2015-01-10 18:31 GMT+02:00 aribhour <notifications@github.com>:

**Comment by aribhour** [comment]
אז שים לב: הבעיה היא שאתה כנראה שם לוגו. הלוגו מסתיר את שם החברה.. אם תסיר את הלוגו אתה תראה את השם.

**Comment by shaulmani** [comment]
צודק, אבל החזיר בעיה קודמת.
ללא לוגו בהדפסה מופיע הכיתוב LOGO על המסמכים.
כדי לבטל את זה שמתי לוגו ריק, שאכן מבטל את הכיתוב LOGO.
אז איך להעלים את הכיתוב לוגו במסמכים ?
תודה.

בתאריך 10 בינואר 2015 בשעה 18:39, מאת aribhour <notifications@github.com>:

**Comment by aribhour** [comment]
כרגע אין דרך להעלים את הטקסט. אני מציע לך ליצור תמונה מטקסט שיבהיר באיזה חברה ובאיזה שנה מדובר (באמצעות תוכנת "צייר" של חלונות לדוגמא) למשל: "שאול מני 2014 " ואז לשים את התמונה עם הטקסט בלבד בתור לוגו
