### ISSUE TITLE
תאריך בתנועת יומן ידנית

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#422]
<p style="text-align: right;">בעת רישום פקודת יומן ידנית ניתן לבחור תאריך אבל המערכת רושמת את התנועה לתאריך 01/01/1970 ומתעלמת מהתאריך שרשמתי בעת רישום התנועה</p>

**Comment by aribhour** [comment]
בדקתי ומצאתי שזה נכון
