### ISSUE TITLE
אין אפשרות להנפיק חשבונית !!!!

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#423]

**Comment by aribhour** [comment]
קודם כל, שומעים אותך כבר בפעם הראשונה, לא צריך לפתוח 5 הודעות על אותו הנושא
שנית, לא מקובל כאן סגנון של צעקות עם כל סימני הקריאה הללו, המנע מזה בעתיד
שלישית: התופעה שאת/ה מצביע עליה שאי אפשר להפיק חשבוניות לא מופיעה באף אחד מסוגי ההתקנות שקיימות אצלנו
אנא הוסף עוד מידע: על איזה מערכת הפעלה התקנת את לינט, באיזה אופן את/ה מנסה להפיק חשבונית, מה את/ה מקבל/ת
שאר 4 ההודעות שפתחת באותו נושא יימחקו עקב כפילות
