### ISSUE TITLE
הודעת שגיאה באשף ההתקנה

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#428]
שלום
אני מתקין על שרת מרוחק עם לינוקס.
פעלתי על פי ההנחיות בהתקנה (העתקת הקבצים, בניית מסד הנתונים, ום מתן ההרשאות לתיקיה) ואני מגיע לאשף ההתקנה
בשורה האחרונה של הדף הראשון לא כתוב writable אלא denaid/
כשאני עובר למסך השני הכל בסדר אבל בנסיון למעבר למסך השלישי אני מקבל הודכת שגיאה [object Object]
ואין אפשרות להמשיך.
מה יכולה להיות הבעיה
יום מקסים
שחף

**Comment by aribhour** [comment]
תראה אם יש כאן #416 תשובה בשבילך

**Comment by shahafbs** [comment]
כמה דברים לברר בקשר לפוסט שהפנת אותי אליו.
1. אני פתרתי את הבעיה הראשונה על ידי מיקום הספריה yii בספריה אלי ההודעה העבירה אותי.
לגבי הבעיה שאני נמצא בה בסוף הוא מתאר פתרון אבל אני לא מצליח להבין מה הוא עשה.
תודה רבה
שחף

**Comment by aribhour** [comment]
אני בטח לא מבין מה הוא עשה. אם אתה גם לא מבין , נצטרך לחכות ליום ראשון לחזרתו של אדם מחופשה ונקווה שלו יהיו תשובות.
שבת שלום בינתיים

**Comment by shahafbs** [comment]
סבבה שבת שלום
רק אוסיף לאדם את השאלה האם פתרתי נכון את הבעיה עם התיקייה.או שעדיף הפתרון שמוצע בשרשור המקושר.

**Comment by shahafbs** [comment]
בוקר טוב
זה מה שמוצג במסך הראשון של אשף ההתקנה
d	value
PHP Version	5.3.3-7+squeeze14
PHP PDO	OK
PHP Zip	OK
PHP CURL	OK
PHP PDO Mysql	OK
PHP PDO Sqlite	Failed
PHP OpenSSL	OK
Apache mod Rewrite	OK
file permission	Denaid

אחרי המסך השני אני מקבל את אותה הודעת שגיאה כמו בשרשור המקושר של בבלת
יום מקסים בינתיים
שחף

**Comment by adam2314** [comment]
אהלן שחר
נראה לי שלאפצי שלך אין הרשאת כתיבה לתקייה של לינט
ולכן הוא לא מצליח לכתוב את קובץ ההגדרות של לינט.
אנא ודא שיש לו הרשאה לכתוב לתקייה(גם לקבצים הקיימים)

אם לא ה
object 
שאתה מקבל זו תקוגבה לבקשת 
AJAX
אם תוכל בעזרת
 F12 
לומר לנו מה התגובה אני אוכל לעזור יותר

**Comment by shahafbs** [comment]
טוב, הבעיה היא שהוא מנסה להכנס עם יוזר 
root
אפילו שב
protected/config/install.php 
שיניתי את שם המשתמש וגם במסך הראשון של ההתקנה שיניתי את השם משתמש בהתאמה.
האם יש מקום נוסף בו צריך לשנות את שם המשתמש בהגדרות?
תודה רבה
שחף

**Comment by adam2314** [comment]
יש רק שני מקומות שבהם מגדירים את הגישה לDB
ושניהם בקובץ
protected/config/install.php 
אם אשף ההתקנה לא מצליח לעדכן את הקובץ
כנראה שאין לו הרשאה לכתיבה.

בלי קשר בשביל להפעיל את
 htaccess
תוסיף להגדרות של האפצי
```
        <Directory /var/www/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>

```

**Comment by shahafbs** [comment]
טוב אני חושב שעשיתי את זה.
הקונסול (f12) 
נותן לי את ההודעות הבאות על התיקיה של 
/install/3
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/install
 Failed to load resource: net::ERR_CACHE_MISS
/install/3
500 (Internal Server Error)

רעיון?

**Comment by aribhour** [comment]
היי שחף
ההשערה של אדם היא עדיין שאין הרשאות מספיקות לאפצ'י לכתיבה לתיקיה.
אנחנו במבוי סתום כאן ואין פתרון אלא אם נבדוק את זה בשליטה מרחוק באמצעות גישת
 SSH 
או משהו דומה, אבל אז התמיכה תהיה בתשלום

**Comment by shahafbs** [comment]
כמו שכתבתי זו התקנה על שרת מרוחק אני אני אבדוק עם החברה המארחת אני חושב שהם צריכים לספק לזה תשובה מכיוון שאני מבחינת הרשאות נתתי את כל מה שניתן.
 אני לא פוסל תמיכה בתשלום במקרה הצורך. 
אאדכן כאן 
תודה רבה!

**Comment by shahafbs** [comment]
לאחר שיחה עם התמיכה הם עלו על הבעיה.
ראשית אני מתנצל הבורות שלי עמדה כאן לרועץ. אז ככה:
מה שניסיתי לעשות לא נקרא שרת מרוחק אלא host sharing 
דרך אכסון אתרים. אז כפי הנראה ההתיחסות שלכם הייתה לא נכונה עקב מידע מוטעה.
לעניין הבעיה. ההתקנה זקוקה להרשאות של root ואת זה לא ניתן לקבל בשרותי אכסון אתה מקבל הרשאות לשם המשתמש שלך. 

האפשרויות שעומדות בפני עכשיו הן לבדוק אתכם האם יש אפשרות ברמת התכנה לעבוד ללא הרשאות root. 
והאפשרות השניה והיקרה יותר היא לרכוש vps  ואותו לנהל כפי שאני מנהל את השרת בבית. 
האפשרות השלישית ומסורבלת היא להמשיך לאכסן את התכנה בבית 
סליחה, ואשמח לכל עיצה
שחף

**Comment by adam2314** [comment]
אל תיהיה קשה אם עצמך:)
אז ככה אני יכול להבטיח לך שההתקנה לא זקוקה להרשאות מנהל.
(root)
אתה מתקין את לינט בתקיית השורש של האתר שלך, נכון?
התוכנה מנסה להתחבר בברירת המחדל עם מנהל.
במסך השני של ההתקנה 
צריך להזין
שם משתמש סיסמא ושרת למסד הנתונים שים לב ללחוץ על כפתור הרדיו
וללחוץ הבא
בשלב הזה אם הרשאות הכתיבה אצלך נכונות הקובץ
protected/config/install.php 
ייכתב מחדש עם הנתונים המעודכנים
)שם משתמש שהוא לא מנהל)
לאחר מכן תווצרנה טבלאות במסד הנתונים

והתוכנה תבקש ממך ליצור משתמש ראשי.

**Comment by shahafbs** [comment]
תודה אדם אז ככה:
מבחינת עץ הספריות אני מתקין את התכנה בתיקית השורש היינו ב 
/www/mysite.me
השם כמובן בדוי לצוך הדוגמה
עכשיו התיקייה yii 
נמצאת ב
/www

(זה הפתרון שאני מצאתי אולי זה קשור?)

נתתי הרשאות כתיבה לכל הקבצים והתיקיות כפי שצריך
שיניתי את הקובץ ונתתי שם משתמש וסיסמה למסד הנתונים 
ואנחנו במבוי הסתום שהיינו בו.

מה אתה חושב?

**Comment by shahafbs** [comment]
טוב הבעיה נפתרה
יש לי חבר טלפוני... והוא קצת התקשקש עם זה לא הייתה לו סבלנות להכנס להסברים אז אני אסביר בגדול את מה שהוא הסביר לי.
ואני מקווה שלא אעשה אוול להסבר.
אז מה שהוא אומר שתהליך ההתקנה לא ניהל נכון את יציר הקבצים והתיקיות ולכן היה צריך להתחקות אחרי התהליך וליצור או לשנות ידנית.
בכל אופן עכשיו נראה שהדברים עובדים
אני אתקדם לאט לאט לפי ההוראות ולפי השרשורים פה ונקווה שהכל יעבוד טוב
לילה טוב בינתיים
שחף

**Comment by starnetwork** [comment]
היי, נשמח אם הוא ישתף אותנו במסקנות שלו כדי שנוכל ללמוד ואולי שבפעם הבאה זה יתקין לך את זה בלי בעיה :)

**Comment by shahafbs** [comment]
אני חושב שאם היה לו זמן הוא היה עושה את זה בשמחה. 
הוא פשוט מאוד עסוק וגם את זה עשה כטובה אישית.
מה שכן אני חושב שתוכלו לשחזר את העניין
