### ISSUE TITLE
Version update notice - 404 error when clicking the update link (uppercase issue)

### ISSUE THREAD

**Issue by dan-omniscience** [adam2314/linet3#434]
Hi,
The link in the notice http://awesomescreenshot.com/086487ktba
is redirecting the user to: http://linet3.omniscience.co.il/newupdate
instead of: http://linet3.omniscience.co.il/newUpdate

Most server config (apache/nginx) will be case sensitive so this should be fix.

Best Regards

**Comment by adam2314** [comment]
thank you, ive updated the link.
