### ISSUE TITLE
הודעת שגיאה בכל מיני מצבים

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#435]
היי
ההודעה הזו מופיעה לאחר כל מיני נסיונות להתחלת עבודה:
Fatal error: Can't use method return value in write context in /mydomain.com/protected/models/Docs.php on line 272
כמעט כל נסיון לגשת לאיזה שהוא פריט מגיע לזה
חשבונית
קבלה
גם כאשר לוחצים על הלוגו ואמורים להגיע לדשבורד
וגם כאשר מנסים לכנס לחברה
בעצם אני מצליח לכנס רק דרך עריכה או משהו כזה לחברה.
(דרך אייקון קטן שנראה כמו שעון כאשר אני לוחץ על מנהל מערכת)
לפעמים מופיע למעלה משפט שאומר שצריך לעדכן ולחיצה עליו מובילה להודעה הזו:
Parse error: syntax error, unexpected '[' in.../protected/views/newUpdate/index.php on line 8

**Comment by shahafbs** [comment]
https://github.com/adam2314/linet3/issues/414

מצאתי את הקישור הזה ואני לא ממש מבין מה אני אמור לעשות שם. 
תזכורת אני על sharedhosting
ניסיתי לשנות בשורת הכתובת ל
https://www.mydomain.com:85/newupdate
אבל זה לא מגיע לשום מקום. 
וכמובן יש את ההודעה השניה.

**Comment by adam2314** [comment]
אהלן שחף
בוא תנסה לקחת ידנית את הקובץ
protected/models/Update.php
מהכתובת
https://github.com/adam2314/linet3/blob/master/protected/models/Update.php
ואז תנסה לעדכן את התוכנה.
אחרי זה נראה אם יהיו לך בעיות...

**Comment by shahafbs** [comment]
Parse error: syntax error, unexpected '[' in /var/www/seaking/data/www/shahafbs.com/protected/views/newUpdate/index.php on line 8

**Comment by shahafbs** [comment]
ניסיתי לקחת גם אותו ידנית והוא אומר לי שיש טעות בשורה 7
Parse error: syntax error, unexpected '[' in /var/www/seaking/data/www/shahafbs.com/protected/views/newUpdate/index.php on line 7

**Comment by adam2314** [comment]
תחליף את השורה
 $version = $model->getVersionI()["name"];
ב
 $version = $model->getVersionI();
$version = $version["name"];

**Comment by shahafbs** [comment]
אוקי זה הפעיל את אשף העידכון.
זה הפעיל אותו פעם אחת והייתי צריך לתת הרשאות לשני קבצים ואז לפתוח ידנית את קובץ הזים.
זה אפשר לתכנה להתחיל להראות תכנה שניתן לעבודה איתה וגם אמר שצריך להתקין עידכון

מה שקורא עכשיו זה שכל הקבצים המתעדכנים צריכים הרשאת כתיבה. 
השערה שלי היא מכיוון שהם שייכים ל משתמש אחר ואינם קשורים לקבוצה. 
ההרשאה שמשחררת אותם זה other
אחרי שנתתי הרשאות לכל . אני מקבל את ההודעה הזו:
Invalid argument supplied for foreach()

**Comment by adam2314** [comment]
שחף אני אני מצטער
אבל די
התוכנה צריכה הרשאות כתיבה גם לספריות בשביל ליצור מסמכים
גם בשביל העדכונים
ובטח שבשביל אשף ההתקנה
אם אתה לא מסוגל להגדיר את זה אין לי איך לעזוןר לך.

**Comment by shahafbs** [comment]
אדם יקר כפי שכתבתי נתתי הרשאות מלאות

 א ח ר י   שנתתי הרשאות מלאות זה המשפט שאני מקבל 
Invalid argument supplied for foreach()

למיטב ידיעתי זו לא בעיה של הרשאות.

**Comment by shahafbs** [comment]
ויתרה מכך הוא משכתב את הקובץ 
protected/views/newUpdate/index.php on line 8
 ומחזיר אותו למצב שהיה לפני השנוי שהצעת.
