### ISSUE TITLE
הודעת שגיאה בגיבוי בלינוקס

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#437]
שגיאה 500
fopen(/var/www/install/protected/config/../files/CA7_/db.sql): failed to open stream: No such file or directory Back
בחברה אחרת מקבל שגיאה זו 
בעיה בטעינת דף
החיבור הופסק

החיבור לשרת אותחל בזמן שהדף נטען.

    האתר איננו זמין כרגע או שהוא עמוס מדי. אנא נסה שוב בעוד מספר רגעים.
    אם אינך מצליח לטעון דפים כלשהם, בדוק את הקישוריות של המחשב שלך לרשת.
    אם המחשב או הרשת שלך מוגנים באמצעות חומת אש או שרת מתווך, ודא כי Firefox מורשה לגישה לרשת.

**Comment by shaulmani** [comment]
לאחר בדיקה התברר שהיו יותר מידי גיבויים בחברה

**Comment by adam2314** [comment]
טופלה הבעיה, זב כבר לא מגבה גיבויים
דבר שהופך את הגיבויי לגדול להחריד.
