### ISSUE TITLE
כמה שאלות לשלב שמיד אחרי ההתקנה

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#439]
ראשית בגיבוי מלינט 2 יש ספריה שלמה וגם קובץ באק איזה מהקבצים אני אמור ליבא?
שנית ניתן להכנס רק בתור מנהל ורק להגדרות כל נסיון אחר מוביל להודעות שגיאה כגון אלא:
https://github.com/adam2314/linet3/issues/435

אני השנה מתחיל רישום חדש לגמרי ולכן לא זקוק להגדרה של יתרות פתיחה. מה גם שגם לאחר נסיון של הגדרה ראשונית כפי שמתואר אין שינוי ולא ניתן להכנס לשום חברה שנוצרה. 

יום מקסים
שחף

**Comment by adam2314** [comment]
אתה מדבר על גיבויי כללי לפני עדכון(מחיל את כל החברות והנתונים)
אתה צריך לקחת גיבויי של חברה ספצפית מתוך לינט 2
ואז לייבא

**Comment by shahafbs** [comment]
או קי יבדק 

שאלה לפני שאני מתחיל כמה דברים. 
אני מתחיל הנהלת חשבונות חדשה וצריך מספור חדש וכו. 

זה אומר שאני פותח חברה חדשה לגמרי על גרסה שלוש.
אני רוצה ליבא את החומרים מהתכנה הישנה כדי שיהיו זמינים. 
האם תהליך היבוא ידרוס את כל החברות או שישאיר חברות חדשות שפתחתי?
תודה רבה
שחף

**Comment by adam2314** [comment]
היבוא מיועד לחברה אחת בלבד בכל פעם וידרוס את נתוני החברה
שדרכה מיבאים

**Comment by shahafbs** [comment]
מעולה תודה רבה!
