### ISSUE TITLE
כמה בעיות אחרי נסיון עדכון

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#440]
ראשית נסיון העידכון עוצר בהודעת השגיאה
Invalid argument supplied for foreach()
כפי שציינתי יש הרשאות מלאות לתיקיה
בנוסף הוא משכתב את הקובץ הזה
protected/views/newUpdate/index.php on line 8
ומחזיר אותו למצב שהיה לפני השנוי שהצעת.
ראיתי בקבצי המקור שתיקנתם את זה. אני שכתבתי אותו חזרה.

**Comment by aribhour** [comment]
שרת העדכונים נפל ולא היה פעיל בשעתיים האחרונות כנראה שזו הסיבה. תנסה לעדכן עכשיו

**Comment by shahafbs** [comment]
אני מבין שנמאס לך ממני אבל זה ממש לא מקצועי לתת תשובה ולסגור את הט'רד מיד אחר כך.
במיוחד שהבעיה לא נפתרה עם עליתו מחדש של השרת 
וכמו שכתבתי הוא משכתב את הקובץ ומחזיר אותו לנוסח שאינו עובד ואני צריך לשכתב אותו.
