### ISSUE TITLE
משתמשים אינם יכולים להכנס לחברה

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#442]
גם לאחר הקצאת תפקיד
אחרי לוגאין מופיע מסך נטול חברות

**Comment by adam2314** [comment]
אני יודע שעוד אין תיעוד לזה והממשק לא ככ ברור
אבל
(במסך של בחירת החברה)
עם משתמש העל אתה נכנס לניהול מערכת ואז לחיצה על הסמליל של המשתמש
ותוכל להוסיף משתמשים לחברה
ואז רק תוכל להתחבר לחברה עם משתמש חדש
