### ISSUE TITLE
תקלה במחיקת משתמש מחברה

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#444]
×‘×—×¨ ×—×‘×¨×”
 	 	User	 
3	Fatal error: Call to a member function getName() on a non-object in  /yii/framework/base/CComponent.php(612) : eval()'d code on line 1

**Comment by adam2314** [comment]
אתה חייב לפרט יותר.
לפחות באיזה מסך את המקבל את התקלה
האם הצלחת למחוק את המשתמש?

**Comment by shahafbs** [comment]
ההודעה מתקבלת מיד לאחר נסיון הסרת משתמש מחברה. 
מאותו מסך שמקצים משתמש לחברה
המשתמש אכן נמחק סליחה שלא טרחתי לבדוק.
