### ISSUE TITLE
המלצה להוסיף אפשרות לנתק משתמש מהמערכת 

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#445]
כשנכנסים למערכת נרשמים ובעצם אין אפשרות לצאת ממשתמש אחד ולהכנס עם משתמש אחר.

**Comment by adam2314** [comment]
ואני הייתי בטוח שכפתור אדום בסיידבר יבהיר את המסר
אם אתה מדבר על לוח המכוונים אתה יכול להציג את הסיידבר עם לחיצה על הכפתור הירוק
