### ISSUE TITLE
בקשה : לפתוח אפשרות לבדיקת נתונים של עסקים, תודה.

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#449]

**Comment by aribhour** [comment]
איזה נתונים? ואיזה עסקים? אתה מתכוון ללקוחות?

**Comment by shaulmani** [comment]
נגיד אני ספר שמשתמש בלינט. שהמערכת תתריע אם יש שגיאות כמו חובה וזכות לא
מאוזן, שיבוש ברצף מיסמכים. כבר קרה שפתחתי חברה והיו שיבושים. אדם בדק והסביר
שהחברה לא נפתחה טוב. שיהיה אפשרות לבדוק את ההנהח לא ברמת התוכן כי אם ברמת
המערכת
בתאריך 26 בפבר' 2015 08:52, ‏"aribhour" <notifications@github.com> כתב:

**Comment by aribhour** [comment]
שאול אני לא מבין, חובה וזכות לא מאוזן בכרטסת ספק או לקוח זה לא שיבוש אלא מצב נפוץ מאוד שאחד הצדדים חייב למי שמנהל את החשבונות כסף או הפוך...
השיבוש האפשרי היחיד זה רצף מסמכים לא תקין...
תקן אותי אם אני טועה.
אדם, צריך למצוא איזשהו ממשק יאפשר בדיקה של רצף מסמכים כי זו גם דרישה של רשות המסים

**Comment by shaulmani** [comment]
הדרישה היא כפילות ורצף מסמכים.
בנוסף קרה שעבדתי על חברה ודברים לא הסתדרו.
לאחר בדיקה אדם הסביר שהחברה נפתחה בצורה לא תקינה או השתבשה.
זה גרם לכך שלדוגמה סה"כ חובה וזכות ביתרות לא מתאים או דוחות לא הופקו נכון.
איך אפשר למנוע מצב זה...

בתאריך 4 בספטמבר 2015 בשעה 19:04, מאת aribhour <notifications@github.com>:

**Comment by aribhour** [comment]
Fixed. There is a module for checking doc numbering consistency that will be available next update.

**Comment by shaulmani** [comment]
👍
בתאריך 22 בספט' 2015 14:20,‏ "aribhour" <notifications@github.com> כתב:
