### ISSUE TITLE
הודעת שגיאה לאחר עדכון אחרון

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#450]
שגיאה 500
Illegal string offset 'name' Back

**Comment by aribhour** [comment]
שאול
אתה כבר יותר מדי מנוסה מכדי להשאיר הודעה כזו שמשאירה אותנו בפה פעור וסימן שאלה בעיניים 
1. מה ניסית לעשות לאחר העדכון לפני שיצאה הודעת השגיאה
2. באיזה מסך של התוכנה 
3. האם כל שאר הפונקציות בתוכנה עובדות

**Comment by shaulmani** [comment]
אעדכן שוב חייב לצאת
מתנצל

**Comment by shaulmani** [comment]
התחברתי לתוכנה, לחצתי עדכן וראיתי שיש עדכון.
המשכתי בתהליך העדכון וקמתי מהמחשב. כשחזרתי למחשב אחרי כמה דקות והמסך נראה קפוא ולא מגיב.
יצאתי, התחברתי שוב רציתי לעדכן וזאת ההודעה.
כל השאר נראה תקין ועובד למעט האפשרות לבצע את הגיבוי.

**Comment by shaulmani** [comment]
ההודעה הקודמת בלינוקס
בחלונות נותן הודעת שגיאה זו

PHP warning

Illegal string offset 'name'

C:\Program Files\linet\apache\htdocs\protected\views\newUpdate\index.php(9)

01 <?php
02 /*
03  * To change this license header, choose License Headers in Project Properties.
04  * To change this template file, choose Tools | Templates
05  * and open the template in the editor.
06  */
07 
08 $version = $model->getVersionI()["name"];
09 $version = $version["name"];
10 $sversion = $model->getSVersion();
11 
12 
13 $this->beginWidget('MiniForm', array(
14     'header' => Yii::t('update', "Update Wizard"),
15 ));
16 ?>
17 <div id='conUpdate'>
18     <div class="updatetext">
19         <?php echo Yii::t('update', "Welcome To Linet update wizard your system version is:") ." ". $sversion; ?><br />
20         <?php echo Yii::t('update', "The current version is:") ." ". $version; ?> 
21         <br />

Stack Trace
#0 	
+
 C:\Program Files\linet\yii\web\CBaseController.php(126): require("C:\Program Files\linet\apache\htdocs\protected\views\newUpdate\i...")
#1 	
+
 C:\Program Files\linet\yii\web\CBaseController.php(95): CBaseController->renderInternal("C:\Program Files\linet\apache\htdocs\protected\views\newUpdate\i...", array("model" => Update), true)
#2 	
+
 C:\Program Files\linet\yii\web\CController.php(869): CBaseController->renderFile("C:\Program Files\linet\apache\htdocs\protected\views\newUpdate\i...", array("model" => Update), true)
#3 	
+
 C:\Program Files\linet\yii\web\CController.php(782): CController->renderPartial("index", array("model" => Update), true)
#4 	
–
 C:\Program Files\linet\apache\htdocs\protected\components\RightsController.php(54): CController->render("index", array("model" => Update), false)

49 
50     public function render($view, $data = NULL, $return = false) {
51         if (isset($_POST['minimal'])) {
52             echo CJSON::encode(parent::renderPartial($view, $data, true));
53         } else {
54             return parent::render($view, $data, $return);
55         }
56     }
57 
58     public function init() {
59         /*

#5 	
–
 C:\Program Files\linet\apache\htdocs\protected\controllers\NewUpdateController.php(27): RightsController->render("index", array("model" => Update))

22     public function actionIndex() {
23         $model = new Update;
24 
25         $this->render('index', array(
26             'model' => $model,
27         ));
28     }
29 
30     public function actionBackup() {
31         $model = new Update;
32 

#6 	
+
 C:\Program Files\linet\yii\web\actions\CInlineAction.php(49): NewUpdateController->actionIndex()
#7 	
+
 C:\Program Files\linet\yii\web\CController.php(308): CInlineAction->runWithParams(array())
#8 	
+
 C:\Program Files\linet\yii\web\filters\CFilterChain.php(133): CController->runAction(CInlineAction)
#9 	
+
 C:\Program Files\linet\yii\web\filters\CFilter.php(40): CFilterChain->run()
#10 	
–
 C:\Program Files\linet\apache\htdocs\protected\modules\rights\components\RController.php(36): CFilter->filter(CFilterChain)

31     */
32     public function filterRights($filterChain)
33     {
34         $filter = new RightsFilter;
35         $filter->allowedActions = $this->allowedActions();
36         $filter->filter($filterChain);
37     }
38 
39     /**
40     * @return string the actions that are always allowed separated by commas.
41     */

#11 	
+
 C:\Program Files\linet\yii\web\filters\CInlineFilter.php(58): RController->filterRights(CFilterChain)
#12 	
+
 C:\Program Files\linet\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(CFilterChain)
#13 	
+
 C:\Program Files\linet\yii\web\CController.php(291): CFilterChain->run()
#14 	
+
 C:\Program Files\linet\yii\web\CController.php(265): CController->runActionWithFilters(CInlineAction, array("rights"))
#15 	
+
 C:\Program Files\linet\yii\web\CWebApplication.php(282): CController->run("")
#16 	
+
 C:\Program Files\linet\yii\web\CWebApplication.php(141): CWebApplication->runController("newUpdate")
#17 	
+
 C:\Program Files\linet\yii\base\CApplication.php(180): CWebApplication->processRequest()
#18 	
+
 C:\Program Files\linet\apache\htdocs\index.php(23): CApplication->run()
2015-01-30 12:32:45 Apache Yii Framework/1.1.14

**Comment by adam2314** [comment]
צודק

**Comment by shaulmani** [comment]
היי אדם,
הודעת השגיאה  ממשיכה.
האם אפשר לעבוד או להמתין לעדכון ?
תודה שאול​

2015-02-01 10:18 GMT+02:00 adam2314 <notifications@github.com>:
