### ISSUE TITLE
תקלה - לא ניתן להגיע לחשבוניות מהדשבורד

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#451]
מציג 404 הקובץ אינו קיים

**Comment by adam2314** [comment]
אתה יכול לפרט בבקשה?
באיזה ווידג'אט מדובר האם?
האם החשבונית קיימת במערכת בכלל?

**Comment by shahafbs** [comment]
בוודג'ט של חשבוניות לגביה הן נראות כקישור והקישור מוביל ל 404 בטענה שהקובץ אינו קיים

**Comment by adam2314** [comment]
אהלן
אני לא מצליח לשחזר את הבעיה
הלינק שנוצר:
docs/view/<id>
שהוא חוקי לחלוטין

אני רוצה לסגור את הבאג הזה
אלא אם יש לך משהו להוסיף.

**Comment by shahafbs** [comment]
אני נכון לעכשיו תקוע עם הבעיה השניה אז לא יכול לבדוק שום דבר.
אנסה את זה שוב אחרי שאסדר את הבעיה. 
תסגור בינתיים 
תודה
