### ISSUE TITLE
הדפסה לא נכונה של חשבוניות 

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#452]
אולי במסמכים אחרים גם.
אחרי שכתבתי חשבונית ולחתי על הדפסה הוא מדפיס כביכול את כל העמוד עם כל הפרטים כולל הכפתורים קישורים וכו. 
ולא רק את החשבונית.
הבעיה היא שזה סופר את הדפסת החשבונית...
אחר כך אם מנסים להדפיס את ההעתק הוא מדפיס ללא בעיה.
פרט לבעיה שמדובר בהעתק כמובן.

העניין לדעתי קורה כאשר פותחים את החשבונית מטיוטא.

**Comment by adam2314** [comment]
אני לא מצליח לשחזר את התקלה אצלי.
גם שאני יוצר טיוטא לפני.

באיזה דפדפן אתה משתמש?

**Comment by shahafbs** [comment]
כרומיום

**Comment by shahafbs** [comment]
נסה להדפס את הטיוטא

**Comment by adam2314** [comment]
כתבתי שניסיתי.
זה לא קורה תנסה בבקשה להריץ את העדכון
אם הבעיה קיימת אני צריך הסבר מפורט 
מהשלב של יצירת חברה

אני מנסה על פיירפוקס וכרום אצלי 
ואפילו על כמה ווינדוסים ולא מצליח לייצר את הבאג.

**Comment by shahafbs** [comment]
אוקי זה באמת לא עקבי
אני לא משתמש בכרום אלא כרומיום. אני מניח שזה אותו דבר פשוט על פלטפורה של לינוקס.
ככה זה נראה
https://drive.google.com/file/d/0B5pKdDAUHAWeVU1vNXpHSmw3TjA/view?usp=sharing

**Comment by adam2314** [comment]
פעם הבאה יהיה לנו יותר קל אם תנסה לשפוך כמה שיותר אינפורמציה מהתחלה.
בכל מקרה מציאה טובה
הבאג מופיע בשכפול מסמכים ורק בהדפסה ראשונה באמת
לא משנה באיזה דפדפן

בוא תנסה לעדכן 
גריסה 3.01227
סוגרת את העניין

אגב כרומיום הוא פשוט גרסה פתוחה של כרום
יש אפילו למי שרחמנא לצלן רוצה להשתמש בווינדוס
