### ISSUE TITLE
תקלה מוזרה אחרי מחיקת חברה

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#454]
לא נתקלתי בתקלה הזו קודם לכן. וכבר מחקתי חברות 
אחרי מחיקת חברה ממשק מנהל מערכת אחרי לוגאין אני מגיע להודעת זגיאה הזו:

CDbException

The table "{{config}}" for active record class "Settings" cannot be found in the database.

/www/yii/framework/db/ar/CActiveRecord.php(2385)

זה הפלט:

CDbException

The table "{{config}}" for active record class "Settings" cannot be found in the database.

/var/www/seaking/data/www/yii/framework/db/ar/CActiveRecord.php(2385)

2373 
2374     /**
2375      * Constructor.
2376      * @param CActiveRecord $model the model instance
2377      * @throws CDbException if specified table for active record class cannot be found in the database
2378      */
2379     public function __construct($model)
2380     {
2381         $this->_modelClassName=get_class($model);
2382 
2383         $tableName=$model->tableName();
2384         if(($table=$model->getDbConnection()->getSchema()->getTable($tableName))===null)
2385             throw new CDbException(Yii::t('yii','The table "{table}" for active record class "{class}" cannot be found in the database.',
2386                 array('{class}'=>$this->_modelClassName,'{table}'=>$tableName)));
2387                 
2388         if(($modelPk=$model->primaryKey())!==null || $table->primaryKey===null)
2389         {
2390             $table->primaryKey=$modelPk;
2391             if(is_string($table->primaryKey) && isset($table->columns[$table->primaryKey]))
2392                 $table->columns[$table->primaryKey]->isPrimaryKey=true;
2393             elseif(is_array($table->primaryKey))
2394             {
2395                 foreach($table->primaryKey as $name)
2396                 {
2397                     if(isset($table->columns[$name]))
Stack Trace
#0	
+  /var/www/seaking/data/www/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Settings)
#1	
+  /var/www/seaking/data/www/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2	
+  /var/www/seaking/data/www/yii/framework/db/ar/CActiveRecord.php(1490): CActiveRecord->getTableSchema()
#3	
–  /var/www/seaking/data/www/shahafbs.com/protected/models/User.php(141): CActiveRecord->findByPk("company.1.certpasswd")
136         return $this->warehouse;
137     }
138 
139     public function getCertPasswd() {
140         if (isset(Yii::app()->user->Database)) {
141             $a = Settings::model()->findByPk("company." . $this->id . ".certpasswd");
142             if ($a !== null) {
143                 $this->certpasswd = $a->value;
144             }
145         }
146         return $this->certpasswd;
#4	
–  /var/www/seaking/data/www/shahafbs.com/protected/models/User.php(175): User->getCertPasswd()
170         return $res;
171     }
172 
173     public function afterFind() {
174 
175         $this->certpasswd = $this->getCertPasswd();
176         return parent::afterFind();
177     }
178 
179     private function certpasswdSave($passwd) {
180         $model = Settings::model()->findByPk("company." . $this->id . ".certpasswd");
#5	
+  /var/www/seaking/data/www/yii/framework/db/ar/CActiveRecord.php(1871): User->afterFind()
#6	
+  /var/www/seaking/data/www/yii/framework/db/ar/CActiveRecord.php(1892): CActiveRecord->populateRecord(array("id" => "1", "username" => "shahafbs", "fname" => "Shahaf", "lname" => "BS", ...), true)
#7	
+  /var/www/seaking/data/www/yii/framework/db/ar/CActiveRecord.php(1356): CActiveRecord->populateRecords(array(array("id" => "1", "username" => "shahafbs", "fname" => "Shahaf", "lname" => "BS", ...), array("id" => "2", "username" => "sha", "fname" => "", "lname" => "sha", ...)), true, null)
#8	
+  /var/www/seaking/data/www/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(CDbCriteria, true)
#9	
–  /var/www/seaking/data/www/shahafbs.com/protected/controllers/SiteController.php(41): CActiveRecord->findAll()
36     /**
37      * Displays the login page
38      */
39     public function actionLogin() {
40 
41         if(User::model()->findAll()==null){
42             $this->redirect(Yii::app()->createAbsoluteUrl('install/user'));
43                 Yii::app()->end();
44         }
45         
46         
#10	
–  /var/www/seaking/data/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
44         $controller=$this->getController();
45         $method=new ReflectionMethod($controller, $methodName);
46         if($method->getNumberOfParameters()>0)
47             return $this->runWithParamsInternal($controller, $method, $params);
48 
49         $controller->$methodName();
50         return true;
51     }
52 }
#11	
+  /var/www/seaking/data/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(array())
#12	
+  /var/www/seaking/data/www/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(CInlineAction)
#13	
+  /var/www/seaking/data/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#14	
+  /var/www/seaking/data/www/yii/framework/web/CController.php(1145): CFilter->filter(CFilterChain)
#15	
+  /var/www/seaking/data/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(CFilterChain)
#16	
+  /var/www/seaking/data/www/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(CFilterChain)
#17	
+  /var/www/seaking/data/www/yii/framework/web/CController.php(291): CFilterChain->run()
#18	
+  /var/www/seaking/data/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array("accessControl"))
#19	
+  /var/www/seaking/data/www/yii/framework/web/CWebApplication.php(282): CController->run("login")
#20	
+  /var/www/seaking/data/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController("site/login")
#21	
–  /var/www/seaking/data/www/yii/framework/base/CApplication.php(184): CWebApplication->processRequest()
179     public function run()
180     {
181         if($this->hasEventHandler('onBeginRequest'))
182             $this->onBeginRequest(new CEvent($this));
183         register_shutdown_function(array($this,'end'),0,false);
184         $this->processRequest();
185         if($this->hasEventHandler('onEndRequest'))
186             $this->onEndRequest(new CEvent($this));
187     }
188 
189     /**
#22	
–  /var/www/seaking/data/www/shahafbs.com/index.php(23): CApplication->run()
18     $config=require_once($load);
19 }else{
20     $config=dirname(__FILE__).'/protected/config/main.php';
21 }
22 
23 Yii::createWebApplication($config)->run();
2015-01-31 08:26:25 Apache/2.2.16 (Debian) Yii Framework/1.1.16

**Comment by adam2314** [comment]
בקשר לבאג הזה:
אני מכיר אותו והוא כבר טופל בעדכון האחרון
יש לך שתי אפשריות מרכזיות
להתחבר למסד הנתונים ובטבלה databases
למחוק את החברה הרלוואנטית

למשוך ידנית\באמצעות העדכון
(לא מאמין שאתה יכול להגיע לעדכון כעת)
את הקבצים
/protected/models/User.php
/protected/models/Company.php

אמור לפתור את זה
בהצלחה
ואנא עדכן כשיש התקדמות

**Comment by shahafbs** [comment]
משכתי ידנית ואני מגיע לזה:
CException

Property "RWebUser.settings" is not defined.

/var/www/seaking/data/www/yii/framework/web/auth/CWebUser.php(146)

134 
135     /**
136      * PHP magic method.
137      * This method is overriden so that persistent states can be accessed like properties.
138      * @param string $name property name
139      * @return mixed property value
140      */
141     public function __get($name)
142     {
143         if($this->hasState($name))
144             return $this->getState($name);
145         else
146             return parent::__get($name);
147     }
148 
149     /**
150      * PHP magic method.
151      * This method is overriden so that persistent states can be set like properties.
152      * @param string $name property name
153      * @param mixed $value property value
154      */
155     public function __set($name,$value)
156     {
157         if($this->hasState($name))
158             $this->setState($name,$value);
Stack Trace
#0	
+  /var/www/seaking/data/www/yii/framework/web/auth/CWebUser.php(146): CComponent->__get("settings")
#1	
–  /var/www/seaking/data/www/shahafbs.com/protected/models/Menu.php(130): CWebUser->__get("settings")
125     private static function buildMenu($id) {
126 
127         $known = Menu::model()->findAllByAttributes(array('parent' => $id),array('order'=>'sort'));
128         $menu = array();
129         foreach ($known as $item) {
130             if ((($item->id == 43) || ($item->id == 43) || ($item->parent == 43)) && (Yii::app()->user->settings['company.doublebook'] == 'false')) {
131                 continue;
132             }
133             //echo "  ".$item->id." ".$item->label."<br />";
134             $url = str_replace('/', '.', $item->url);
135             if (Yii::app()->user->checkAccess($url)) {//if has access
#2	
–  /var/www/seaking/data/www/shahafbs.com/protected/models/Menu.php(122): Menu::buildMenu(0)
117     public static function buildUserMenu() {
118         if (Yii::app()->user->isGuest) {
119             return array(array('label' => Yii::t('app', 'Login'), 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest));
120         }
121 
122         return Menu::buildMenu(0);
123     }
124 
125     private static function buildMenu($id) {
126 
127         $known = Menu::model()->findAllByAttributes(array('parent' => $id),array('order'=>'sort'));
#3	
–  /var/www/seaking/data/www/shahafbs.com/protected/models/Company.php(30): Menu::buildUserMenu(array("company.logo" => "110", "company.name" => "גם כן נסיון...", "company.vat.id" => "034088369", "company.website" => "", ...))
25             
26             foreach ($temp as $key) {
27                 $settings[$key->id] = $key->value;
28             }
29             
30             Yii::app()->session['menu']=Menu::model()->buildUserMenu($settings);
31         }
32         
33         Yii::app()->session['settings']=$settings;
34         
35         
#4	
+  /var/www/seaking/data/www/shahafbs.com/protected/models/Company.php(57): Company->loadSettings()
#5	
+  /var/www/seaking/data/www/shahafbs.com/protected/components/RightsController.php(83): Company->loadComp(Company)
#6	
+  /var/www/seaking/data/www/shahafbs.com/protected/controllers/CompanyController.php(23): RightsController->init()
#7	
+  /var/www/seaking/data/www/yii/framework/web/CWebApplication.php(281): CompanyController->init()
#8	
+  /var/www/seaking/data/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController("company")
#9	
+  /var/www/seaking/data/www/yii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#10	
+  /var/www/seaking/data/www/shahafbs.com/index.php(23): CApplication->run()

**Comment by adam2314** [comment]
אוקיי אז אתה גירסה אחורה ממה שחשבתי.
צריך עוד שניים
/protected/config/main.php
/protected/components/WebUser.php

**Comment by shahafbs** [comment]
זה איפס את האפשרות לרענן את הדף. ויכולתי לעשות לוג אין שוב. 
יחד עם זאת זה מציג את אותה שגיאה בדיוק...

**Comment by adam2314** [comment]
אז קראתי שוב את השגיאה וצריך עוד קובץ
/protected/models/Menu.php

**Comment by shahafbs** [comment]
אוקי יופי זה סידר את הבעיה.
עכשיו רק נותר לפתור את הבעיה עם העדכון...
