### ISSUE TITLE
duplicate pdf document

### ISSUE THREAD

**Issue by dan-omniscience** [adam2314/linet3#456]
In related to the previous issue  #455 after I printed the unsigned document I used the PDF button to create a sign one, the sign pdf that was created was stated as a duplicate(I don't have the source as a pdf file now).

Also It seems that as a duplicate document the logo file is missing(There's a red "X" where the logo should be present) in the signed source documents I created the logo appeared correctly.

**Comment by aribhour** [comment]
Hi Dan
The behavior you described is obligatory by tax authority regulation. After producing a document once it is obligatory to mark the second printout (in any form, doesn't matter whether it is direct print or pdf  file) as a "copy" document. 
The only solution to your misuse is to mark the document as "identical to the original" and sign it manually if it is a physical printout or add the mentioned signature and markup by third party pdf editing app if it is a pdf file.
As for the described behavior that the copy doc doesn't show the logo: It seems that I can't reproduce this issue on any instance of Linet we have here. The behavior is identical for both original and copy documents. Maybe you have deleted the logo? Can it be that you changed the working company to a company without logo and you forgot about it?
Please double check yourself and report back.
