### ISSUE TITLE
בבקשה לאפשר לעדכן הערות לאחר הפקת מסמך 

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#457]
דוגמה לציין בהערה שמספר שיק שגוי צ"ל מספר אחר או תיקון תאריך השיק
זה מותר כל עוד יש מעקב תיקונים.
השינוי לא משנה את הסכום החשבונות תאריך הפקה או אסמכתה כי אם שדות נילווים.

**Comment by aribhour** [comment]
Second that

**Comment by shaulmani** [comment]
?
לא הבנתי

**Comment by adam2314** [comment]
done
