### ISSUE TITLE
בעיה בעידכון התכנה

### ISSUE THREAD

**Issue by shahafbs** [adam2314/linet3#458]
טוב, אני רוצה להכנס לעובי הקורה בכל מה שקשור לעדכון. 
אני משתמש בשרות אכסון אתרים.  על שרת לינוקס.
יש הרשאות מלאות לתיקיה של התכנה.
 בזמן עידכון ישנם קבצים שמגיעים שהבעלים שלהם זה www-data 
ואז מה שנוצר זו בעיה שהם לא מקבלים את ההרשאות של התיקיה עצמה. 
השינוי של ההרשאות מצריך שינוי של הבעלים של הקובץ ידנית וזה לכשעצמו תוקע את התהליך של ההתקנה. 

אשמח לעיצה בעניין
שחף

**Comment by aribhour** [comment]
שחף, זה לא באג בתוכנה אלא אי התאמה לדרישות חומרה ותוכנה בסיסיות של התכנה
