### ISSUE TITLE
אסמכתא חיצונית לא נקלטת במערכת בקליטת הוצאה עסקית

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#459]
בקליטת מסמך דרך קליטת הוצאה עסקית מספר החשבונית (אסמכתא) נרשם בשדה אסמכתא חיצונית אך לא מופיע בדוחות.
מופיע רק מספר רכש שוטף באסמכתא 1. שדה אסמכתא 2 נשאר ללא תוכן.

**Comment by adam2314** [comment]
יופיע בתנועות יומן החל מ
(3.01233)

**Comment by shaulmani** [comment]
לא ברור מה כתבת....
בתאריך 25 בפבר' 2015 18:52, ‏"adam2314" <notifications@github.com> כתב:

**Comment by aribhour** [comment]
אדם מתכוון לזה שהבעיה תטופל במסגרת גרסה מספר 3.01233 שאנחנו נכניס לשרת העדכונים היום או מחר לאחר סיום 
הבדיקות 
בינתיים מספר הגרסה שתהיה מחר זמינה להורדה תהיה ספרה אחת קדימה

**Comment by shaulmani** [comment]
תודה
בתאריך 25 בפבר' 2015 20:35, ‏"aribhour" <notifications@github.com> כתב:
