### ISSUE TITLE
עוסק פטור/עמותה רששומה

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#462]
<p>שלום וברכה</p>
<p>לא מצאתי אפשרות להגדיר את העסק שלי כעוסק פטור</p>
<p>אשמח לדעת איך ואם יש פיתרון לעניין (האפשרות היחידה היא ע.מ/ח.פ.) תודה</p>
<p>&nbsp;</p>
<p>כמו כן איך אני מגדיר לקוח שהוא עמותה (גם שם&nbsp;האפשרות היחידה היא ע.מ/ח.פ.) תודה</p>

**Comment by aribhour** [comment]
התוכנה לא בנויה לעוסק פטור כעיקרון. אבל מאחר ועוסק פטור אינו גובה מע"מ הוא אינו צריך להוציא חשבוניות ללקוחותיו וכן הנהלת החשבונות שלו פשוטה הרבה יותר. הוא לא צריך להשוות כל הזמן ולדאוג שכל חשבונית נסגרת מול קבלה כי הוא מוציא רק קבלות כנגד תשלום. אז מה הבעיה להוציא רק קבלות בתוכנה ותו לא?
באשר לרישום עמותה בתור לקוח: שדה מספר עוסק מורשה/ח.פ. יכול לקבל גם מספר עמותה בפרטי לקוח /ספק או כל חשבון אחר לצורך העניין.

**Comment by urinka** [comment]
אבל היא היחידה שמציעה את עצמה בחינם (עד כמה שאני יודע ) ומאפשרת התרחבות עתידית ללא תשלום נוסף ... 
נכון??

**Comment by aribhour** [comment]
נכון
