### ISSUE TITLE
איך מעדכנים מוצר ללא מעמ

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#475]
<p>ניסיתי בכל מיני מקומות, ותמיד כשהכנתי הצעת מחיר הוא חישב לי מעמ</p>
<p>תודה רבה</p>

**Comment by shaulmani** [comment]
בעיקרון בהפקת מסמך יש חשבון נגדי. 
בהוצאה אם חשבון ההוצאה פטור ממעמ תקבל עסקה ללא מעמ.
זה היה קיים גם בהכנסות. 
האפשרות לבחירת חשבון הכנסה במסגרת הפקת מסמך הכנסה כנראה נעלמה בטעות מתי שהוא במסגרת העידכונים. 
(אדם זה היה, אני בטוח,ראה נושא 182, משוכנע שבדקתי וראיתי שזה קיים ועובד).
אני בטוח שזה יחזור בקרוב במסגרת העידכונים (:

**Comment by shaulmani** [comment]
גם אני רוצה יחס (:

**Comment by adam2314** [comment]
שאול מעולם לא הייתה לנו אפשרות לבחירת חשבון הכנסה. ברמת מסמך
חשבון הכנסה תמיד נלקח מתוך הפריט וכך גם חישוב המעמ

**Comment by shaulmani** [comment]
אתה מוכן לפרט בבקשה ? לא מסתדר.
פתחתי פריט הכנסה פטורה, קטגוריית מעמ פטור ממעמ, מפיק חשבונית עם פריט זה,
ואין הבדל בין זה למצב רגיל.
איפה אני טועה ?
תודה, כי השאלה נשארה פתוחה.
