### ISSUE TITLE
UX Feedback from customer

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#476]
Hi,
1. every time I want to create doc and than I create new client and it's not back to the doc page and I need to re-enter to the doc page, same for new items, very frustrating

2. at the step of the doc confirmation, the "Print" option, the browser "Back" button back only to the print page and not back to the "Linet" doc pages, and when I want to create multiple docs, I need to back to the docs creation again and again, it's will be better to ask the manager Where he wants to go back.

**Comment by aribhour** [comment]
Duplicate with #188
