### ISSUE TITLE
הפיתרון של עיגול סכומים יוצר בעיה. קניות יבוא ללא מעמ 100.01 ספק 100. המערכת לא מאוזנת. 

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#477]
רכש שוטף	קניות יבוא-ללא מע"מ	רכש שוטף #1		ספקים שונים	11/02/2015 21:02:46	11/02/2015 21:10:46	-100.01	
1	רכש שוטף	ספקים שונים	רכש שוטף #1		ספקים שונים	11/02/2015 21:02:46	11/02/2015 21:10:46		100.00
ראה דוח יתרות
מזהה	שם	חובה	זכות	סכום	מזהה 6111
	לקוחות				
	סה"כ	0	0	0	
	ספקים				
114	ספקים שונים	0	100	100	0
	סה"כ	0	100	100	
	הוצאות				
18	קניות יבוא-ללא מע"מ	-100.01	0	-100.01	1340
	סה"כ	-100.01	0	-100.01	
	הכנסות				
	סה"כ	0	0	0	
	נכסים				
	סה"כ	0	0	0	
	חובות				
	סה"כ	0	0	0	
	רשויות				
	סה"כ	0	0	0	
	בנקים				
	סה"כ	0	0	0	
	מחסנים				
	סה"כ	0	0	0	
	לידים				
	סה"כ	0	0	0	
	אנשי קשר				
	סה"כ	0	0	0	
	Sub Total	-100.01	100	-0.01

**Comment by aribhour** [comment]
לא ברור בכלל איפה החוסר איזון. נראה לי שאתה יוצא מנקודת הנחה שאנחנו אנשי הנהלת חשבונות ואנחנו לא. ענייני הנהלת חשבונות צריך להסביר לנו לאט וכמו לילד מפגר
:-)

**Comment by shaulmani** [comment]
אתה יודע רק לא מקשר. לימדתי רו"חים בהתמחות שהבינו פחות. כשרושמים פקודת יומן
צד חובה וצד זכות חייבים להיות שווים.
בהפקת דוח יתרות סהכ חובה וזכות צל שווה יתרה אפס.
הדוגמה שהראתי מראה כי כרגע זה לא המצב. אחלה יום (:
בתאריך 12 בפבר' 2015 07:16, ‏"aribhour" <notifications@github.com> כתב:

**Comment by shaulmani** [comment]
בבקשה לשים לב שמדובר בהוצאה.
יתכן ואני מטעה באמירה שזה קשור לעיגול סכומים ומדובר בבעיה אחרת.

**Comment by adam2314** [comment]
אהלן
אתה צריך להסביר טוב יותר; יצרתי אצלי פריט ללא מעמ ויצרתי הוצעה עיסקית על סך 100.01 זה לא ניסה לעגל לי אגורות.

**Comment by shaulmani** [comment]
עשיתי כך,
הוצאות, קליטת הוצאה עסקית, קניות יבוא ללא מע"מ, ספקים שונים מקט כללי 100 ש"ח
פקודה יוצאת כמו שכתבתי.
חובה קניות יבוא 100.01
זכות ספק 100
לאן נעלמה האגורה ?
היה צריך לראות אותה בדוח יתרות נגיד בעיגול סכומים או משהוא כזה...
להבנתי זה מחייב פתרון מיידי

**Comment by adam2314** [comment]
טופל
(3.01233)
