### ISSUE TITLE
לא ניתן ליצור סוג מסמך חדש, יש צורך להשלים פרטים שאין גישה לשדות שלהם.

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#478]
.

**Comment by aribhour** [comment]
קודם כל בוא נתחיל מזה : איזה סוג מסמך בכלל חסר לךבמערכת?

**Comment by shaulmani** [comment]
מקביל לחשבונית שריון בחשבשבת. להפיק חשבונית מס עם התחשבנות אך ללא נגיעה
במלאי עפ הזמנה. בעת האספקה להוציא ת.מ. שתסגור הפריטים.
בתאריך 12 בפבר' 2015 07:17, ‏"aribhour" <notifications@github.com> כתב:

**Comment by aribhour** [comment]
בלינט כבר קיים פיתרון לנושא הפקת מסמכים מבלי ליצור תנועת מלאי: במסכי הפקת מסמכים רלווינטיים שיוצרים תנועת מלאי בברירת מחדל יש שדה קטן שלא שמת לב אליו כנראה והוא "צור תנועת מלאי" . בברירת מחדל הוא מסומן ב
V
תוריד את ה
V
והמסמך לא ייצור תנועת מלאי

**Comment by shaulmani** [comment]
ראיתי חשבתי ליצור מסמך שיהיה כך קבוע במקום להתעסק כל פעם ב-וי.
האם יש לזה פתרון?
בתאריך 12 בפבר' 2015 07:53, ‏"aribhour" <notifications@github.com> כתב:

**Comment by aribhour** [comment]
לא בגרסה הנוכחית. אין אפשרות ליצור בכלל סוג מסמך חדש על ידי ממשק המשתמש. כרגע התכונה הזו לא פעילה וצריך להוריד אותה מהתפריט

**Comment by adam2314** [comment]
אם אתה לא מוצא את זה ביציירת סוג מסמך דבר איתי

**Comment by shaulmani** [comment]
עשיתי כך,
הגדרות, ניהול סוגי מיסמכים, צור סוג מסמך, מגדיר וזה מופיע

Please fix the following input errors

    האם מסמך בפורמט חוזה cannot be blank.
    האם מבצע תנועת מחסן cannot be blank.
    מצב ברירת מחדל של סוג מסמך cannot be blank.

אין לי גישה לשדות אלה

**Comment by shaulmani** [comment]
אדם, לאחר עדכון אחרון עדיין יש 2 שדות חסומים

    האם מסמך בפורמט חוזה cannot be blank.
    מצב ברירת מחדל של סוג מסמך cannot be blank.

תודה.
