### ISSUE TITLE
UX suggestion - tooltips

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#479]
Hi,
it's will be very good to add some tool-tips to the Docs pages
help to explain what to do on each page

Regards,

**Comment by aribhour** [comment]
The scope of this request is too large. We wont set tooltips for each and every single field in th application.
Please make a list of "must have tooltips" fields added with the text (English and Hebrew) that should appear with each item in the list and we will make it happen....

**Comment by aribhour** [comment]
If not responded within the next 3 days.I am going to close this issue.
The requested response must have to be met. ie. :
The scope of this request is too large. We wont set tooltips for each and every single field in the application.
Please make a list of "must have tooltips" fields added with the text (English and Hebrew) that should appear with each item in the list and we will make it happen....

**Comment by aribhour** [comment]
No response.
Closed
