### ISSUE TITLE
Bug in API /list/item

### ISSUE THREAD

**Issue by dan-omniscience** [adam2314/linet3#480]
Hi Adam,
I'm working on some improvements for shalom and I tried to list all the items from linet.
the response I'm getting is included with some invalid chars that make the json decode to fail
The Post I'm sending is:
```php
POST /api/list/item HTTP/1.1
Host: XXX.speedcomp.co.il
Connection: close
Accept-encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
User-Agent: Zend_Http_Client
Content-Length: 84
```
{"login_id":"1","login_hash":"XXXXXXXXXXXX","login_company":"1"}

The Response is:
```php
f890
{JSON DATA}
0
```

The Enter between the {JSON DATA} to the "f890" and "0" is in purpose(exactly as I receive it from the server).

I'm available for questions
Thank you,
Dan

**Comment by adam2314** [comment]
hello
please check your code i've tried against my own server and StuffStore and i was unable to produce the problem.
if you are working against a different customer please inform me in private and ill check. otherwise Linet is not sending that crap its something else.

**Comment by dan-omniscience** [comment]
I'm working against stuffstore, the test company, I'll do some more testing and if it resolve I will close the issue.

**Comment by dan-omniscience** [comment]
I am using the Zend_Rest_Clinet for all of my requests.
to get The body of linet response I'm using a function called getRawBody() it's working well for all requests and response is able to go throw the Zend_Json::decode() function except for the api/list/item action. the response I mentioned earlier is returned. to solve this issue I used Zend getBody() function instead of the getRawBody() and the included chars where removed.

For now this works for me, 

Still I'm affraid that the "f890" at the beginning and "0"  at the end are something that is returned from the linet server. 

anyway, thanks for your check,
Dan
