### ISSUE TITLE
בעייה בהתקנת לינט 3- בבקשה מי יכול לעזור

### ISSUE THREAD

**Issue by ruimydavid** [adam2314/linet3#482]
שלום,
התקנתי את לינט 3 על שרת VPS מבוסס מ. הפעלה Debian.
באשף ההתקנה אני מקבל הודעת שגיאה ברגע שאני רוצה לעבור לשלב הבא.
מצ"ב צילום מסך
נתתי הרשאות כתיבה לספריית לינט.
יש למישהו רעיון?
תודה 

![default](https://cloud.githubusercontent.com/assets/11016574/6249645/3f79c87c-b791-11e4-99ed-867e5f0e9b1b.jpg)

**Comment by adam2314** [comment]
אהלן 
עם הפרטים האלו אני יכול רק לנחש...
תראה שhtaccess
מוגדר נכון אצלך
(הכנסת את התוכנה לתוך תיקייה...)

מעבר לזה תביא לפה את התגובה שאתה מקבל מהשרת בעזרת F12
וננסה להמשיך

**Comment by ruimydavid** [comment]
תודה רבה אדם 
אני סידרתי את הבעיה באמת ה htaccess לא היה מוגדר נכון.
סיימתי את תהליך ההתקנה ויצרתי שם משתמש.
בכניסה הראשונה הוא לא נותן לי להכנס (שם משתמש או סיסמא לא נכונים)
אשמח לניחוש נוסף :)
תודה

**Comment by ruimydavid** [comment]
שגיאה 403
User is not asigned a role inside the company! Back

**Comment by adam2314** [comment]
קיבלת מסך בחירת חברה?
יצרת חברה?

אם לא תנסה לרוקן את הטבלה users
ואז תקבל את מסך יצירת המשתמש
