### ISSUE TITLE
קבצים אחידים מיובאים אינם עובדים

### ISSUE THREAD

**Issue by thqmas** [adam2314/linet3#483]
בניסיון לייבא קובץ אחיד לתכנת מבקרת המדינה, נראה כי הקובץ אינו מכיל דבר ובנוסף לכך, ללא תאריכים כפי שלינט התבקשה לייבא.

.בנוסף יצירת גיבויים לא מתבצעת באופן שוטף, לעתים כן ולעתים לא

 מצ"ב תמונת מסך של מסך היבוא של מבקרת המדינה.
![default](https://cloud.githubusercontent.com/assets/11156076/6324523/b017e04a-bb43-11e4-802c-b1bda11b692c.PNG)

**Comment by adam2314** [comment]
שלום!
אני לא הולך להתייחס לתוכנות ספצפיות.
הבדיקה היחידה עבורי שתקפה היא האם עובר סימולטור של רשות המיסים או לא
https://www.misim.gov.il/tmbakmmsml/

בקשר לגיבויים נראה לי שאתה עובד על מהודרה קצת ישנה תריץ את אשף העדכון חלו קצת שיפורים בחודש האחרון...

ואני מבקש לפתוח פוסט לכל נושא ולא לערבב להבא
בהצלחה.

**Comment by thqmas** [comment]
תודה על תגובתך המהירה.
התכנה מעודכנת לגרסה האחרונה.
![default](https://cloud.githubusercontent.com/assets/11156076/6325597/d6a5f57c-bb51-11e4-8f3c-73da2759ce4c.PNG)

**Comment by adam2314** [comment]
אוקיי לפי השגיאות הA100 והZ900
זו אותה שגיאה-זה פשוט מזהה יחודיי שצריך להתאים כנראה שזה באמת באג אני אבדוק ואטפל בהמשך
הB110
מדווח על חשבון ללא חפ\עוסק מורשה חוקי
אתה יכול לנסות לפתוח את הקובץ עם notepad
או משהו שורה 59 ולגלות איזה חשבון זה..

חוץ מזה הקובץ מחיל 311 שורות אז כנראה שהוא לא ריק:)

בקשר לגיבויי
יש לך קושי לגבות עדיין?
תתאר קצת את הבעיה.

**Comment by thqmas** [comment]
אני לוחץ על "צור גיבוי" בצידו הימני של המסך (http://127.0.0.1:85/data/backup?Backup=True), ה-browser טוען מחדש את הדף, ללא שום שינוי או קובץ להורדה.

מפתיחת הקובץ ב-notepad עולה כי כל הפקודות בעלות תאריך 01/01/1970.

**Comment by aribhour** [comment]
אימתנו את התקלה. מטפלים

**Comment by adam2314** [comment]
טוב אז הגיבויי המזהה והתאריכים טופלו  בעדכון האחרון
(3.01233)

**Comment by thqmas** [comment]
תודה על הטיפול בקבצי הגיבוי. אך נותרה עדיין הבעיה של יבוא הקבצים האחידים. לא שונו כל התאריכים, כך נראה לי בקובץ BKMVDATA.

ראה קובץ שהופק מתוכנת הנה"ח לא לינט:
![default](https://cloud.githubusercontent.com/assets/11156076/6387459/2b963328-bd94-11e4-90d9-e6373e9c33cb.PNG)

וראה את הקובץ של לינט (שים לב לסימון הצהוב):
![default](https://cloud.githubusercontent.com/assets/11156076/6387473/48b6b072-bd94-11e4-8375-0079cea80bfb.PNG)
