### ISSUE TITLE
בעית עדכון

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#484]
<p>התקנתי את התוכנה (WIN XP) וזה השגיאות שהוא כותב לי</p>
<p>אשמח לדעת מה הבעיה?</p>
<p>&nbsp;</p>
<p>תודה</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>Operation timed out after 29984 milliseconds with 10158080 out of 13816415 bytes received (C:\Program Files\linet\apache\htdocs\protected\extensions\curl\Curl.php:48)</p>
<pre>#0 C:\Program Files\linet\apache\htdocs\protected\extensions\curl\Curl.php(63): Curl-&gt;exec('https://update3...')
#1 C:\Program Files\linet\apache\htdocs\protected\models\Update.php(52): Curl-&gt;post('https://update3...', '[]')
#2 C:\Program Files\linet\apache\htdocs\protected\models\Update.php(105): Update-&gt;_file('update/file/161')
#3 C:\Program Files\linet\apache\htdocs\protected\controllers\NewUpdateController.php(51): Update-&gt;upgrade(Array)
#4 C:\Program Files\linet\yii\web\actions\CInlineAction.php(49): NewUpdateController-&gt;actionUpdate()
#5 C:\Program Files\linet\yii\web\CController.php(308): CInlineAction-&gt;runWithParams(Array)
#6 C:\Program Files\linet\yii\web\filters\CFilterChain.php(133): CController-&gt;runAction(Object(CInlineAction))
#7 C:\Program Files\linet\yii\web\filters\CFilter.php(40): CFilterChain-&gt;run()
#8 C:\Program Files\linet\apache\htdocs\protected\modules\rights\components\RController.php(36): CFilter-&gt;filter(Object(CFilterChain))
#9 C:\Program Files\linet\yii\web\filters\CInlineFilter.php(58): RController-&gt;filterRights(Object(CFilterChain))
#10 C:\Program Files\linet\yii\web\filters\CFilterChain.php(130): CInlineFilter-&gt;filter(Object(CFilterChain))
#11 C:\Program Files\linet\yii\web\CController.php(291): CFilterChain-&gt;run()
#12 C:\Program Files\linet\yii\web\CController.php(265): CController-&gt;runActionWithFilters(Object(CInlineAction), Array)
#13 C:\Program Files\linet\yii\web\CWebApplication.php(282): CController-&gt;run('update')
#14 C:\Program Files\linet\yii\web\CWebApplication.php(141): CWebApplication-&gt;runController('newUpdate/updat...')
#15 C:\Program Files\linet\yii\base\CApplication.php(180): CWebApplication-&gt;processRequest()
#16 C:\Program Files\linet\apache\htdocs\index.php(23): CApplication-&gt;run()
#17 {main}</pre>

**Comment by aribhour** [comment]
החיבור שלך לאינטרנט הוא מאוד איטי ולכן דף האינטרנט מדווח שלאחר 30 שניות של משיכת העדכון הוא "מרים ידיים" ומוותר על הניסיון
שפר את החיבור לאינטרנט אצלך
