### ISSUE TITLE
בעית עדכון

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#485]
<p>התקנתי את התוכנה (WIN XP) וזה שגיאות שהוא כותב לי</p>
<p>ישמח לדעת מה בעיה?</p>
<p>&nbsp;</p>
<p>תודה</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>מבצע שהוקצב לאחר 29,984 אלפיות שנייה עם 10,158,080 מתוך 13,816,415 בתים שהתקבל (C: \ Program Files \ לינט \ אפצ'י \ htdocs \ מוגן \ הרחבות \ תלתל \ Curl.php: 48)</p>
<pre># 0 C: \ Program Files \ לינט \ אפצ'י \ htdocs \ מוגן \ הרחבות \ תלתל \ Curl.php (63): Curl-&gt; exec ('https: // update3 ... ")
C # 1: \ Program Files \ לינט \ אפצ'י \ htdocs \ מוגן \ דגמים \ update.php (52): Curl-&gt; פוסט ('https: // update3 ...', '[]')
# 2 C: \ Program Files \ לינט \ אפצ'י \ htdocs \ המוגן \ דגמים \ update.php (105): עדכון -&gt; _ קובץ ("עדכון / קובץ / 161 ')
# 3 C: \ Program Files \ לינט \ אפצ'י \ htdocs \ מוגן \ הבקרים \ NewUpdateController.php (51): Update-&gt; שדרוג (Array)
# 4 C: \ Program Files \ לינט \ web \ Yii \ פעולות \ CInlineAction.php (49): NewUpdateController-&gt; actionUpdate ()
# 5 C: \ Program Files \ לינט \ CController.php \ Yii \ האינטרנט (308): CInlineAction-&gt; runWithParams (Array)
# 6 C: \ Program Files \ לינט \ מסנני \ web \ Yii \ CFilterChain.php (133): CController-&gt; runAction (Object (CInlineAction))
# 7 C: \ Program Files \ לינט \ מסנני \ web \ Yii \ CFilter.php (40): CFilterChain-&gt; הפעלה ()
# 8 C: \ Program Files \ לינט \ אפצ'י \ htdocs \ המוגן \ מודולים \ זכויות \ רכיבים \ RController.php (36): CFilter-&gt; מסנן (Object (CFilterChain))
# 9 C: \ Program Files \ לינט \ מסנני \ web \ Yii \ CInlineFilter.php (58): RController-&gt; filterRights (Object (CFilterChain))
# 10 C: \ Program Files \ לינט \ מסנני \ web \ Yii \ CFilterChain.php (130): CInlineFilter-&gt; מסנן (Object (CFilterChain))
# 11 C: \ Program Files \ לינט \ CController.php \ web \ Yii (291): CFilterChain-&gt; הפעלה ()
# 12 C: \ Program Files \ לינט \ CController.php \ Yii \ האינטרנט (265): CController-&gt; runActionWithFilters (Object (CInlineAction), Array)
# 13 C: \ Program Files \ לינט \ web \ Yii \ CWebApplication.php (282): ריצת CController-&gt; ("עדכון")
# 14 C: \ Program Files \ לינט \ web \ Yii \ CWebApplication.php (141): CWebApplication-&gt; runController ('newUpdate / updat ... ")
# 15 C: \ Program Files \ לינט \ בסיס \ Yii \ CApplication.php (180): CWebApplication-&gt; processRequest ()
# 16 C: \ Program Files \ לינט \ אפצ'י \ htdocs \ index.php (23): CApplication-&gt; הפעלה ()
# 17 {} ראשי</pre>

**Comment by aribhour** [comment]
Duplicate with #484
