### ISSUE TITLE
שחזור מקובץ גיבוי אינו עובד

### ISSUE THREAD

**Issue by thqmas** [adam2314/linet3#487]
ניסיון שחזור מקובץ גיבוי נותן את האזהרות הבאות:

![1](https://cloud.githubusercontent.com/assets/11156076/6392598/f55aad8e-bdca-11e4-9d4c-dc68c5a6fd40.PNG)
![2](https://cloud.githubusercontent.com/assets/11156076/6392602/f90fd684-bdca-11e4-8eb7-ea7d1000c733.PNG)
![3](https://cloud.githubusercontent.com/assets/11156076/6392603/fb6148fa-bdca-11e4-8a88-58c6cdf52d8d.PNG)

**Comment by adam2314** [comment]
מישהו יכול לאמת או להפריך?

**Comment by starnetwork** [comment]
אדם, בגרסת האירוח, זה משהו שאפשר לבדוק באמצעות בית עסק ספציפי מבלי לפגוע בכל המע'?
אם כן, תגיד לי ואני אפתח בית עסק ואבדוק את זה...

**Comment by adam2314** [comment]
אם זה יפגע בכל המערכת אז עוד יותר חשוב לבדוק את זה עכשיו:)
לא אמורה להיות בעיה.

**Comment by aribhour** [comment]
תגובות? בדיקות?

**Comment by danreznik** [comment]
יש לי את אותה הבעיה

**Comment by shaulmani** [comment]
אצלי לא קורה כלום אין הודעת שגיאה ואין שחזור

**Comment by aribhour** [comment]
מאשר שלא תקין

**Comment by adam2314** [comment]
done.
