### ISSUE TITLE
It is Possible to create 0 sum receipt.

### ISSUE THREAD

**Issue by aribhour** [adam2314/linet3#488]
Please add a validator to total sum of receipt as follows:
If total sum = 0 (negative as well as positive value chars are accepted), the system shouldn't create receipt and shouldn't create transactions and should display an error message as following:
Creating zero sum receipt is not acceptable. Please enter positive or negative value sum.

**Comment by shaulmani** [comment]
לא מדוייק.
חזר שיק ושילמו במזומן.
מוציאים קבלה בסכום אפס השיק שחזר במינוס המזומן בפלוס.
אחרת צריך 2 מיסמכים

**Comment by aribhour** [comment]
O.K. Shaul
I accept your remark and closing this issue.
Leaving current behavior as is.
