### ISSUE TITLE
האם ניתן להתקין את לינט 3 על מחשב בענן, מבחינת אבטחת מידע?

### ISSUE THREAD

**Issue by sapird** [adam2314/linet3#490]
שלום,
בגירסת לינט 2 היתה אזהרת אבטחה לא להתקין אותה בענן.
האם אבטחת התוכנה תוקנה?
האם בטוח להתקין אותה על שרת אינטרנט, ולחבר לה דומיין?
תודה,
דוד.

**Comment by aribhour** [comment]
שלום דוד
אבטחת מידע היה אחד המניעים העיקריים לכתוב את קוד התוכנה לגמרי מחדש בלינט 3 והבעיה של פרצות האבטחה אכן נפתרה בגרסה 3
בטוח לחבר אותה לשרת בענן ויותר מזה: יש כבר חברות לאירוח אתרים שמפעילות לינט בתשלום ומארחים משתמשים על גבי שרתי האינטרנט שלהם
