### ISSUE TITLE
בחירת סוג עסק לקבלת סוגי מסמכים מותאמים

### ISSUE THREAD

**Issue by rafush** [adam2314/linet3#492]
שלום רב.
ראשית אני רוצה להודות לכם על עבודה נפלאה !
אני חושב שצריך שתהיה אפשרות לבחירת סוג עסק (חברה בע"מ. עמותה. עוסק פטור . חל"צ. וכדומה) ובבחירה כזו יתקבלו כברירת מחדל סוגי מסמכים המתאימים לסוג העסק.
בנוסף יהיה נחמד מאד אם תהיה אפשרות לערוך להצגה מותאמת אישית את הלשוניות שבראש העמוד כך שדברים שאינם רלוונטים לעסק ספציפי לא יהיו שם. 

תודה

**Comment by aribhour** [comment]
שלום
תודה על המילים החמות
ראשית אין הבדל בין חברה בע"מ/עמותה/עוסק מורשה וכן הלאה בסוגי המסמכים ובפונקציות שנדרשות מתוכנת הנה"ח
לעומת זאת, כן יש הבדל בין עסקים שמנהלים/נדרשים לנהל הנה"ח חד צידית או דו צידית ובחירת חשבונאות דו וחד צידית היא בהחלט אפשרית בלינט וגורמת להעלמת תפריט ההתאמות כולו במידה ובוחרים בחד צידית.
מלבד זאת יש ממשק נסתר מעיני המשתמש לניהול התפריט העליון המאפשר הצגה/הסתרה של פריטים בתפריט ושינוי מספר הפריטים ומאפשר לשלוט בסדר הפנימי של התפריט העליון. מטרת ההסתרה היא מניעת שוני רב מידי בין המשתמשים על מנת להקל על התמיכה
אנא פנה אלינו בערוץ הטלפוני שבתשלום או חפש מתכנת שיתאים לך את התפריט כרצונך

**Comment by rafush** [comment]
יש הבדל אחד.
עמותה צריכה 2 סוגי קבלות. אחת רגילה והשניה קבלה עבור תרומה.
וכן עמותה לא צריכה חשבוניות 
(לפחות לפי הידוע לי)
