### ISSUE TITLE
תאריך במסמכים

### ISSUE THREAD

**Issue by rafush** [adam2314/linet3#493]
בעת הפקת קבלה ויתכן בשאר המסמכים מופיע תאריך הפקת מסמך שאי אפשר לשנות ויש תאריך ערך. אבל בהדפסה מופיע תאריך תוקף 01/01/1970
איך משנים או מבטלים את תאריך התוקף?
איך אפשר לשנות תאריך הפקת המסמך או לחילופין שיופיע במסמך המודפס רק תאריך הערך

**Comment by aribhour** [comment]
אי אפשר לשנות תאריך הפקת מסמך כי זה לא חוקי. לעומת זאת כן ניתן לשנות תאריך ערך (תאריך רישום) ברישום הוצאות על מנת למקם נכון הוצאה לתקופת דיווח מס נכונה
התופעה של תאריך לא נכון מופיעה בדרך כלל במסמכים מיובאים בתנאים מסוימים.

**Comment by rafush** [comment]
אוקיי תודה
ואיך מבטלים את תאריך התוקף? או לחילופין שיהיה תאריך הגיוני ולא משנת 1970 
מדובר במסמכים שאני מפיק בתוכנה ולא ייבוא
