### ISSUE TITLE
הודעת שגיאה ביבוא דפי בנק

### ISSUE THREAD

**Issue by rafush** [adam2314/linet3#494]
CException

Bankbook and its behaviors do not have a method or closure named "searchBankbook".

C:\Program Files (x86)\linet\yii\base\CComponent.php(266)

254     public function __call($name,$parameters)
255     {
256         if($this->_m!==null)
257         {
258             foreach($this->_m as $object)
259             {
260                 if($object->getEnabled() && method_exists($object,$name))
261                     return call_user_func_array(array($object,$name),$parameters);
262             }
263         }
264         if(class_exists('Closure', false) && $this->canGetProperty($name) && $this->$name instanceof Closure)
265             return call_user_func_array($this->$name, $parameters);
266         throw new CException(Yii::t('yii','{class} and its behaviors do not have a method or closure named "{name}".',
267             array('{class}'=>get_class($this), '{name}'=>$name)));
268     }
269 
270     /**
271      * Returns the named behavior object.
272      * The name 'asa' stands for 'as a'.
273      * @param string $behavior the behavior name
274      * @return IBehavior the behavior object, or null if the behavior does not exist
275      */
276     public function asa($behavior)
277     {
278         return isset($this->_m[$behavior]) ? $this->_m[$behavior] : null;

Stack Trace
#0 	
+
 C:\Program Files (x86)\linet\yii\db\ar\CActiveRecord.php(227): CComponent->__call("searchBankbook", array())
#1 	
–
 C:\Program Files (x86)\linet\apache\htdocs\protected\models\Bankbook.php(249): CActiveRecord->__call("searchBankbook", array())

244             $value = (ltrim(substr($line, 33, 12), '0 ')) * $sighn;
245             $bank->sum = $value; //$zachot-$hova;
246 
247             $sighn = substr($line, 46, 1) . '1';
248             $bank->total = (ltrim(substr($line, 47, 12), '0 ')) * $sighn;
249             if (!$bank->searchBankbook()) {
250                 //mybe save output? num
251                 $bank->extCorrelation = 0;
252                 return $bank->save();
253             }
254         }

#2 	
–
 C:\Program Files (x86)\linet\apache\htdocs\protected\models\Bankbook.php(249): Bankbook->searchBankbook()

244             $value = (ltrim(substr($line, 33, 12), '0 ')) * $sighn;
245             $bank->sum = $value; //$zachot-$hova;
246 
247             $sighn = substr($line, 46, 1) . '1';
248             $bank->total = (ltrim(substr($line, 47, 12), '0 ')) * $sighn;
249             if (!$bank->searchBankbook()) {
250                 //mybe save output? num
251                 $bank->extCorrelation = 0;
252                 return $bank->save();
253             }
254         }

#3 	
–
 C:\Program Files (x86)\linet\apache\htdocs\protected\models\Bankbook.php(174): Bankbook->readlineLeumi()

169                         break;
170                     case 'HashWin':
171                         $this->readlineHashWin($line, $account);
172                         break;
173                     case 'leumi':
174                         $this->readlineLeumi($line, $account);
175                         break;
176                 } else {
177                 throw new CHttpException(500, Yii('app', 'bankbook Import Unkown file format'));
178             }
179         }//while end

#4 	
+
 C:\Program Files (x86)\linet\apache\htdocs\protected\models\Bankbook.php(145): Bankbook->readFile(resource, 116)
#5 	
+
 C:\Program Files (x86)\linet\apache\htdocs\protected\controllers\BankbookController.php(87): Bankbook->import(116)
#6 	
 unknown(0): BankbookController->actionAdmin(null)
#7 	
+
 C:\Program Files (x86)\linet\yii\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(BankbookController, array(null))
#8 	
+
 C:\Program Files (x86)\linet\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(BankbookController, ReflectionMethod, array())
#9 	
+
 C:\Program Files (x86)\linet\yii\web\CController.php(308): CInlineAction->runWithParams(array())
#10 	
+
 C:\Program Files (x86)\linet\yii\web\filters\CFilterChain.php(133): CController->runAction(CInlineAction)
#11 	
+
 C:\Program Files (x86)\linet\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 	
+
 C:\Program Files (x86)\linet\apache\htdocs\protected\modules\rights\components\RController.php(36): CFilter->filter(CFilterChain)
#13 	
+
 C:\Program Files (x86)\linet\yii\web\filters\CInlineFilter.php(58): RController->filterRights(CFilterChain)
#14 	
+
 C:\Program Files (x86)\linet\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(CFilterChain)
#15 	
+
 C:\Program Files (x86)\linet\yii\web\CController.php(291): CFilterChain->run()
#16 	
+
 C:\Program Files (x86)\linet\yii\web\CController.php(265): CController->runActionWithFilters(CInlineAction, array("rights"))
#17 	
+
 C:\Program Files (x86)\linet\yii\web\CWebApplication.php(282): CController->run("admin")
#18 	
+
 C:\Program Files (x86)\linet\yii\web\CWebApplication.php(141): CWebApplication->runController("bankbook/admin")
#19 	
+
 C:\Program Files (x86)\linet\yii\base\CApplication.php(180): CWebApplication->processRequest()
#20 	
+
 C:\Program Files (x86)\linet\apache\htdocs\index.php(23): CApplication->run()
2015-03-12 17:03:22 Apache Yii Framework/1.1.14

**Comment by aribhour** [comment]
Good catch. will fix soon.

**Comment by aribhour** [comment]
Fixed with 3.1 version/
Make sure you are importing Hashavshevet file format from the site of the bank account.
