### ISSUE TITLE
סוגי מסמכים לעמותה

### ISSUE THREAD

**Issue by rafush** [adam2314/linet3#496]
עמותה צריכה מסמך קבלה על תרומה - בהכנסות.
וכן בזיכויים צריך קבלה על תרומה החזר.  וקבלה להחזר.

**Comment by aribhour** [comment]
לגבי קבלה על תרומה: אנו ניצור סוג מסמך שכזה בגרסה 3.1 שתופץ לציבור בחודש הקרוב דרך האתר ודרך עדכון התוכנה למי שכבר התקין אותה
לגבי החזר קבלה רגילה והחזר קבלה על תרומה: אין ולא יהיה מסמך מיוחד לכך.  אם צריך להחזיר כסף ללקוח/תורם יש להפיק קבלה /קבלה על תרומה בסכום שלילי. זה יעשה את העבודה
כך גם נהוג בתוכנות אחרות
