### ISSUE TITLE
can't change mysql settings at installation

### ISSUE THREAD

**Issue by herzaso** [adam2314/linet3#499]
Installation process fails if the settings are different than the default settings (root/linet)

**Comment by adam2314** [comment]
hello,
the install wizard is used to setup the config file only. it will NEVER have the power to set Mysql password. you can always set Mysql users & passwords manually.

**Comment by herzaso** [comment]
I'm cool with that, but if that's the case then you shouldn't give users the ability to change those settings...

**Comment by adam2314** [comment]
yes we should for installations not using the installer.
