### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by herzaso** [adam2314/linet3#500]
after installing linet 3 on windows with default settings, I defined a user and the system moved to the login page.
At this stage, when I insert the correct credentials, nothing happens (login fields are cleared).
When I insert wrong credentials, I see "Incorrect username or password" below the fields (UX suggestion - change the color of the error - it's currently gray on gray)

**Comment by adam2314** [comment]
you can try to remove the user, which will trigger the user creation page(if you have the Mysql knowledge).
or you can just remove Linet and then reinstall it.
the UX suggestion is a good idea.

**Comment by herzaso** [comment]
Removing the user and creating it again did not solve the problem.

In the uninstall process, services are not removed/stopped, and files are not removed (installer doesn't work if httpd process is still running)

During installation, an exception is raised "Caught exception: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" but this time login does work, thanks.

**Comment by adam2314** [comment]
when you run the Uninstaller use the run as Admin...
or else it wont have the necessary permissions to stop the services and remove files from Program Files folder.

**Comment by aribhour** [comment]
You are kindly advised to pay attention to installation instructions here: http://www.linet.org.il/support/installation-manuals/for-windows/3-0

**Comment by herzaso** [comment]
I did read and follow the instructions.
The application is now running ok (as far as I can tell), although there was an exception in the signup wizard (after approving the mysql details)
