### ISSUE TITLE
תפריטים אינם עובדים כראוי לאחר הרצת עדכון

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#501]
הרצתי את העדכון האחרון (1234 אם אני לא טועה) ולאחר העדכון בתפריט העליון חסרה אפשרות "הגדרות" (תפריט מתחיל מ"כללי" ומסתיים ב"מלאי").
במעבר עכבר על גבי "כללי" נראה כי מופיעים מספר תפריטים אחד על גבי השני

**Comment by adam2314** [comment]
כשאתה בתוכנה תלחץ על
F5
מבטיח לך שזה יפתור את הבעיה.
