### ISSUE TITLE
הדפסת חשבונית מס קבלה סכומים משמאל יוצאים משולי הדף

### ISSUE THREAD

**Issue by etalbi** [adam2314/linet3#502]
שלום,
כאשר אני מדפיס חשבונית מס קבלה הסכומים שמופיעים בשמאל הדף נחתכים 

![screenshot007](https://cloud.githubusercontent.com/assets/11733025/6914220/fcae7342-d790-11e4-82e9-4fc4b3a80f80.jpg)

דפדפן: CHROM
האופציות שאני בוחר בהדפסה הן:

גודל דף: A4
שוליים: מינימום או ברירת מחדל לא משנה מה אני בוחר זה יוצא אותו דבר

הצלחתי להדפיס הכל רק כאשר אני בוחר גודל דף: Envelop B5

![screenshot006](https://cloud.githubusercontent.com/assets/11733025/6914208/ead0300c-d790-11e4-90b5-ee3f98a2450c.jpg)

**Comment by aribhour** [comment]
שלום לך
ניסינו לחולל את הבעיה שאתה מצביע עליה בסביבת עבודה כמה שיותר דומה לשלך. דפדפן כרום וכדומה וההדפסה יוצאת תקינה.
נסה אולי עם מדפסת אחרת שמותקנת במחשב שלך, למשל תתקין מדפסת 
PDF 
ותראה אם זה קורה גם שם

**Comment by aribhour** [comment]
סוגר את הנושא עקב מרחק הזמן שחלף
אם עדיין לא הסתדרה הבעיה פתח בבקשה את הנושא שוב
