### ISSUE TITLE
כששולחים מסמך פי.די.אף צריך שיופיע אישור על המסמך שיש חתימה דיגיטלית - ואין

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#503]
חג שמח לכולם

**Comment by aribhour** [comment]
חג שמח
על פי חוק כל מה שצריך שיופיע על גבי מסמך ממוחשב חוקי זה הטקסט"מסמך ממוחשב". נכון שתוכנות מסוימות מוסיפות מן "חותמת" שמודיעה שהמסמך חתום דיגיטאלית, שזה טוב אולי בשביל אנשים שיסכימו לקבל מסמך ממוחשב
אבל!!!הרבה אנשים לא יודעים אתה צריך לקבל הסכמה מראש מהמכותב למשלוח מסמך ממוחשב אז זה מייתר את כל הקישוט הזה

**Comment by shaulmani** [comment]
זה בדיוק מה שחסר אצלי מה שכתבת
אנסה לשלוח לך בהמשך דוגמת חשבונית
בתאריך 2 באפר' 2015 10:22,‏ "aribhour" <notifications@github.com> כתב:

**Comment by shaulmani** [comment]
יש לי הסכמה ואין כיתוב.  זה תקין?
 בתאריך 2 באפר' 2015 10:21,‏ "aribhour" <notifications@github.com> כתב:

**Comment by shaulmani** [comment]
הבנתי אותך תתעלם

**Comment by aribhour** [comment]
כרגע יש עותק של אצלך על המחשב שלך בלבד.
בשעה 23:00 כל יום (החל מהיום) התוכנה של בזק אמורה להעתיק את החומר מהמחשב שלך לשרת שלהם בענן.

בברכה
ארי בן חור
[mms]
גבעת גאולה 1 רמת גן 52215
נייד:    0524780789
טלפון: 0772105001
פקס:   0775611355
http://www.speedcomp.co.il<http://www.speedcomp.co.il/>
