### ISSUE TITLE
למה אני לא מצליח לפתוח חשבון ?

### ISSUE THREAD

**Issue by Gilad123** [adam2314/linet3#507]
אני עושה את כול שלבי ההרשמה במדריך ההתקנה אבל שאני לוחץ על תוכנה נפתח לי הדפדפן והוא מבקש ממני להזין לו שם משתמש וסיסמה אבל שום שם משתמש וסיסמה לא מכניסים אותי למערכת 

עזרה בבקשה ?

**Comment by aribhour** [comment]
לא ברור מה הבעיה? אתה לא מצליח להיכנס לאתר לאחר הרשמה על מנת להוריד את התוכנה או שאתה לא מצליח להיכנס לתוכנה אחרי שהורדת והתקנת אותה?
