### ISSUE TITLE
שיחזור סיסמה

### ISSUE THREAD

**Issue by carlito5** [adam2314/linet3#510]
שלום לכולם
ניראה כי לאחר התקנת התכנה, בכניסה הראשונה בה כתבתי שם משתמש וסיסמה, עשיתי טעות בכתיבת הסיסמה, וכיוון שאין צורך לחזור עליה, הטעות נשארה. כעת איני יכול להיכנס, כיוון שאיני יודע מהי הסיסמה. האם יש דרך לגלות מהי, או לאפס אותה?  
תודה מראש

**Comment by adam2314** [comment]
רק להתקין מחדש
