### ISSUE TITLE
העימוד של הדפים השתבש

### ISSUE THREAD

**Issue by Tal-v** [adam2314/linet3#511]
כפתורים לא ממוקמים היכן שצריך, לחצנים עולים על שדות..
משהו יודע מה גורם לזה?

עשיתי התקנה חדשה על חלונות 8.1
שדרגתי מנתונים של לינט 2 וזה עבד בצורה טובה

חוצמיזה, לא ראיתי בקצת הזמן שביליתי עם התוכנה, איפה משנים את אחוז המע"מ

**Comment by adam2314** [comment]
אתה יכול להרחיב?
למה אתה קורא דף?
אפשריות בתפריט מסמכים בPDF ?

**Comment by Tal-v** [comment]
אני מקווה שעשיתי צילום מסך, מה שכן, עשיתי עדכון של משהו בפיירפוקס, נדמה לי פלש, ופתאום הכל הסתדר

**Comment by adam2314** [comment]
יכול להיות שהיה לך CSS לא מעודכן במסמך אחד?
על איזו גירסה אתה?
נראה לך שאפשר לסגור את הבאג הזה(קורה עכשיו או שתקין)

**Comment by Tal-v** [comment]
כרגע זה בסדר,
אני שמח שיש פעילות בפורום בנוגע לתוכנה.
אם צריך עזרה במשהו, יש לי עכשיו קצת זמן

בכל מקרה אני אנסה לראות אם שמרתי תמונת מסך מאז
