### ISSUE TITLE
משהו הצליח להתקין את התוכנה בלינוקס?

### ISSUE THREAD

**Issue by Tal-v** [adam2314/linet3#512]
אחרי שהיו לי בעיות תצוגה בחולונות
ניסיתי להתקין את לינט בלינוקס
הורדתי את הגרסה האחרונה של yii:
Yii 1.1.16
שמתי אותם בספריית protected
בכניסה לכתובת אני מקבל:
Warning: require_once(/var/www/protected/config/../../../yii/framework/yii.php): failed to open stream: No such file or directory in /var/www/index.php on line 13

Fatal error: require_once(): Failed opening required '/var/www/protected/config/../../../yii/framework/yii.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/index.php on line 13

אני אנסה שוב מאוחר יותר
בכל מקרה לא מצליח להתקין את האפליקציה בשום צורה,

**Comment by chaimvaid** [comment]
אני נתקלתי באותה בעיה נראה שהנתיב בקובץ
 /protected/config/yii.php
שמיובא לקובץ האינדקס
 לא נכון הוא מסמן לדעתי לשתי תקיות מתחת 
והנה השורה :
$yii=dirname(__FILE__).'/../../../yii/framework/yii.php';
בכל אופן גם אם משנים את זה א"א להתקין נראה כאילו חסרה תיקיה בשם
 install 
בתקיית הקבצים אשמח מאוד לעזרה בענין

**Comment by Tal-v** [comment]
אני אנסה לשבת על זה השבת.
לא ברור איזה גרסה של
yii
מותקנת אצלם,  הורדתי את 1.1.16

אגב, להתקין בחלונות הצלחת ?
אצלי חסרים איקונים ונראה שמשהו בעימוד של המסך השתבש ולא נראה כמו זה שיש אצלם בגרסת הנסיון באתר

**Comment by eitriv** [comment]
בדיוק אותה בעיה אצלי האם נמצא פתרון?

**Comment by eitriv** [comment]
שימו לב שהקובץ
.htaccess
גם נמצא בזיפ של לינט אבל בגלל שהוא נסתר אולי לא הועתק לתיקית הרוט, יש לודא שהוא במקום ולבצע
$ sudo a2enmod rewrite
כדי לאפשר את השימוש בו. גם צריך לעדכן את:
/etc/apache2/sites-available/000-default.conf
כך
 <Directory /var/www/html>
                AllowOverride All
 </Directory>

**Comment by Tal-v** [comment]
יום שלישי שבוע הבא אני מסיים משהו ויהיה לי זמן לנסות שוב את ההתקנה.

אגב, העניין בחלונות הסתדר ( התצוגה הייתה מבולגנת לי, דברים לא ישבו איפה שצריך) זה נפתר אחרי שעדכנתי משהו בפיירפוקס, כלומר נדמה לי שזו הייתה הבעיה, בכל מקרה, זה הסתדר, עכשיו צריך רק לבדוק שאין יותר מדי באגים

אגב, משהו נתקל בבעיות מהותיות?

**Comment by eitriv** [comment]
הצלחתי להתקין בלינוקס, זה פחות נוח מרווחית שאני משתמש כעת אבל חשוב לי שזה עובד בלינוקס ואוכל להיפטר מוינדוס.
שמתי לב שהוא מאד ממהר בלהוציא מסמכים למשל אפשר להפיק חשבונית שלא מולאה לגמרי ואין התראה
צריך לתרגל עבודה עם זה, מתכנן לעבור ללינט בתחילת שנה הבאה.

**Comment by Tal-v** [comment]
צריך לדווח על זה כבאג .. בהנחה שעדיין יש פיתוח

**Comment by adam2314** [comment]
אז נראה לי שהצלחתם להתקין בלינוקס
;))
