### ISSUE TITLE
אני לא מצליח להירשם לאתר ע"מ להוריד את התוכנה

### ISSUE THREAD

**Issue by danreznik** [adam2314/linet3#513]
שלום רב,

אני מעוניין להוריד את התוכנה אך אני לא מצליח להירשם (לא מוצא את הקישור להרשמה)

תודה לעוזרים.
דן

**Comment by tomer2** [comment]
גם אני

**Comment by tomer2** [comment]
נסגר אך הבעיה נותרה,אשמח למשוב

**Comment by danreznik** [comment]
איזה בעיה? של הספאם או אנשים שלא יכולים להירשם?

**Comment by tomer2** [comment]
בעיה שלא מצליח להירשם.
בתאריך 19 ביוני 2015 7:57 לפנה״צ,‏ "danreznik" <notifications@github.com>
כתב:

**Comment by aribhour** [comment]
אין בעיית הרשמה כרגע באתר
שלח לי את שם המשתמש/כתובת המייל שאיתה נרשמת ואנסה לעזור לך

**Comment by tomer2** [comment]
הי,
תודה על התמיכה.
שם המשתמש : bubux
דואל: bubux@inter.net.il
שוב תודה,
תומר

Best Regards,
Tomer Gritzman, CPA (Isr)
+972-54-535-0007

הודעת דואר אלקטרוני זו וכל המסמכים ו/או הקבצים המצורפים אליה מיועדים לנמעני
ההודעה בלבד, וכוללים מידע פרטי וחסוי. אם קיבלת הודעה זו ואינך הנמען/נת
המיועד/ת, הנך מתבקש/ת להימנע מקריאת תוכן ההודעה, גילויו, העתקתו, הפצתו בכל
דרך שהיא או נקיטת כל פעולה על בסיס ההודעה, ולהודיע לנו מיידית, בדואר
אלקטרוני חוזר על כך שההודעה הגיעה לידיך בטעות. תודה.

בתאריך 21 ביוני 2015 בשעה 9:20, מאת aribhour <notifications@github.com>:
