### ISSUE TITLE
לא מצליח להתקין

### ISSUE THREAD

**Issue by 220gal220** [adam2314/linet3#515]
אני הורדתי את התוכנה התקנתי ואז אני לוחץ זה פותח דף בדפדפן ולא מופיע כלום...

**Comment by Q1W2E** [comment]
יש לי אותה בעיה מישהוא יכול לעזור?

**Comment by adam2314** [comment]
עיינתם פה?
http://www.linet.org.il/support/installation-manuals/for-windows/3-0
