### ISSUE TITLE
חתימה דיגיטלית

### ISSUE THREAD

**Issue by hershkoy** [adam2314/linet3#516]
שלום. אני חדש כאן. 
ניסיתי לחפש תשובה האם לינט 3.0 תומכת בחתימה דיגיטלית כדי לשלוח את החשבוניות במייל לפי הוראת החוק, אבל לא הצלחתי למצוא. 
מישהו יודע כאן את התשובה לזה?

**Comment by adam2314** [comment]
שלום, תבדוק פה:
http://www.linet.org.il/
