### ISSUE TITLE
גיבויים

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#517]
<p>לא ניתן לגבות,</p>
<p>במסך מופיעים 2 שדות אין שום כפתור לביצוע גיבוי</p>

**Comment by adam2314** [comment]
בצד ימין
 "צור גיבוי"
יכול להיות שאת\ה עובד\ת על רזולציה גרועה 
ואז צריך ללחוץ על הירוק בכדי להציג את הפנאל הצדדי
