### ISSUE TITLE
Empty company image

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#521]
if company logo is not inserted, it should not show empty image in sidebar
if company logo is mandatory, it should not allow to create / update company without upload logo
image: http://images-uploader.com/image/s

**Comment by aribhour** [comment]
Company Logo is not mandatory. The issue is fixed and now if there is no company logo inserted the first 2 letters of company name appear.

**Comment by starnetwork** [comment]
Hi,
just did new installation from updated git, now
please see: http://www.awesomescreenshot.com/image/583143/1ff791ff8d6562c9c5b474d65006ec6b

**Comment by aribhour** [comment]
Look at hosted Linet at speedcomp.co.il. The issue is solved there. If there is a mismatch with git files and updates talk directly to Adam to solve flawless direct updates on private channels because of well known current issues.
