### ISSUE TITLE
Send email error

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#522]
Hi,
I created client without email address -> created Preforma Invoice -> select Email and I got popup to insert the email address to get this invoice
after I added the details, I got the next error
the URL: http://lineturl.tld/mail/create
Swift_RfcComplianceException
Address in mailbox given [] does not comply with RFC 2822, 3.6.2.
in /var/www/linet3/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php

and the email is correct...

**Comment by adam2314** [comment]
have you tried to enter email? in the "company details" page the error is for the email from field.
