### ISSUE TITLE
Create Tax invoice flow is incorrect

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#523]
Hi try to create invoice receipt and I added the client info -> the product -> the payment
I clicked on PDF, and I got the PDF file
I still I stayed in the same screen of the Document "creation" page
I clicked again on PDF, and I got this screenshot:
http://postimg.org/image/6y2mlbnh5

**Comment by aribhour** [comment]
Confirmed as wrong behavior, it can confuse the average user and make him create duplicate documents. After creating a document the display should automatically jump to the document view display.

**Comment by aribhour** [comment]
duplicate with 
 #410
