### ISSUE TITLE
Print Invoice not working

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#524]
Hi try to create invoice receipt and I added the client info -> the product -> the payment
I clicked on PDF, and I got the PDF file
I still I stayed in the same screen of the Document "creation" page
I clicked again on "הדפסה", and I got this screenshot:
http://postimg.org/image/6y2mlbnh5

* BTW, the "הדפסה" button didn't Appeared at the first time but only after I created the PDF
it's 2 different page templates?

**Comment by aribhour** [comment]
This is one of the 3 contributions of Yossi to the temlate design. Print button dissapeared after he messed with it...
Adam please fix it asap. It is draging out too long.

**Comment by aribhour** [comment]
Fixed
