### ISSUE TITLE
Create Company method looks wrong

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#525]
Hi,
when I click on "Create Company"
link: http://lineturl.tld/index.php/company/create
it's already create the company with empty settings, and I belive that this is why if someone go to one of the menu items (general / documents / items / etc..), he have company with empty required field, like Company name & Company VAT Number and it's make bugs and problems

this method should be that company created only after the required values are set on this screen and the manager clicked on "Save" to save the company details

**Comment by aribhour** [comment]
This Issue fixing scope is too broad for putting up a solution for now.
The fix would alter a lot of code which will destabilise the whole DB structure.

**Comment by starnetwork** [comment]
Hi,
it's not so small issue, can you please re-check / consider it, or want to talk about Idea for temporary solution?

**Comment by aribhour** [comment]
Simple explanation to the user about creating new company should be enough to prevent misuse.
The issue can not be fixed by altering the code in this stage.

**Comment by starnetwork** [comment]
I mean, for example, redirect the user to "Dashboard" page after the settings are saved in first time, so it's will be clear that the process ended

**Comment by aribhour** [comment]
Redirection to dashboard is not a solution to this issue.
I remind you that the original issue is that new company is first created and then gets a name and ID.
You asked to revert the order and it is not posible to do that within the scope of curent project.
Sorry. but I insist to close this issue. It won't be fixed in this version.

**Comment by aribhour** [comment]
Again. The solution is placing a decent explanation for the user on this page so he will avoid creating a nameless company
