### ISSUE TITLE
API Connection question

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#526]
Hi,
we sending
$data = array("login_id" => "username", "login_hash" => "loginhashkey","login_comany" => "1");                                                                    
$data_string = json_encode($data);                                                                                   

to: http://tbit.speedcomp.co.il/api/list/user
and we got: 
{"status":403,"text":"Forbidden","body":"Error: Mode list is not implemented for model user","errorCode":0}
Please advice,

**Comment by adam2314** [comment]
"login_comany"??

**Comment by tzvir** [comment]
changed to 
$data = array("login_id" => "tbit", "login_hash" => "8ea9b0a09591d30a8ef0746c7cb26d14","login_company" => "1");                                                                    


same result
{"status":403,"text":"Forbidden","body":"Error: Mode list is not implemented for model user","errorCode":0}

**Comment by aribhour** [comment]
נא לקרוא בעיון רב את הדוקומנטציה של ה-API.
הפתרון לבעיות שלך נמצא בלימוד מעמיק שלה. במקרה הזה, השגיאה בקוד שלך נובעת מזה שאו ששכחת או שלא הבנת שאתה צריך לבחור חברה קודם.
אני מבקש קצת ביקורת עצמית לפני שאתה פותח נושאים בגיט.
תודה


":0}

**Comment by adam2314** [comment]
login_id is user->id and not username so try with one instead of "tbit" and those details (hash and url) shouldn’t be published.

**Comment by tzvir** [comment]
It works 

Thank you
