### ISSUE TITLE
תהליך הרשמה נתקע ללא הסבר בכמה נקודות - חברה לא כולם תכנתים כמוכם

### ISSUE THREAD

**Issue by ittay** [adam2314/linet3#527]

**Comment by ittay** [comment]
ממש מעצבן, סתם ביזבזתי חצי שעה
מסך הרשמת משתמש חוזר ללא הרף לא משנה איזה שם וסיסמה אני מכניס

**Comment by adam2314** [comment]
אתה מדבר על איזה שלב??
בתוכנה? באתר?

**Comment by ittay** [comment]
באתר, לא הגעתי מעבר לזה
תודה על התגובה!

  _____

**Comment by starnetwork** [comment]
היי איתי, ניתן להוריד את קוד התוכנה באמצעות הקישור הבא: https://github.com/adam2314/linet3/archive/master.zip

**Comment by adam2314** [comment]
אני דיי בטוח שהוא רוצה להתקין אותה על חלונות ואז הקישור ששלחת קצת פחות עוזר עד מבלבל מאוד.

**Comment by starnetwork** [comment]
בא נשמע מאיתי פידבק, אם הוא לא יודע מה לעשות עם זה, נבדוק את ההתחברות דרך האתר...

**Comment by ittay** [comment]
מעולה, אנסה כשאחזור מחופשה, תודה!

  _____

**Comment by ittay** [comment]
בכייף, אני חוזר עוד כמה ימים ואבדוק

  _____

**Comment by adam2314** [comment]
טוב עם אין פה עדכון אני אסגור את השרשור

**Comment by ittay** [comment]
תודה, מקווה להתפנות לזה שוב בקרוב
איתי

  _____

**Comment by aribhour** [comment]
גם סוגר עד קבלת תגובה חדשה מאיתי
