### ISSUE TITLE
קצת מפחיד לנהל את הכספים של העסק בתוכנה שמתקשה ברישום משתמשים ולוג אין

### ISSUE THREAD

**Issue by ittay** [adam2314/linet3#528]

**Comment by ittay** [comment]
ואין בה מינימום הוראות למשל מה סיסמה חוקית או פידבק למה קיבינמט המסך הרשמה חוזר 30 פעם ולא משנה מה מכניסים

**Comment by adam2314** [comment]
זוהי אזהרה ראשנוה ואחרונה.
אם לא תפתח באגים עם תוכן ענייני ותיאור ענייני הם לא יזכו להתייחסות
אני הייתי שמח עם הייתי מנקה את השפה של ההודעה הזו.

**Comment by ittay** [comment]
סליחה?
איזה שפה היית מנקה למשל?
למרות שזה גם טיפה ציני, זה אמת ולמי שמפתח תוכנה לאנשים רגילים (לא אנשי
תוכנה) שווה לחשוב על זה.
לא כתוב אצלכם בשום מקום שזה רק לבאגים, כתוב ההפך, שמצאתם שזו הדרך המתאימה
לנהל פורום למשתמשים.
אחרי שביזבזתי קרוב לשעה לחינם מותר להיות קצת ציני?
או שרק לך מותר להתחיל באזהרות ואיומים למישהו שבסה"כ עשה מה שאומרים לו ומתבאס
כי שום דבר לא עבד, שלא באשמתו?
בקיצור, כל הכבוד לכם על הפרויקט, שנשמע שהוא רציני ומובורך, למרות שלא זכיתי
בינתיים לבחון אותו;
וכל הכבוד למי שמקבל בברכה ביקורת של משתמשים ומזמין תקשורת חופשית ובלי איומים
- זה מאד עוזר לשפר את הפרויקט. 
(ואפילו אם הביקורת מגיעה עם מעט ציניות או כעס, אנחנו חיים במזרח התיכון, לא
בשבדיה) 
בהצלחה ואשמח לעידכון כשאפשר להרשם ולהוריד את התוכנה, זה מענין אותי.
תודה
איתי

  _____

**Comment by aribhour** [comment]
במקום לכתוב כל מיני תירוצים על מזרח תיכון וכיוצא בזה ירקות שאינן קשורות להתנהלות שלך, תתנצל וזהו. המילה קיבינינמאט ממש לא במקום ואף אחד כאן לא חייב לך כלום, נעזור לך בכיף אם תבוא ממקום טוב ומכבד ולא מעמדה תוקפנית.

**Comment by aribhour** [comment]
אם התכוונת לזה שנעלמה חלונית הכניסה והרישום לאתר אז הבעיה סודרה ואתה יכול להיכנס דרך האתר ולהוריד את התוכנה 
הבעיה נבעה ממתיחת פנים עיצובית שאנחנו עושים לאחרונה לאתר, כי הוא נראה זוועה לכל הדעות...
אם זאת לא הבעיה. תאר בקצרה ובמדויק מה כן הבעיה.

**Comment by ittay** [comment]
אני בחופשה, 
בקצרה, מה שאני זוכר,
הכנסתי המון פעמים סיסמא כי כל פעם אחרי הזנת פרטי משתמש הקומיט היה מחזיר אותי
לאותו דבר, רק בלי הסיסמא, אז שיערתי שמשהו לא בסדר בסיסמא. באמת היו פעמים
בודדות שעברתי את השלב הזה ויתכן שאפילו קיבלתי איזה פידבק (ויתכן שלא...) אבל
הנחתי שאקבל איזה פידבק למייל (שזה אחד המקומות היחידים שמתבקשים להזין אותו
פעמיים...) - אבל שום פידבק. אח"כ אף ניסיון להוריד את התוכנה לא הצליח, גם זה
ללא שום פידבק. וכל ניסיון ללוגין לא הוביל למשהו אחר ממה שהיה לפני שנרשמתי.
נסיתי להרשם גם עם 2-3 שמות משתמש, גם לא השפיע. זהו בערך.
להתראות
איתי

  _____

**Comment by adam2314** [comment]
טוב עם אין פה עדכון אני אסגור את השרשור

**Comment by ittay** [comment]
תודה, מקווה להתפנות לזה שוב בקרוב
איתי

  _____

**Comment by aribhour** [comment]
סוגר את הנושא עד לתגובה חדשה מאיתי
