### ISSUE TITLE
Manage docs give error

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#530]
Hi,
in ourlinet.speedcomp.co.il/docs/admin
we got the error: http://www.awesomescreenshot.com/image/509666/3407344c9d0ac44c8375476b89bfed75

I got it when I click on
הכנסות -> ניהול מסמכים

Please advice,

**Comment by adam2314** [comment]
הכנסת סטטוס לא נכון למסמך כלשהו.

**Comment by starnetwork** [comment]
אז אחד מה-2
המסמך הופק דרך ה-API
אם יש שם משהו שלא תקין, צריך להיות אימות לנתונים שלא מאפשר להכניס משהו שיגרום למע' לקרוס
אם אפשר להזין ערך כזה, האינדיקציה לכך שזה לא תקין לא צריכה להיות בצורה כזו בתוך המע' כך שבכל מקרה יש פה בעיה

**Comment by starnetwork** [comment]
Hi,
any comment for this close?
fixed / any update?

**Comment by adam2314** [comment]
added a function to get status name so the page won't fail
