### ISSUE TITLE
view docs error

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#531]
Hi,
got error on http://linetinstallation.speedcomp.co.il/docs/view/3
http://www.awesomescreenshot.com/image/509669/4a48847acff782642eda6bdd14ab2120

Please advice,

**Comment by adam2314** [comment]
הכנסת סטטוס לא נכון למסמך כלשהו.

**Comment by starnetwork** [comment]
אם יש שם משהו שלא תקין, צריך להיות אימות לנתונים שלא מאפשר להכניס משהו שיגרום למע' לקרוס
אם אפשר להזין ערך כזה, האינדיקציה לכך שזה לא תקין לא צריכה להיות בצורה כזו בתוך המע' כך שבכל מקרה יש פה בעיה

**Comment by starnetwork** [comment]
Please comment if this issue is fixed so we can follow / get update about that...

**Comment by adam2314** [comment]
also fixed.
