### ISSUE TITLE
Delete Products in Linet

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#535]
Hi,
I try to Delete Product and I got the following error:
 in /var/www/linet3/protected/vendor/yiisoft/yii2/base/Component.php at line 143
foreach ($this->_behaviors as $behavior) {
                if ($behavior->canGetProperty($name)) {
                    return $behavior->$name;
                }
            }
        }
        if (method_exists($this, 'set' . $name)) {
            throw new InvalidCallException('Getting write-only property: ' . get_class($this) . '::' . $name);
        } else {
            throw new UnknownPropertyException('Getting unknown property: ' . get_class($this) . '::' . $name);
        }
    }
 
    /**
     * Sets the value of a component property.
     * This method will check in the following order and act accordingly:
     *
     *  - a property defined by a setter: set the property value
     *  - an event in the format of "on xyz": attach the handler to the event "xyz"
2. in /var/www/linet3/protected/controllers/ItemController.php – yii\base\Component::__get('isPostRequest') at line 133
/**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        if (Yii::$app->request->isPostRequest) {
 
            // we only allow deletion via POST request
            $this->findModel($id)->delete();
 
            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
3. app\controllers\ItemController::actionDelete('6')

Please advice

**Comment by starnetwork** [comment]
Hi,
any comment?
this issue is fixed?

**Comment by adam2314** [comment]
fixed.
