### ISSUE TITLE
Duplicating Linet default Theme to new

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#536]
Hi,
can you please let me know what is the steps to duplicate Linet default theme to new theme so we can work on the new theme and let users select template to work.

Regards,

**Comment by adam2314** [comment]
Hello
You don't need to duplicate just use this:
http://www.yiiframework.com/doc-2.0/guide-output-theming.html

**Comment by starnetwork** [comment]
thanks for that answer!
but just to know, there is no default theme for Linet 3.1?
as good as I see, no @app/themes at all on our Installations
and not also in our private git

also, just to make it clear, linet supporting in few themes and unique css / js files for each theme?

**Comment by adam2314** [comment]
the default theme is @app/protected/views 
im not using  @app/themes path anymore

you can add any css or js...

**Comment by starnetwork** [comment]
so just to know, if I want to add another theme I should copy @app/protected/views to @app/protected/views2 ?

**Comment by adam2314** [comment]
1. you can. but i wouldn't copy all of it.
2. please read about Assets in the yii2 doc.
