### ISSUE TITLE
Login to linet in speedcomp installation

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#537]
Hi,
after the login I got this error:
Unknown Method – yii\base\UnknownMethodException
Calling unknown method: app\models\User::writeDateTime()

    */
    public function __call($name, $params)
    {
        $this->ensureBehaviors();
        foreach ($this->_behaviors as $object) {
            if ($object->hasMethod($name)) {
                return call_user_func_array([$object, $name], $params);
            }
        }
        throw new UnknownMethodException('Calling unknown method: ' . get_class($this) . "::$name()");
    }
 
    /**
     * This method is called after the object is created by cloning an existing one.
     * It removes all behaviors because they are attached to the old object.
     */
    public function __clone()
    {
        $this->_events = [];
2. in /var/www/linet3/protected/models/FormLogin.php – yii\base\Component::__call('writeDateTime', [1441194058]) a

**Comment by adam2314** [comment]
ok got it
