### ISSUE TITLE
כנראה שגיאה בעדכון קובץ אינדקס להתקנת לינוקס

### ISSUE THREAD

**Issue by chaimvaid** [adam2314/linet3#538]
שלום 

אמנם הצלחתי להתקין את התוכנה על לינוקס אולם על ידי הקבצים הישנים האינדקס החדש לא עובד לפחות אחד הקבצים הדרושים על ידי requier בקובץ האינדקס לא קיים בנתיב /protected/vendor/yiisoft/yii2/yii.php

**Comment by adam2314** [comment]
כרגע כל yii2 fw חסרה במקור
אני ממליץ לך להשתמש בגירסה 3.0 עם yii1.1
https://github.com/adam2314/linet3/tree/40912b23eea9b704f6e8c9563973d1dbc564a282

**Comment by starnetwork** [comment]
או לחלופין להוריד את ה
yii2 framework 
בנפרד ולשים בנתיב הרלוונטי

**Comment by adam2314** [comment]
זה לא מספיק.
אם הוא יודע לעבוד עם
 composer
 אז הוא יכול להסתדר אבל רוב התקייה של ה
vendor
לא עודכנה בגיט משום מה.
