### ISSUE TITLE
swiftmailer Should be included in the build

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#539]
Hi,
after clean Installation I got
PHP Fatal error:  require(): Failed opening required '/home/linetdev1/domains/linetdev/public_html/protected/vendor/swiftmailer/swiftmailer/lib/swift_required.php' (include_path='.:/usr/local/lib/php') in /home/linetdev1/domains/linetdev/public_html/protected/vendor/composer/autoload_real.php on line 54

and swiftmailer is not exist, so I was needed to download it manually, it's not big lib so please add it to the git

**Comment by adam2314** [comment]
i wont update the files in this git you should use the other one. there are a bench of libs missing in this commit.
