### ISSUE TITLE
Linet3.1 Clean Installation

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#540]
Hi,
I just install clean Installation of Linet 3.1, the steps:
1. Download lint 3.1
2. download Yii2 Framework and put it in the right location
3. Download and put swiftmailer lib in the right location,
4. DB settings are set in config/db.php 
the current status:
1. Error:
PHP Fatal error:  Class 'kartik\\datecontrol\\Module' not found in /home/dev1/domains/linetdev1.s4u.co.il/public_html/protected/config/web.php on line 28
2. the database is empty

there is any special URL / something I need to do for the installation?

Regards,

**Comment by aribhour** [comment]
Adam, your comment please

**Comment by adam2314** [comment]
https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

added vendor.zip thet includes the files needed

**Comment by starnetwork** [comment]
Hi,
Thanks for that!
1. I added public link for that, so it's be for everyone: http://www.filedropper.com/vendor
2. now, we on the next step
a. DB is empty
b. got the next error
Database Exception – yii\db\Exception

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dev1_ldb.auth_item' doesn't exist
The SQL being executed was: SELECT * FROM `auth_item` WHERE `name`='/company/index'
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'dev1_ldb.auth_item' doesn't exist
)
↵
Caused by: PDOException

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dev1_ldb.auth_item' doesn't exist

in /protected/vendor/yiisoft/yii2/db/Command.php at line 822

**Comment by aribhour** [comment]
With Linet 3.0 version and Yii1 there was a wizard activated the first time you browse to the application. The wizard configured the DB. This is one of the functions went wrong with the YII2 upgrade in linet 3.1.
Will fix it within this week and restore the wizard functionality.

**Comment by starnetwork** [comment]
thanks for that update, please keep me updated!
if possible, this is priority since anyone can do new installations...

**Comment by aribhour** [comment]
A little fund contribution for that functionality restore is not mandatory but will be most welcomed.

**Comment by aribhour** [comment]
We created a wizard covering this issue. We don't want to publish it yet since we don't want to encourage 3.1 instalations.
We will publish it within the couple of months.
