### ISSUE TITLE
ניסיון לשלוח מסמך באימייל מוביל להודעת שגיאה

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#542]
Swift_TransportException
Connection could not be established with host smtp.gmail.com [Connection timed out #110]

    1. in /var/www/install/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php at line 265
    256257258259260261262263264265266267268269270271272273274

            if (!empty($this->_params['timeout'])) {
                $timeout = $this->_params['timeout'];
            }
            $options = array();
            if (!empty($this->_params['sourceIp'])) {
                $options['socket']['bindto'] = $this->_params['sourceIp'].':0';
            }
            $this->_stream = @stream_socket_client($host.':'.$this->_params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, stream_context_create($options));
            if (false === $this->_stream) {
                throw new Swift_TransportException(
                    'Connection could not be established with host '.$this->_params['host'].
                    ' ['.$errstr.' #'.$errno.']'
                    );
            }
            if (!empty($this->_params['blocking'])) {
                stream_set_blocking($this->_stream, 1);
            } else {
                stream_set_blocking($this->_stream, 0);
            }

    2. in /var/www/install/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php – Swift_Transport_StreamBuffer::_establishSocketConnection() at line 62
    56575859606162636465666768

            switch ($params['type']) {
                case self::TYPE_PROCESS:
                    $this->_establishProcessConnection();
                    break;
                case self::TYPE_SOCKET:
                default:
                    $this->_establishSocketConnection();
                    break;
            }
        }
     
        /**
         * Set an individual param on the buffer (e.g. switching to SSL).

    3. in /var/www/install/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php – Swift_Transport_StreamBuffer::initialize(['protocol' => 'tcp', 'host' => 'smtp.gmail.com', 'port' => 25, 'timeout' => 30, ...]) at line 113
    107108109110111112113114115116117118119

                    if ($evt->bubbleCancelled()) {
                        return;
                    }
                }
     
                try {
                    $this->_buffer->initialize($this->_getBufferParams());
                } catch (Swift_TransportException $e) {
                    $this->_throwException($e);
                }
                $this->_readGreeting();
                $this->_doHeloCommand();
     

    4. in /var/www/install/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php – Swift_Transport_AbstractSmtpTransport::start() at line 79
    73747576777879808182838485

         */
        public function send(Swift_Mime_Message $message, &$failedRecipients = null)
        {
            $failedRecipients = (array) $failedRecipients;
     
            if (!$this->_transport->isStarted()) {
                $this->_transport->start();
            }
     
            $sent = 0;
     
            try {
                $sent = $this->_transport->send($message, $failedRecipients);

    5. in /var/www/install/protected/vendor/yiisoft/yii2-swiftmailer/Mailer.php – Swift_Mailer::send(Swift_Message) at line 140
    134135136137138139140141142143144145146

            $address = $message->getTo();
            if (is_array($address)) {
                $address = implode(', ', array_keys($address));
            }
            Yii::info('Sending email "' . $message->getSubject() . '" to "' . $address . '"', __METHOD__);
     
            return $this->getSwiftMailer()->send($message->getSwiftMessage()) > 0;
        }
     
        /**
         * Creates Swift mailer instance.
         * @return \Swift_Mailer mailer instance.
         */

    6. in /var/www/install/protected/vendor/yiisoft/yii2/mail/BaseMailer.php – yii\swiftmailer\Mailer::sendMessage(yii\swiftmailer\Message) at line 260
    7. in /var/www/install/protected/vendor/yiisoft/yii2/mail/BaseMessage.php – yii\mail\BaseMailer::send(yii\swiftmailer\Message) at line 48
    8. in /var/www/install/protected/models/Mail.php – yii\mail\BaseMessage::send() at line 82
    76777879808182838485868788

            //$mail->AddCC($this->cc); //.$this->cc
            //$mail->AddBcc($this->bcc);
            //$mail->
            //$mail->setHtmlBody($this->body);
            //$mail;
     
            if (!$mail->send()) {
                //echo "Mailer Error: " . $mail->ErrorInfo;
                throw new Exception(Yii::t('app', "Mailer Error: ") . $mail->ErrorInfo . $mail->Username);
            } else {
                $this->sent++;
                $this->save();
                \Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Message sent!'));

    9. in /var/www/install/protected/controllers/MailController.php – app\models\Mail::send() at line 22
    16171819202122232425262728

    class MailController extends RightsController {
     
        public function actionCreate() {
            $model = new Mail;
     
            if ($model->load(Yii::$app->request->post())){
                if ($model->send()){
                    //sent++
     
                    echo "done";
     
                }
                //$this->redirect(array('view', 'id' => $model->id));

    10. app\controllers\MailController::actionCreate()
    11. in /var/www/install/protected/vendor/yiisoft/yii2/base/InlineAction.php – call_user_func_array([app\controllers\MailController, 'actionCreate'], []) at line 55
    12. in /var/www/install/protected/vendor/yiisoft/yii2/base/Controller.php – yii\base\InlineAction::runWithParams([]) at line 151
    13. in /var/www/install/protected/vendor/yiisoft/yii2/base/Module.php – yii\base\Controller::runAction('create', []) at line 455
    14. in /var/www/install/protected/vendor/yiisoft/yii2/web/Application.php – yii\base\Module::runAction('mail/create', []) at line 83
    15. in /var/www/install/protected/vendor/yiisoft/yii2/base/Application.php – yii\web\Application::handleRequest(yii\web\Request) at line 375
    16. in /var/www/install/index.php – yii\base\Application::run() at line 27
    2122232425262728

        $config=require_once($load);
    }else{
        include('upgrade.php');
        $config=require_once(dirname(__FILE__).'/protected/config/web.php');
    }
     
    (new yii\web\Application($config))->run();
     

$_POST = [
    '_csrf' => 'cGFuMEk2N00JExZdfgJmPQMJJGcLXXABPwc3Xw9UZhodLyN9ZFtlKg==',
    'Mail' => [
        'files' => '73',
        'to' => 'phkhphk@gmail.com',
        'cc' => '',
        'bcc' => '',
        'subject' => '',
        'body' => '',
    ],
];

$_SERVER = [
    'REDIRECT_STATUS' => '200',
    'HTTP_HOST' => '10.0.0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
    'HTTP_REFERER' => 'http://10.0.0.8/index.php/docs/view/37?mail=1',
    'HTTP_COOKIE' => 'PHPSESSID=gptotlm91noq0bc7u5lkpkaso6; _csrf=353c740cb76ff6341a94aa38d6c07ac929ac8466afb2f061030c80649da7f424a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22yrxm74QpshJWBkGLOfYoFbQWmNMM-mRg%22%3B%7D; _identity=3730b8d3868db1d0f077dab290e7a85f8009c73fccb3fbb4f636883b646f260da%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A16%3A%22%5B1%2Cnull%2C2592000%5D%22%3B%7D',
    'HTTP_CONNECTION' => 'keep-alive',
    'CONTENT_TYPE' => 'application/x-www-form-urlencoded',
    'CONTENT_LENGTH' => '182',
    'PATH' => '/usr/local/bin:/usr/bin:/bin',
    'SERVER_SIGNATURE' => '
Apache/2.2.22 (Debian) Server at 10.0.0.8 Port 80

',
    'SERVER_SOFTWARE' => 'Apache/2.2.22 (Debian)',
    'SERVER_NAME' => '10.0.0.8',
    'SERVER_ADDR' => '10.0.0.8',
    'SERVER_PORT' => '80',
    'REMOTE_ADDR' => '10.0.0.7',
    'DOCUMENT_ROOT' => '/var/www/install',
    'SERVER_ADMIN' => 'webmaster@localhost',
    'SCRIPT_FILENAME' => '/var/www/install/index.php',
    'REMOTE_PORT' => '49713',
    'REDIRECT_URL' => '/mail/create',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'POST',
    'QUERY_STRING' => '',
    'REQUEST_URI' => '/mail/create',
    'SCRIPT_NAME' => '/index.php',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' => 1441548823.9430001,
    'REQUEST_TIME' => 1441548823,
];

$_COOKIE = [
    'PHPSESSID' => 'gptotlm91noq0bc7u5lkpkaso6',
    '_csrf' => '353c740cb76ff6341a94aa38d6c07ac929ac8466afb2f061030c80649da7f424a:2:{i:0;s:5:"_csrf";i:1;s:32:"yrxm74QpshJWBkGLOfYoFbQWmNMM-mRg";}',
    '_identity' => '3730b8d3868db1d0f077dab290e7a85f8009c73fccb3fbb4f636883b646f260da:2:{i:0;s:9:"_identity";i:1;s:16:"[1,null,2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 1,
    'company' => 3,
];

Yii Framework

2015-09-06, 17:14:14

Apache/2.2.22 (Debian)

Yii Framework/2.0.4-dev

**Comment by aribhour** [comment]
בדוק הגדרות שרת דואר יוצא בהגדרות חברה
חפש בגוגל את ההגדרות שצריכות להיות לשרת דואר יוצא
SMTP
של ג'ימייל ותעבור על ההגדרות, כולל שם משתמש וסיסמא.

**Comment by shaulmani** [comment]
זה עבד עד העדכון האחרון שאדם עשה אצלי.
האם העדכון של אדם תומך בזה ?
בגלל זה שאלתי על שרת העדכונים.
וכמובן שקודם כל בדקתי את ההגדרות (:


בתאריך 6 בספטמבר 2015 בשעה 17:23, מאת aribhour <notifications@github.com>:

**Comment by aribhour** [comment]
לא שאול, עם ההגדרות האלה שאני רואה אצלך ג'ימייל לעולם לא יעבוד.
 :)פורט 25 זה לא הפורט שאתו עובד ג'ימייל. בדוק את ההגדרות שלך (תיעזר באחיך.

**Comment by aribhour** [comment]
מתנצל שאני מתעקש, אבל הבעיה היא חד משמעית בהגדרות שלך

**Comment by shaulmani** [comment]
צודק, הסתדר, תודה (:

2015-09-06 17:41 GMT+03:00 aribhour <notifications@github.com>:
