### ISSUE TITLE
התקנה על אובונטו 

### ISSUE THREAD

**Issue by danreznik** [adam2314/linet3#543]
שלום לכולם,

כבר כמה זמן שאני מנסה להריץ את לינט דרך לינוקס ואני לא מצליח.

כל פעם אני מקבל את הודעת השגיאה הזו:

Warning: require_once(/var/www/html/protected/config/../../../../yii/yii.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 13

Fatal error: require_once(): Failed opening required '/var/www/html/protected/config/../../../../yii/yii.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/index.php on line 13

מישהו יודע איך פותרים את זה.

דן.

**Comment by adam2314** [comment]
אהלן
אתה צריך להוסיף yii 1.1
https://github.com/yiisoft/yii/releases/download/1.1.16/yii-1.1.16.bca042.tar.gz
ותפתח אוותו לפה:
/var/www/html/protected/
אחכ תתקן את הנתיב בקובץ
/protected/config/yii.php
שייצביע לקובץ בתקייה שפתחת

ותעדכן כאן אחכ:)

**Comment by danreznik** [comment]
אין לי את הקובץ הזה
/protected/config/yii.php

**Comment by adam2314** [comment]
מאיפה הורדת?
תנסה לעבוד עם הגרסה הזו:
https://github.com/adam2314/linet3/tree/40912b23eea9b704f6e8c9563973d1dbc564a282

**Comment by danreznik** [comment]
דבר מוזר, בגיט אני רואה שהקובץ קיים. אולם, כאשר אני מוריד את הקובץ (download zip), הקובץ לא נמצא בתיקייה.

**Comment by starnetwork** [comment]
היי, תנסה אולי למשוך את הגיט באמצעות
Clone

**Comment by adam2314** [comment]
אני דווקא רואה בdownload zip את הקובץ המתאים.
תנסה שוב או באמצאות clone.

**Comment by danreznik** [comment]
צילום מסך של תוכנת התיקייה
http://i60.tinypic.com/nv1fte.jpg

**Comment by aribhour** [comment]
לא רק תנסה. גם תודיע מה קרה :-)

**Comment by danreznik** [comment]
כמובן

**Comment by danreznik** [comment]
עשיתי clone 
אני עדיין לא רואה את הקובץ בתיקייה

http://oi61.tinypic.com/2aes6tv.jpg

**Comment by danreznik** [comment]
כעת יש לי בעיה אחרת. אני לא מצליח כלל להגיע למסך עם השגיאה
Warning: require_once(/var/www/html/protected/config/../../../../yii/yii.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 13

Fatal error: require_once(): Failed opening required '/var/www/html/protected/config/../../../../yii/yii.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/index.php on line 13

אני מקבל כל הזמן דף לבן

**Comment by danreznik** [comment]
הערה נוספת, עכשיו כשאני מסתכל ברשימת הקבצים בגיט אני לא רואה את הקובץ
/protected/config/yii.php

**Comment by danreznik** [comment]
הצעה
אני מוכן ליצור מדריכי התקנה מצולמים למערכת (קודם אבל צריך להתקין אותה)

**Comment by danreznik** [comment]
טוב ישנה התקדמות מסויימת...
נזכרתי שלפני כמה חודשים הורדתי גרסה של המערכת ואותה הצלחתי לעלות אבל לא עד הסוף.

אדם2314, ערכתי את הקובץ yii.php 
כמו שאמרת והצלחתי להריץ.

במקום http://localhost/install/
שלא עובד ומציג שגיאה 404 גם כשהפעלתי מוד רירייט וגם כשביטלתי אותו.
הרצתי http://127.0.0.1/index.php?r=install
אומנם היו כמה שגיאות שפתרתי אותם בקלות, ועכשיו אני נתקבל בדבר הבא
http://oi61.tinypic.com/oti4va.jpg

האזהרה בראש הדף נפתרה ע"י עידכון של פרטי ההתחברות לדטה בייס בקובץ install.php
נותרה לי הבעיה של ההרשאות, אינני יודע לאילו קבצים ותיקיות לתת אילו הרשאות.
אשמח אם תוכלו לתת רשימה מעודכנת.

והשגיאה האחרונה (אני מקווה)
http://oi57.tinypic.com/2jcez5t.jpg

**Comment by danreznik** [comment]
את הבעיה של הרשאות הכתיבה פתרתי ע"י
sudo chown -R www-data /var/www/html

כעת נשארה הבעיה האחרונה שכאשר לוחצים על נקטס קופצת השגיאה הבאה:
http://oi57.tinypic.com/2jcez5t.jpg

לפי ההיסטוריה, משתמש אחר נתקל בבעיה הזו הסביר מה הוא עשה אבל ללא דוגמא.
לפי ההיסטוריה הבעיה נובעת מכך שכאשר לוחצים על נקטס הדף מפנה ל
http://127.0.0.1/install
והוא צריך להפנות אל
http://127.0.0.1/index.php?r=install

הפתרון הוא לכתוב חוק כתיבה בrewrite, 
הבעיה שאני לא יודע איך עושים את זה.

**Comment by adam2314** [comment]
קודם כל כל הכבוד על הנחישות שלך ועל ההצעה לכתוב מדריך אנחנו כמובן נשמח.
שנית על מנת להפעיל rewrite
כדאי להפעיל את המודל
אובנטו:
`a2enmod rewrite`
ואז לאפשר override בsite
`/etc/apache2/sites-enabled/000-default.conf`

```
 <Directory />
                Options FollowSymLinks
                AllowOverride All
        </Directory>
        <Directory /var/www/linet3-dev/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                #None
                Order allow,deny
                allow from All
        </Directory>
```

מה שכתבתי לגבי הsite
כנראה עוד לא עשית ולכן החוקי rewrite
שבקובץ .htaccess
לא באים לידי ביטוי
אם לא קיים אצלך אתה יכול לראות בגיט(קובץ נסתר)

**Comment by danreznik** [comment]
תודה רבה.

אנסה את פיתרונך ואעדכן

בתאריך 8 בספטמבר 2015 בשעה 9:26, מאת adam2314 <notifications@github.com>:

> קודם כל כל הכבוד על הנחישות שלך ועל ההצעה לכתוב מדריך אנחנו כמובן נשמח.
> שנית על מנת להפעיל rewrite
> כדאי להפעיל את המודל
> אובנטו:
> a2enmod rewrite
> ואז לאפשר override בsite
> /etc/apache2/sites-enabled/000-default.conf
>
>  <Directory />
>                 Options FollowSymLinks
>                 AllowOverride All
>         </Directory>
>         <Directory /var/www/linet3-dev/>
>                 Options Indexes FollowSymLinks MultiViews
>                 AllowOverride All
>                 #None
>                 Order allow,deny
>                 allow from All
>         </Directory>
>
> מה שכתבתי לגבי הsite
> כנראה עוד לא עשית ולכן החוקי rewrite
> שבקובץ .htaccess
> לא באים לידי ביטוי
> אם לא קיים אצלך אתה יכול לראות בגיט(קובץ נסתר)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adam2314/linet3/issues/543#issuecomment-138448638>.
>



-- 
דן רזניק
טל': 972-54-6599309+

**Comment by danreznik** [comment]
עשיתי את מה שאמרת.
עכשיו http://127.0.0.1/install :
Not Found

The requested URL /install was not found on this server.

Apache/2.4.10 (Ubuntu) Server at 127.0.0.1 Port 80

http://127.0.0.1/index.php?r=install
מסך ריק לבן ללא קוד

**Comment by adam2314** [comment]
אחרי השינויים צריך לעשות
service apache2 restart
נראה שה rewrite 
עדיין לא מופעל אצלך

**Comment by danreznik** [comment]
מופעל, אבל עשיתי שוב ועדיין  אותה תוצאה

**Comment by adam2314** [comment]
אז תן לנו את הפלט של:
tail /var/log/apache2/error.log

**Comment by danreznik** [comment]
```[Mon Sep 07 20:43:57.617992 2015] [mpm_prefork:notice] [pid 19974] AH00163: Apache/2.4.10 (Ubuntu) PHP/5.5.12-2ubuntu4.6 configured -- resuming normal operations
[Mon Sep 07 20:43:57.618036 2015] [core:notice] [pid 19974] AH00094: Command line: '/usr/sbin/apache2'
[Mon Sep 07 20:44:45.472019 2015] [mpm_prefork:notice] [pid 19974] AH00169: caught SIGTERM, shutting down
[Mon Sep 07 20:44:46.556738 2015] [mpm_prefork:notice] [pid 20501] AH00163: Apache/2.4.10 (Ubuntu) PHP/5.5.12-2ubuntu4.6 configured -- resuming normal operations
[Mon Sep 07 20:44:46.556770 2015] [core:notice] [pid 20501] AH00094: Command line: '/usr/sbin/apache2'
[Mon Sep 07 21:41:33.387414 2015] [mpm_prefork:notice] [pid 1421] AH00163: Apache/2.4.10 (Ubuntu) PHP/5.5.12-2ubuntu4.6 configured -- resuming normal operations
[Mon Sep 07 21:41:33.513708 2015] [core:notice] [pid 1421] AH00094: Command line: '/usr/sbin/apache2'
[Tue Sep 08 16:47:06.572211 2015] [mpm_prefork:notice] [pid 1421] AH00169: caught SIGTERM, shutting down
[Tue Sep 08 16:47:07.704873 2015] [mpm_prefork:notice] [pid 7382] AH00163: Apache/2.4.10 (Ubuntu) PHP/5.5.12-2ubuntu4.6 configured -- resuming normal operations
[Tue Sep 08 16:47:07.704909 2015] [core:notice] [pid 7382] AH00094: Command line: '/usr/sbin/apache2'
```

**Comment by adam2314** [comment]
:<
שום דבר מעניין שם
טוב אז בוא ננסה את זה ביותר מלוכלך

`index.php`

שורה שניה ישר מתחת

`>?php`
תוסיף
```
error_reporting(E_ALL);
ini_set('display_errors', 1);
```
ותראה אם אתה מקבל תוצאה שונה מדף לבן.

**Comment by danreznik** [comment]
ריק לחלוטין

**Comment by adam2314** [comment]
כנראה שהקובץ
/protected/config/yii.php
לא תקין

**Comment by danreznik** [comment]
זה תוכן הקובץ

<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');

//must be full path!
$yii=dirname(__FILE__).'/../yii/framework/yii.php';
// remove the following lines when in production mode
defined('YII_DEBUG') or define('YII_DEBUG',true);
// specify how many levels of call stack should be shown in each log message
defined('YII_TRACE_LEVEL') or define('YII_TRACE_LEVEL',3);

**Comment by adam2314** [comment]
נרראה תקין.
תוכן הקובץ index.php?

**Comment by aribhour** [comment]
היי דן, אל תתייאש בוא ננסה לסיים את זה תן משוב לאדם וננסה לפתור את הבעיה

**Comment by danreznik** [comment]
אל תאגה אני לא מתייאש
הנה התוכן של האינדקס

<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
/***********************************************************************************
 * The contents of this file are subject to the Mozilla Public License Version 2.0
 * ("License"); You may not use this file except in compliance with the Mozilla Public License Version 2.0
 * The Original Code is:  Linet 3.0 Open Source
 * The Initial Developer of the Original Code is Adam Ben Hur.
 * All portions are Copyright (C) Adam Ben Hur.
 * All Rights Reserved.
 ************************************************************************************/


require_once(dirname(__FILE__).'/protected/config/yii.php');
require_once($yii);


$load=dirname(__FILE__)."/../linet3admin/protected/addon/load.php";
if(file_exists($load)){
    $config=require_once($load);
}else{
    $config=dirname(__FILE__).'/protected/config/main.php';
}

Yii::createWebApplication($config)->run();
//echo ";".Yii::app()->theme.";";

//php:curl,zip,apc
//wkhtmltopdf
//apache: mod_rewrite
//mysql

//open format import linet 2 db error fld 1322
//must fix.

 מכל הקוד אני רק לא יודע מה הקשר של התיקייה הזו והקובץ הזה
$load=dirname(__FILE__)."/../linet3admin/protected/addon/load.php";

הם לא קיימים אצלי

**Comment by danreznik** [comment]
שאלה נוספת, 
האם ניתן להריץ את המערכת משרת של גו דדי או חברת אחסון אחרת?

**Comment by starnetwork** [comment]
כן, ניתן להריץ את זה מכל שרת סטנדרטי שתומך ב
PHP / MySQL
והספריות הנדרשות, שהם בסיסיות

**Comment by aribhour** [comment]
אנחנו יכולים לארח בשבילך לינט לתקופת ניסיון בחינם

**Comment by danreznik** [comment]
אני מריץ את המערכת על וירוס
פשוט כחובב לינוקס אני מעוניין להריץ אותה על לינוקס

**Comment by aribhour** [comment]
דרישות תוכנה וחומרה להתקנת לינט: ראה כאן
http://www.linet.org.il/support/installation-manuals/linux/3

**Comment by danreznik** [comment]
מה לגבי תוכן קובץ האינדקס? האם הכל בסדר?

**Comment by danreznik** [comment]
העליתי את הקבצים לשרת חיצוני זו השגיאה שקיבלתי

Warning: require(/public_html/linet/protected/vendor/swiftmailer/swiftmailer/lib/swift_required.php): failed to open stream: No such file or directory in /home/u170201516/public_html/linet/protected/vendor/composer/autoload_real.php on line 54

Fatal error: require(): Failed opening required '/home/public_html/linet/protected/vendor/swiftmailer/swiftmailer/lib/swift_required.php' (include_path='.:/opt/php-5.5/pear') in /home/public_html/linet/protected/vendor/composer/autoload_real.php on line 54

התיקייה שהוא מפנה הינה ריקה

**Comment by adam2314** [comment]
הקובץ אינדקס שהעלת בסדר גמור.
מה שהעלת לשרת צד שלישי זו לא הגריסה הנכונה
תחזור לתחילת השרשור ותקרא  מאיפה להוריד

**Comment by danreznik** [comment]
לייתר ביטחון אני הורדתי את הגרסא המצויינת בתחילת השירשור, העליתי אותה לשרת צד שלישי וזה מה שקיבלתי


```Warning: require(/home/u170201516/public_html/linet3/protected/vendor/swiftmailer/swiftmailer/lib/swift_required.php): failed to open stream: No such file or directory in /home/u170201516/public_html/linet3/protected/vendor/composer/autoload_real.php on line 54

Fatal error: require(): Failed opening required '/home/u170201516/public_html/linet3/protected/vendor/swiftmailer/swiftmailer/lib/swift_required.php' (include_path='.:/opt/php-5.5/pear') in /home/u170201516/public_html/linet3/protected/vendor/composer/autoload_real.php on line 54
```

אין שינוי

**Comment by starnetwork** [comment]
יש שינוי, תוריד את swiftmailer
מפה: http://swiftmailer.org/download
ותשים בתיקייה הנכונה 
u170201516/public_html/linet3/protected/vendor/swiftmailer
וזה יתקדם לך
תשים לב שבשלב הבא אתה צריך גם את תיקיית ה-vandor

**Comment by danreznik** [comment]
צריך רק את התיקייה או שצריך להיות בה תוכן? אם כן,  מאיפה מורידים את התוכן?
בתאריך 10 בספט׳ 2015 16:04,‏ "starnetwork" <notifications@github.com> כתב:

**Comment by danreznik** [comment]
OK
הורדתי את הסוויפטמיילר והתקנתי. השגיאה ההיא אינה קיימת יותר
עכשיו זו השגיאה הזו:

Warning: require(/home/u170201516/public_html/linet3/protected/vendor/yiisoft/yii2/Yii.php): failed to open stream: No such file or directory in /home/u170201516/public_html/linet3/index.php on line 17

Fatal error: require(): Failed opening required '/home/u170201516/public_html/linet3/protected/vendor/yiisoft/yii2/Yii.php' (include_path='.:/opt/php-5.5/pear') in /home/u170201516/public_html/linet3/index.php on line 17

**Comment by danreznik** [comment]
התקנתי את yii2 
השגיאה נעלמה

כעת מה שאני רואה זה:
Fatal error: Class 'kartik\datecontrol\Module' not found in /home/u170201516/public_html/linet3/protected/config/web.php on line 28

כיצד פותרים?

**Comment by starnetwork** [comment]
לדעתי צריך להמתין כמה ימים עד שתעלה גרסה חדשה שתפתור את השגיאה שאתה מדבר עליה...

**Comment by danreznik** [comment]
אוקיי

**Comment by danreznik** [comment]
יש חדש?

**Comment by starnetwork** [comment]
היי,
נראה שהגרסה החדשה לא תצא כמתוכנן עקב עניינים שונים, בכל מקרה מומלץ כעת להשתמש בגרסה הנוכחית לפי ההוראות שאדם רשם פה...

**Comment by danreznik** [comment]
אני מבין, אך עקבתי אחר ההוראות ועדיין אני לא מצליח להפעיל את המערכת על שרת
לינוקס (הן פרטי והן חיצוני)

**Comment by adam2314** [comment]
אהלן.
לפי ההודעות האחרונות שלך אתה לא משתמש בגירסה שקשרתי בתחילת הפוסט.
כרגע ניתן לעבוד רק עם 
yii1.1 
ולא עם
 2

תוריד מחדש מפה או מפה זה אותו דבר
https://github.com/adam2314/linet3/releases
https://github.com/adam2314/linet3/tree/40912b23eea9b704f6e8c9563973d1dbc564a282

ואחכ תוסיף לזה 
yii1.1
https://github.com/yiisoft/yii/releases/download/1.1.16/yii-1.1.16.bca042.zip

**Comment by danreznik** [comment]
האחרי ההעלאה, ושינוי ההגדרות דטה בייס אני קיבלתי את השגיאה הזו

Fatal error: Call to undefined function apache_get_modules() in /home/public_html/linet4/protected/models/InstallPre.php on line 32

מה עושים?

**Comment by danreznik** [comment]
אני חושב שמקור השגיאה נובע מכך שסינטקס החיבור לדטה בייס 

עשיתי שינוי קטן מ
mysql
ל
mysqli

ועכשיו השגיאה היא
Caught exception: CDbConnection failed to open the DB connection: could not find driver 
Fatal error: Call to undefined function apache_get_modules() in /home/public_html/linet4/protected/models/InstallPre.php on line 32

האם המערכת מותאמת לphp 5.3

**Comment by adam2314** [comment]
5.4 עד 5.6
עדיף
אבל גם זה צריך להיות בסדר
אנחנו משתמשים בmysql

יצרת DB כמו שמתואר פה?
http://www.linet.org.il/%D7%AA%D7%9E%D7%99%D7%9B%D7%94-%D7%91%D7%9C%D7%99%D7%A0%D7%98-%D7%AA%D7%95%D7%9B%D7%A0%D7%94-%D7%9C%D7%A0%D7%99%D7%94%D7%95%D7%9C-%D7%A2%D7%A1%D7%A7/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%94%D7%AA%D7%A7%D7%A0%D7%94-%D7%9C%D7%9C%D7%99%D7%A0%D7%98-%D7%AA%D7%95%D7%9B%D7%A0%D7%AA-%D7%94%D7%A0%D7%94%D7%9C%D7%AA-%D7%97%D7%A9%D7%91%D7%95%D7%A0%D7%95%D7%AA/%D7%94%D7%AA%D7%A7%D7%A0%D7%AA-%D7%9C%D7%99%D7%A0%D7%98-%D7%A2%D7%9C-%D7%9E%D7%97%D7%A9%D7%91-%D7%9C%D7%99%D7%A0%D7%95%D7%A7%D7%A1

**Comment by danreznik** [comment]
OK

אז מה פירוש הודעת השגיאה הזו:


Fatal error: Call to undefined function apache_get_modules() in /home/u170201516/public_html/linet4/protected/models/InstallPre.php on line 32

**Comment by adam2314** [comment]
http://php.net/manual/en/function.apache-get-modules.php

מה הפלט של
`php -v`
`apache2 -v`

**Comment by danreznik** [comment]
השרת מגביל אותי בלוגים שאני יכול להוציא, אבל זה מה שהצלחתי לאתר:

[Tue Sep 22 11:16:31.795174 2015] [fcgid:warn] [pid 1040307:tid 140236703049472] [client 84.110.210.251:52566] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function apache_get_modules() in /home/danreznik/public_html/protected/models/InstallPre.php on line 32
[Tue Sep 22 11:16:21.119199 2015] [fcgid:warn] [pid 1040406:tid 140236818437888] [client 84.110.210.251:52557] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function apache_get_modules() in /home/danreznik/public_html/protected/models/InstallPre.php on line 32
[Tue Sep 22 11:15:02.570097 2015] [fcgid:warn] [pid 1040116:tid 140236839417600] [client 84.110.210.251:51117] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function apache_get_modules() in /home/danreznik/public_html/protected/models/InstallPre.php on line 32

**Comment by danreznik** [comment]
apache_get_modules() does not work if you are using PHP as CGI.

יכול להיות שכאן הבעיה...

**Comment by adam2314** [comment]
אנחנו לא נתמוך ב
CGI
אתה בטוח שככה המערכת שלך מוגדרת?
http://php.net/manual/en/install.unix.commandline.php

**Comment by danreznik** [comment]
תראה יצרתי קובץ בדיקה בשם
http://danreznik.co.il/pre.php

תוכן הקובץ:
<?php
print_r(apache_get_modules());
?>

הפלט המצופה:
Array
(
    [0] => ...
    [1] => ...
    [2] => ...
    [3] => ...
    [4] => ...
    [5] => ...
)

או משהו בסגנון.

אולם השגיאה שקיבלתי הינה:
Fatal error: Call to undefined function apache_get_modules() in /home/u170201516/public_html/pre.php on line 2

המסקנה המתבקשת שהפונקציה 
apache_get_modules()
אינה נתמכת ברמת השרת

בעניין הפונקציה הזו רשום:
apache_get_modules() - 
this only works when PHP is installed as an Apache module. This will not function when using PHP as CGI (ex: suPHP)

הרצתי את הפונקציה
phpinfo() 

פלט:
http://danreznik.co.il/phpinfo.php

וה server API
Server API	CGI/FastCGI

כך שהפונקציה הזו לא יכולה לרוץ על השרת הזה או כל שרת דומה

ניסיתי להריץ את המערכת גם על הוסטינגר, גו-דאדי ושרת נוסף שמריץ
IIS
ואף אחד מהם לא עבד.

פתרונות אפשריים:
1. מציאת שרת אינטרנט חליפי
(אשמח לקבל המלצה)
2. שיכתוב הקוד וביטול השימוש בפונקציה הבעייתית ומציאת אלטרנטיבה

**Comment by adam2314** [comment]
1. שלום, זה התחום שלך
2. אנחנו לא מעוניינים כרגע בלשכתב את הקוד הזה.

**Comment by starnetwork** [comment]
היי,
לשיפור התמיכה הייתי ממליץ להוסיף פשוט בדיקה האם הפונקציה קיימת ואז לקרוא לה ואם לא, להציג הודעה שאין מידע וכדו'
if (function_exists('apache_get_modules')) {
apache_get_modules()
and other related code
}
else {
no support for apache modules, maybe phpinfo show some related info
}

זה רלוונטי גם ל-Nginx
ודברים נוספים ולדעתי יהיה חיובי כהרחבת התמיכה למגוון סוגי שרתים

**Comment by danreznik** [comment]
OK
זה הקוד שהרצתי:

<?php
if (function_exists('apache_get_modules')) {
    // call the function
    apache_get_modules();
    // write your other related code
}
else{
    // show message 
    echo "no support for apache modules";
    // get php info
    phpinfo();
}

?>

זה הפלט
no support for apache modules

http://danreznik.co.il/test.php

**Comment by danreznik** [comment]
לכל הפחות שווה להכניס את זה כדרישה מקדימה בהוראות ההתקנה

**Comment by danreznik** [comment]
אם אני לא טועה על מנת שהסקריפט  ירוץ  צריך 
mod_suphp

מרבית השרתים הפופולרים מריצים 
PHP
דרך
mod_fcgid

אולי באמת יהיה שווה לשנות את הקוד ככה שיותר אנשים יוכלו להריץ את המערכת

**Comment by adam2314** [comment]
mod_php 
זה מספיק
אין צורך ב
su

אני עדיין לא מעוניין לשנות את הקוד.
כל תרומה תתקבל בברכה.

**Comment by danreznik** [comment]
מזה 12 ימים אני מנסה למצוא שרת שיכול להריץ את המערכת (שירות איחסון) 
לצערי הרב טרם הצלחתי לעשות זאת.

מספר סיבות לכך:
1. המערכת לא רצה על שרת שמריץ פי אייץ׳ פי שלא ב-
 mod_php.
השימוש בפונקציה apache_get_modules
גורם לכך שהמערכת מנועה מלרוץ במרבית השרתים כי הפונקציה הזו לא קיימת בשרתים שמריצים פי אייץ׳ פי כ-
mod_suphp
או
FastCGI
או למעשה כל מוד אחר מלבד מוד פי אייץ׳ פי.

הפיתרון לסוגייה הזו הוא פשוט להריץ שרת וירטואלי פרטי, אך אז שאלתי את עצמי למה מרבית השרתים לא מריצים את הפונקציה הזו או רצים על מוד פי אייץ׳ פי.
והתשובה לכך מביאה אותנו לבעיה השנייה והיא אבטחת  מידע.

שרת שרץ על מוד פי אייץ׳ פי הוא שרת הרבה הרבה הרבה יותר פגיע למתקפה של פצחנים וזה מסכן את כל המערכת, המידע וחושף את המפעיל למצב של גניבת מידע.
למותר לציין כי גם אם מוצאים שרת שעובד על מוד פי אייץ׳ פי או משתמשים בשרת וירטואלי פרטי ומתקינים מוד פי אייץ׳ פי, זה בכלל לא חכם לאפשר את הרצת הפונקציה
apache_get_modules
כי היא חושפת את השרת לבעיות אבטחה ופצחן יכול בעזרתה להשתלט על המערכת ולגנוב מידע.

אדם, אני לא יודע מה אתה עושה או תעשה עם המידע הזה אבל זה לא משהו שניתן להתעלם ממנו.
שימוש בפונקציה חושף את המערכת כולה לבעיות אבטחת מידע וצריך לטפל בזה

לצערי, לי אין את הידע הנדרש לכתוב קוד ולשנות את זה.
אבל אשמח לסייע בדרך אחרת.

**Comment by adam2314** [comment]
ראשית השימוש בפונקציה
apache_get_modules
נעשה רק באשף ההגדרה הראשונית של המערכת עוד לפני שיש נתונים על המערכת.
אז אני חושב שאנחנו די בסדר עם הנקודה הזו
אחרי הגדרה ראשונית אין יותר יכולת לגשת לפונקציה הזו.

שנית אנחנו לא נעדכן כרגע את הקוד שנמצא בrelease

ולמקרה הספצפי שלך 
`protected/models/InstallPre.php`
שורה 31
```php
         private function apachechk($str){
             if (function_exists('apache_get_modules'))
                $array=apache_get_modules();
            else
               $array=[];
            if(in_array($str,$array))
                return Yii::t('app', "OK");
            else 
                return Yii::t('app', "Failed");
        }
```

**Comment by danreznik** [comment]
זה שהשימוש בפונקציה הזו הוא רק באשף ההתקנה,  לא עושה את המערכת ליותר
מאובטחת. אני דיברתי על בעיות אבטחה ברמת השרת. כי שרת שמאפשר את הרצת
הפונקציה הוא בהכרח שרת הרבה הרבה הרבה יותר פגיע למתקפות של פצחנים וכך גם
המערכת שרצה על אותו שרת פגיעה באותה הרמה

**Comment by adam2314** [comment]
אהלן דן
הצעתי לך פתרון להריץ את המערכת כמו שאתה רוצה.
לא בעזרת mod_php
או שתקח אותו או שלא.

**Comment by adam2314** [comment]
אגב למה שרת כזה הוא בהכרח יותר פגיע? אנא הבא לכאן סימוכין

**Comment by danreznik** [comment]
בגדול זה עניין של הרשאות. לכל משתמש בשרת יש את הרשאות הגישה לכל הקבצים
כלומר אין מידור משתמשים.
אפשר לקרוא על זה בקיצור כאן:
http://boomshadow.net/tech/php-handlers/

**Comment by adam2314** [comment]
זה רק בתנאי שאתה מפעיל כמה אתרים על אותו שרת..
יש גם פלוס 
mod_php
יש בזה שיפור ביצועים

**Comment by danreznik** [comment]
תראה דבר, הבעיה הגדולה בזה היא בשרתי אחסון משותף המערכת לא יכולה לעבוד. ואם
כן היא תהיה חשופה לפריצה.
דבר נוסף שיכול להיות בעייתי הוא מתן הרשאות לקבצים( כתיבה / קריאה). זה גם
חושף את המערכת לכך שפצחן שניצל פרצה או באג בקוד של לינט יכול להשתלט על
הקבצים, הדטה והמחשב בכלל.

גם fastcgi הוא מהיר באותה רמה ואולי יותר ולו אין את בעיות האבטחה שיש במוד
פי אייץ' פי.

**Comment by aribhour** [comment]
דן,
כבר כמה פעמים נאמרו כאן הדברים הבאים:
א. שרתי אירוח משותפים אינם נתמכים.
ב. בגרסה 3.0 שאתה עובד איתה לא יתבצעו שינויי קוד כלשהם כי אנחנו כבר עובדים על גרסה 3.1 ובטח שלא על מנת לפתור את הבעיה של
PHP_MODE
שמלכתחילה נאמר שלא נטפל בה בגרסה זו ואולי לא בכלל
מכאן אתה צריך להחליט מה אתה רוצה לעשות.:
 א. לחכות לגרסה הבאה בתקווה שאחד מהשינויים שנעשה יגרום לכך שזה יעבוד אצלך בצורה שאתה מעונין 
ב. למצוא לך שרת לא שיתופי.
אני סוגר את הנושא
