### ISSUE TITLE
working version with yii1.1

### ISSUE THREAD

**Issue by ghadad** [adam2314/linet3#545]
Hi Adam , 
Where can i find  tha last working version before you moved to Yii2 ? 
I tried to install the new  3.1 (Yii2)  version but now i'm stuck with the install/index action  
It says that there is an infinite redirect loop ... 
Can you give us some manual instructions to complete the instalation ? 
Thanks 
Golan

**Comment by adam2314** [comment]
you can use this
https://github.com/adam2314/linet3/releases
read this before
http://www.linet.org.il/support/installation-manuals/linux/3
watch this issue
https://github.com/adam2314/linet3/issues/543
and send feedback.

**Comment by ghadad** [comment]
Thank you ..

**Comment by ghadad** [comment]
So far so good ... 
But I have one problem .. files and images are not uploaded  in items managemenet ... 
I look at ItemController.php and didn't see any FileUpload handling ...   
the form should include multipart  in form type ... 

Best regards 
Golan

**Comment by adam2314** [comment]
so that is a different issue im closing this one.
you can open anther one describing your request/problem
