### ISSUE TITLE
איך מעדכנים את המע"מ ל-17% מיום 1.10.15 ? תודה

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#550]

**Comment by aribhour** [comment]
ראה כאן:
http://linet.org.il/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9-%D7%9C%D7%9C%D7%99%D7%A0%D7%98-%D7%9B%D7%9C%D7%9C%D7%99/%D7%A7%D7%91%D7%99%D7%A2%D7%AA-%D7%A9%D7%99%D7%A2%D7%95%D7%A8-%D7%94%D7%9E%D7%A2-%D7%9E-%D7%91%D7%9C%D7%99%D7%A0%D7%98-%D7%AA%D7%95%D7%9B%D7%A0%D7%94-%D7%9C%D7%94%D7%A0%D7%94%D7%9C%D7%AA-%D7%97%D7%A9%D7%91%D7%95%D7%A0%D7%95%D7%AA

**Comment by shaulmani** [comment]
כדאי להשאיר שכל המשתמשים יוכלו להיעזר בזה
תודה
