### ISSUE TITLE
אדם, פורמט הדפסה בהעתקי מסמכים עדיין משובש

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#555]

**Comment by adam2314** [comment]
תוסיף תמונות ופירוט בבקשה

**Comment by shaulmani** [comment]
שלחתי לך בעבר באימייל.
אעביר אליך ישירות שוב בהמשך

2015-10-08 15:53 GMT+03:00 adam2314 <notifications@github.com>:

**Comment by shaulmani** [comment]
רצ"ב
![default](https://cloud.githubusercontent.com/assets/9477331/10368880/1779d136-6de0-11e5-977b-0f0e9546ba7d.jpg)

**Comment by shaulmani** [comment]
בחשבונית זה תקין חשבונית מס קבלה משובש  כמו בדוגמה

**Comment by adam2314** [comment]
אני לא מבין מה לא תקין
אתה מדבר על הכותרת?
כי אם כן זה בהגדרות הדפסה של הדפדפן

**Comment by shaulmani** [comment]
לדעתי המסמך קצת מרוח. מצד שני הכל תקין ברמת התוכן אז תתעלם ותסגור.
בתאריך 8 באוק' 2015 17:51,‏ "adam2314" <notifications@github.com> כתב:
