### ISSUE TITLE
במסך תנועות יומן שדה תאריך ערך יש שעה 00:00:00 

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#556]
חושב שזה מיותר אולי כדי להשתמש בשדות לצורך אחר

**Comment by adam2314** [comment]
done.

**Comment by shaulmani** [comment]
​כשכתוב
done
למה הכוונה ?
אשמח אם תסבירו מינוחים נוספים שאתם משתמשים בהם​.
תודה

2015-10-08 15:53 GMT+03:00 adam2314 <notifications@github.com>:

**Comment by adam2314** [comment]
זה אומר שבהקשר הז חתכתי את ה
00:00:00
מהתצוגות הרלוואנטיות
