### ISSUE TITLE
רצף כרטסות חשבון עדיין מציג מסמכים ולא כרטסת.

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#557]
אופן ההצגה בלינט 3 היה תקין.

**Comment by adam2314** [comment]
אצלי זה מציג תנועות יומן תעלה צילום מסך

**Comment by shaulmani** [comment]
מצ"ב :
רצף כרטסות חשבון
מתאריך
עד תאריך
טווח מספרי חשבון
דוגמאות:
1-200
1,3,5
1-10,15-20,25-30
סוג חשבון
סוג חשבון
113 לקוחות שונים
array(7) { ["num"]=> array(1) { [0]=> string(38) "מס' לא יכול להיות ריק." } ["account_id"]=> array(1) { [0]=> string(43) "חשבון לא יכול להיות ריק." } ["valuedate"]=> array(1) { [0]=> string(50) "תאריך ערך לא יכול להיות ריק." } ["currency_id"]=> array(1) { [0]=> string(41) "מטבע לא יכול להיות ריק." } ["sum"]=> array(1) { [0]=> string(41) "סכום לא יכול להיות ריק." } ["owner_id"]=> array(1) { [0]=> string(43) "בעלים לא יכול להיות ריק." } ["linenum"]=> array(1) { [0]=> string(47) "שורה מס' לא יכול להיות ריק." } }
מציג 1-8 מתוך 8 רשומות.
מס'	סוג	מס' אסמכתא 1	מס' אסמכתא 2	פרטים	תאריך ערך	חובה	זכות	יתרה
2	רכש שוטף	רכש שוטף #1		ספקים שונים	2015-10-07 00:00:00	-100.00		-100
2	רכש שוטף	רכש שוטף #1		ספקים שונים	2015-10-07 00:00:00		118.00	118
2	רכש שוטף	רכש שוטף #1		ספקים שונים	2015-10-07 00:00:00	-18.00		-18
1	חשבונית מס-קבלה	חשבונית מס-קבלה #1		לקוחות שונים	2015-08-12 00:00:00		847.46	847.46
1	חשבונית מס-קבלה	חשבונית מס-קבלה #1		לקוחות שונים	2015-08-12 00:00:00	-1000.00		0
1	חשבונית מס-קבלה	חשבונית מס-קבלה #1		לקוחות שונים	2015-08-12 00:00:00		152.54	152.54
1	חשבונית מס-קבלה	חשבונית מס-קבלה #1		לקוחות שונים	2015-08-12 00:00:00		1000.00	0
1	חשבונית מס-קבלה	חשבונית מס-קבלה #1		לקוחות שונים	2015-08-12 00:00:00	-1000.00		-1000

מונע על ידי מחשוב מהיר 2015

נכתב על ידי אדם בן חור
www.speedcomp.co.il

**Comment by adam2314** [comment]
אוקי
הפירוט הזה הוא תנועות יומן

2 רכש שוטף רכש שוטף #1 ספקים שונים 2015-10-07 00:00:00 -100.00 -100
2 רכש שוטף רכש שוטף #1 ספקים שונים 2015-10-07 00:00:00 118.00 118
2 רכש שוטף רכש שוטף #1 ספקים שונים 2015-10-07 00:00:00 -18.00 -18
1 חשבונית מס-קבלה חשבונית מס-קבלה #1 לקוחות שונים 2015-08-12 00:00:00 847.46 847.46
1 חשבונית מס-קבלה חשבונית מס-קבלה #1 לקוחות שונים 2015-08-12 00:00:00 -1000.00 0
1 חשבונית מס-קבלה חשבונית מס-קבלה #1 לקוחות שונים 2015-08-12 00:00:00 152.54 152.54
1 חשבונית מס-קבלה חשבונית מס-קבלה #1 לקוחות שונים 2015-08-12 00:00:00 1000.00 0
1 חשבונית מס-קבלה חשבונית מס-קבלה #1 לקוחות שונים 2015-08-12 00:00:00 -1000.00 -1000

**Comment by shaulmani** [comment]
גרמת לי לחייך (: פקודות יומן אני יודע
ברכש פקודת יומן צריך להיות
חובת הוצאה לפי סיווג 100
חובת מעמ תשומות 18
זכות ספק לפי סיווג 118
בהכנסה חובת לקוח 118
זכות הכנסה 100
זכות מעמ 18
זו לא מופיע כך
בגירסה 3 זה כמו שרשמתי
תשווה ותתאים
בתאריך 8 באוק' 2015 18:19,‏ "adam2314" <notifications@github.com> כתב:

**Comment by adam2314** [comment]
אוקיי עכשיו אני מבין
זה מתעלם ממספר החשבון אצלך במערכת
זה תוקן כבר אני סוגר את הבאג הזה
