### ISSUE TITLE
לינט לא עובדת ללא אינטרנט

### ISSUE THREAD

**Issue by jacovs** [adam2314/linet3#560]
שלום
לינט לא עובדת ללא אינטרנט.
אפשר לסדר שהיא תעבוד ללא אינטרנט?

**Comment by shaulmani** [comment]
זה אסור ע"פ חוק
כל תוכנת הנה"ח חייבת להיות על מחשב מקושר לאינטרנט

**Comment by starnetwork** [comment]
שאול, תודה על החידוש
אשמח מאוד לקבל סימוכן לדרישה הנ"ל, זה מעניין מאוד

**Comment by shaulmani** [comment]
יש חובה לאפשר עדכונים על פי השינויים בחוק. בלינט זה עובד על ידי הרשמה
ואינטרנט זמין כך שכל עדכון יוכל להתעדכן.
בתאריך 8 באוק' 2015 09:05,‏ "starnetwork" <notifications@github.com> כתב:

**Comment by jacovs** [comment]
תודה על התשובה.
אני מבין שהאינטרנט הוא על מנת לשאפשר לקבל עדכונים.
האם אפשר לסדר שאפשר יהיה להפעיל את לינט ללא אינטרנט, וכאשר נהיה בתוך התוכנה תיהיה אפשרות לעדכן את התוכנה דרך האינטרנט.
אני לא רוצה שהתוכנה תהיה מחוברת כל הזמן לאינטרנט.

**Comment by shaulmani** [comment]
להבנתי טכנית לא ניתן לפעול אחרת
בתאריך 8 באוק' 2015 13:22,‏ "jacovs" <notifications@github.com> כתב:

**Comment by adam2314** [comment]
ישנו פתרון כאן בגיט
5729a050f20cb5c88ab06369c17594192a8da7ba

**Comment by jacovs** [comment]
שלום אדם
אפשר כמה מילות הסבר?

**Comment by adam2314** [comment]
אהלן
הקוד עודכן היום כך ש
במקרה והתוכנה לא מצליחה למצוא את שרת העדכונים תקפיץ אזהרה במקום לגרום לקריסה של הדשבורד

**Comment by shaulmani** [comment]
גם אצלי ?
בתאריך 8 באוק' 2015 18:25,‏ "adam2314" <notifications@github.com> כתב:

**Comment by jacovs** [comment]
תודה

**Comment by jacovs** [comment]
שלום אדם
התוכנה שנמצאת בגיק היא לינוקס.
אני משתמש ב windows
אתה יכול לעדכן את הגירסה של windows?

**Comment by aribhour** [comment]
זה לא הולך ככה. אדם הראה לך את שורות הקוד שצריך לשנות. או שאתה משנה אותם לבד או שאתה מבקש ממישהו שמבין לשנות את שורות הקוד הללו.
בהצלחה

**Comment by jacovs** [comment]
שלום
אני חשבתי שהתוכנה שנמצאת בגיט היא מתאימה ללינוקס, אז כנראה שטעיתי.
העתקתי את הקבצים המעודכנים מגיט לגרסת לינט 3 "חלונות" שיש לי והבעיה נפתרה.
עכשיו אפשר להפעיל את לינט ללא אינטרנט.
תודה רבה.
