### ISSUE TITLE
שליחת מסמך באימייל לחיצה ראשונה יש הודעת שגיאה שמבקש שקלים שלמים ללא אגורות מצליח רק בלחיצה שנייה

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#561]
לאחר שליחה פותח טאב נוסף שיש לסגור
אם לוחצים עדכן יש הודעת שגיאה
מסורבל ומטעה
ניסיון ישיר להדפסה מהמסמך גם מבקש עיגול סכומים
ניתן להדפיס רק מניהול מסמכים בלי שהודעה תצוץ

**Comment by adam2314** [comment]
איזה דפדפן?
איזה שדה מבקש סכומים שלמים?

**Comment by shaulmani** [comment]
אני רושם סכום כולל מעמ. ללא מעמ יש אגורות. התוכנה מבקשת לרשום שקלים שלמים.
לחיצה חוזרת מבטלת את ההודעה.
בתאריך 8 באוק' 2015 18:01,‏ "adam2314" <notifications@github.com> כתב:

**Comment by adam2314** [comment]
done.
