### ISSUE TITLE
Cannot create opening balance for accounts - exception

### ISSUE THREAD

**Issue by 86ds8DR** [adam2314/linet3#562]
הגדרות -> יתרת פתיחה
choose some account, fill in some amount.
choose year 2015
click on שמור

result: 
CException 
Property "Transactions.date" is not defined.

**Comment by adam2314** [comment]
you are right.
https://github.com/adam2314/linet3/commit/dbedf0d46048f068fb9f571866c77058ceeb1777
fixed it.
