### ISSUE TITLE
רישום מוקדם של מתרפאים

### ISSUE THREAD

**Issue by roeylee** [adam2314/linet3#563]
לפי הוראות ניהול ספרים, רופאים, רופאי שיניים וטרינרים וכדומה, צריכים:
רישום מוקדם של מתרפאים אשר לפיו נקבעים התאריך ושעת הביקור אצל הרופא יישמר כחלק בלתי נפרד ממערכת חשבונותיו.

רופא מסויים עובד עם יומן גוגל והשאלה היא אם יש אזשהו אופן בו ניתן לקשר יומן גוגל ללינט ושהיא תתעד את הפגישות העתידיות של המתרפאים.

**Comment by aribhour** [comment]
אין כיום אפשרות לסנכרן אירועים בין לינט לבין יומן גוגל . אבל אפשר לרשום אירועים, הן עתידיים והן אירועי עבר בתוכנה.

**Comment by roeylee** [comment]
איך רושמים ארועים? והאם יש תעוד של מחיקות (כדי שזה יהיה קביל מבחינת מ"ה)?

**Comment by aribhour** [comment]
חשבונות או נהל חשבונות-> פרטי קשר
ניתן לראות את רשימת האירועים שרשמת באחד הווידג'טים בדשבורד
אי אפשר למחוק ולכן תיעוד המחיקות אינו רלוונטי
