### ISSUE TITLE
הודעת שגיאה בשחזור בכרום ופיירפוקס

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#569]
413 Request Entity Too Large
nginx/1.4.6 (Ubuntu)

**Comment by adam2314** [comment]
הקובץ שאתה מנסה להעלות גדול מידי צריך שם הודעה יותר טובה, מה גודל הקובץ?

**Comment by shaulmani** [comment]
1.גודל הקובץ 4273 kb.
2.בעבר היה מקרה דומה והבנתי שעשית עדכון מערכת כך שגיבויים קודמים לא נכללים בגיבוי.
3.מחקתי את כל הגיבויים בחברה ועשיתי גיבוי חדש. גודל הקובץ אותו דבר.
4.שיחזור בקובץ חדש ללא גיבויים קודמים נותן אותה הודעת שגיאה.
5.החברה קטנה חד צידי 351 רשומות.

**Comment by shaulmani** [comment]
אדם, אמרת שיש דברים שצריך לעדכן במשתמש שלי.
אולי קשור לזה ?

**Comment by adam2314** [comment]
תנסה עכשיו עודכן פרמטר בשרת
