### ISSUE TITLE
בעיה בעדכון ל2.21

### ISSUE THREAD

**Issue by biavi26** [adam2314/linet3#571]
בעת העדכון הופיעה הודעה
מבקש רשימת קבצים לעדכון
בודק הרשאות.
C:\Program Files\linet\apache\htdocs/tmpהסתיימה בדיקת ההרשאות
תחילת עדכון קבצים
הסתיים תהליך עדכון הקבצים.
מבקש עדכון למסד הנתונים

Warning: Missing argument 1 for getSQL(), called in C:\Program Files\linet\apache\htdocs\module\update\index.php on line 181 and defined in C:\Program Files\linet\apache\htdocs\module\update\index.php on line 233
אולי זה קשור:
כשאני מנסה לעשות גיבוי נוצר קובץ עם 2 בתים!!!

**Comment by adam2314** [comment]
בגדול התשובה היא שאנחנו לא תומכים יותר ב2 ואתה חייב לשדרג כבר
http://linet.org.il/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9-%D7%9C%D7%9C%D7%99%D7%A0%D7%98-%D7%9B%D7%9C%D7%9C%D7%99/%D7%A9%D7%93%D7%A8%D7%95%D7%92-%D7%9C%D7%99%D7%A0%D7%98-2-%D7%9C%D7%92%D7%A8%D7%A1%D7%94-3

בקטן אתה צריך את פונקציית הגיבוי בשביל זה
אז תראה לנו את תוכן
```
c:\Program Files\linet\apache\htdocs\module\private\backup.php
c:\Program Files\linet\apache\htdocs\module\private\download.php
```
באמצעות
http://pastebin.com/

**Comment by biavi26** [comment]
תודה על התשובה:
במחיצה:

c:\Program Files\linet\apache

אין את יתר המחיצות:

htdocs\module\private\

ואולי בגלל זה אין גיבוי.

יש לי כבר את הגרסה החדשה במחשב אחר אבל אני לא יכול להעביר אליו את הקבצים
הישנים בגלל הגיבוי.

בתאריך 1 בנובמבר 2015 בשעה 10:00, מאת adam2314 <notifications@github.com>:

**Comment by adam2314** [comment]
עם התקייה לא קיימת אז התוכנה מותקנת אצלך בנתיב אחר
אני הייתי מריץ חיפוש לקובץ
openfrmtimport.php
נניחומגלה איפה התוכנה נמצאת

**Comment by biavi26** [comment]
התוכנית נמצאת כאן:
C:\Program Files\linet\apache\htdocs
המחיצה שחסרה היא private
התוכניות נמצאות ב- htdocs
backup.php  5K  4/01/12
download.php   1K  16/1/12


בתאריך 2 בנובמבר 2015 בשעה 10:45, מאת adam2314 <notifications@github.com>:

**Comment by biavi26** [comment]
הי,
אם אצליח לבצע גיבוי, אזי אוכל להעביר את המחשב שעליו התוכנה לגרסה 3

תודה על התגובות המהירות.

בתאריך 2 בנובמבר 2015 בשעה 19:51, מאת Avi Ben Itzhak <biavi26@gmail.com>:

**Comment by adam2314** [comment]
אוקי אז זה ממש ישן

תגבה את התקייה
C:\Program Files\linet\apache\htdocs

ותריץ את העדכון שוב
הקבצים צרכים להשתנות הפעם
ואז תנסה לגבות

**Comment by biavi26** [comment]
התכוונת לגבות ולמחוק את htdocs  ?

בתאריך 3 בנובמבר 2015 בשעה 9:46, מאת adam2314 <notifications@github.com>:

**Comment by adam2314** [comment]
אל תמחק כלום אחרי העדכון אתה צריך לראות שם קבצים אחרים.

**Comment by biavi26** [comment]
הי,
(נראה לי שאני מראשוני המשתמשים...)
הבעיה היא שהעדכון נתקע. והצגתי את ההודעה בפורום. מה שיש כרגע במחיצה זה לאחר
כמה נסיונות עדכון.
אם קיימת תוכנית לגיבוי קובצי הנתונים אזי אני אפעיל אותה ואעביר את הנתונים
לגירסה 3.


בתאריך 3 בנובמבר 2015 בשעה 10:17, מאת adam2314 <notifications@github.com>:

**Comment by aribhour** [comment]
אבי שלום לך,
עד כאן זה המקסימום שאנחנו יכולים לעשות בשבילך במדיה הזו. נראה לי שעל מנת לסיים טוב יותר את פרשת השדרוג תאלץ לפנות אלינו טלפונית, לשלם ולקבל סיוע טכני מאתנו בתמורה.
ארי 0772105001

**Comment by biavi26** [comment]
תודה על הנסיונות.
הבעיה נפתרה!!!!!!!!!
מסתבר שבזמן הגיבוי נשמרים 2 קבצים: אחד קובץ ריק במחיצת download - כאשר קובץ
זה מזוהה ע"י הדפדפן.
וזאת בזמן שקובץ הגיבוי המלא נשמר במחיצה ישנה htdocs\backups שהעדכון כפי
הנראה לא מזהה אותה .
גם אני לא זיהיתי אותה, אבל אחרי שבקשת שאחפש מחיצת backup אז זיהיתי את
המחיצה והגיבויים שם.
הקבצים ייובאו לגרסה 3 והכל בסדר.

שוב
תודה על העזרה

בתאריך 3 בנובמבר 2015 בשעה 10:29, מאת aribhour <notifications@github.com>:

**Comment by aribhour** [comment]
יופי, אנחנו שמחים
