### ISSUE TITLE
NSIS Error - Error Launching installer

### ISSUE THREAD

**Issue by gilsoffer1** [adam2314/linet3#578]
הי למישהו יש מושג למה קיבתי את ההוסעה הזאת בהתקנה??
![image](https://cloud.githubusercontent.com/assets/15618665/10893617/7c4d5f16-81b2-11e5-8c5b-57ff166c5a7d.png)

**Comment by adam2314** [comment]
נראה לי שכדאי להוריד את הקובץ מחדש.

מה הגודל שלו?

http://nsis.sourceforge.net/Why_do_I_get_NSIS_Error%3F
