### ISSUE TITLE
הפקת מסמך ראשון בחברה יוצרת כפילות במסמכים

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#579]
המסמך נוצר פעמיים ופקודת היומן כפולה
יש לי רושם שזה כל מסמך ראשון 
עסק חדש או שיחזור
הוצאה עסקית ואח"כ רכוש הרכוש כפול
לדעתי מצריך תיקון בהקדם כדאי שיהיה אפשר לפתוח עסקים או לקלוט סוגי מסמך חדשים

**Comment by shaulmani** [comment]
טופל ?

**Comment by adam2314** [comment]
ראיתי שהייתה לך בעיה בחברה אחת לא מצליך לראות מה הגורם
א. תנסה שוב באותה חברה
ב בוא ננסה למצוא את הבעיה

אני לא מצליח לשחזר

**Comment by shaulmani** [comment]
בעסק 14 שוב קרה. זה לא חברה חדשה כבר יצאו מיסמכים.
חושב שכל כניסה ויציאה מהמערכת הפקת מסמך ראשון מסוג מסוים גורם לזה

**Comment by shaulmani** [comment]
המסקנה שלי שבכל כניסה מחודשת למערכת בהפקת מסמך הוצאה זה קורה..
בדיקת נתונים מראה את הבעיה.

**Comment by shaulmani** [comment]
לא יודע אם קשור באיזה שלב בערב תוך כדי עבודה לינט נתקעה לרגע FREEZ 
אחרי חזרה לעבודה זה התחיל.

**Comment by shaulmani** [comment]
כל רענון חברה גורם לזה גם בקבלות
הכנסות בינתיים לא קרה

**Comment by adam2314** [comment]
לא מצליח לשחזר את הבעיה
הוספתי כמה מניעות ליצירת כפל מסמכים בכל מקרה
