### ISSUE TITLE
 Issue 457 שנסגר לא ברור

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#584]
הכוונה היא לתקן מסמך קיים
מה שקורה זה שאני מתקן מסמך ואז נוצר מסמך חדש
יתכן ואני לא פועל נכון
אשמח להסבר

**Comment by aribhour** [comment]
ניתן עכשיו להוסיף/לערוך הערות נסתרות למסמך וגם לצרף קובץ. לא ניתן לתקן/לערוך מה שכלול בתוכן המסמך
