### ISSUE TITLE
שליחת מייל PDF עם קבלה ללקוח

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#588]
שאני מנסה לשלוח מייל קבלה בPDF
אני מקבל את המסך
Expected response code 250 but got code "501", with message "501 Syntactically invalid HELO argument(s)

**Comment by aribhour** [comment]
בדוק את הגדרות שרת המייל שבפרטי העסק. כנראה שהפרטים שהזנת שם שגויים
