### ISSUE TITLE
Path error on installation

### ISSUE THREAD

**Issue by bardice** [adam2314/linet3#589]
Hi,
I'm trying to install linet3 on local linux apache server.

I have wordpress site on this server too, so I put linet on var/www/html/linet3, followed the installation guide, and enabled in .htaccess "RewriteBase /linet3/".

When I tried to install through chrome, It can't find adress /install, and I didn't found this folder in github.

Do you know where can I find this folder or what do I need to change in .htaccess in order to make it work.

Thanks!

**Comment by adam2314** [comment]
its not a folder make sure htaccess is configured properly and the mod_rewrite is loaded http://httpd.apache.org/docs/2.2/howto/htaccess.html

**Comment by adam2314** [comment]
updates?

**Comment by bardice** [comment]
I will check that later this day, thanks.

**Comment by adam2314** [comment]
you can check the code works without mod_rewrite by trying /index.php?r=install
but you wont be able to continue

**Comment by adam2314** [comment]
i will close this issue if no update will be made

**Comment by bardice** [comment]
Hey, I can see installation page when I enter through r=install.

But with /install, I get 500 error, with this in log file:
[Mon Nov 30 15:52:14.291783 2015] [core:error] [pid 8110] [client 127.0.0.1:43301] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

**Comment by bardice** [comment]
I found my problem with .htaccess rewritebase that wasn't set to /

thanks!

**Comment by adam2314** [comment]
good:)
