### ISSUE TITLE
Failed to connect to update3.linet.org.il port 443: Timed out

### ISSUE THREAD

**Issue by Linet3GithubApiUser** [adam2314/linet3#594]
<p style="direction: rtl;">איך שנכנסים לחברה נפתח העמוד הזה ואי אפשר להמשיך הלאה</p>

**Comment by dan-omniscience** [comment]
The linet update server is down and it breaking the up.
It's not the first time, Adam would you like some help on this?

**Comment by adam2314** [comment]
duplicate #560
update to the latest commit should fix it.
