### ISSUE TITLE
סגירת קבלות

### ISSUE THREAD

**Issue by pelegw** [adam2314/linet3#595]
אולי אני מפספס משהו, אבל ברגע שאני מוציא קבלה כנגד חשבונית וסוגר את החשבונית, הקבלה מופיעה במצב פתוח. מה הפעולה שסוגרת קבלה?

**Comment by aribhour** [comment]
באופן טבעי הפקדה בבנק של אמצעי התשלום שהתקבל סוגרת קבלה. זה לא מיושם כרגע בתוכנה באופן אוטומאטי.
ניתן לסגור קבלה באופן ידני.

**Comment by pelegw** [comment]
היי, תודה :) חשבתי שזה יהיה אוטומטתי גם

קצת מטומטם מצידי, אבל אני לא מוצא שום אופציה לבצע סגירה ידנית ולא מצאתי את זה במדריך המשתמש באתר

**Comment by aribhour** [comment]
לא, זה קצת מטומטם מצדי, כי הפניתי אותך לתכונה שקיימת בגרסה חדשה שעוד לא שוחררה לציבור... בשבועות הקרובים תשוחרר גרסה חדשה ובה היכולת "לסגור" כל מסמך באופן ידני במסך ניהול המסמכים. עד אז אין אפשרות לסגור קבלה
