### ISSUE TITLE
בהפקת חשבונית מס קבלה, בקליטת תאריך השיק, אם דחוי, מופיע יום קודם

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#596]
דוגמה
הפקתי חשבונית מס קבלה היום
קיבלתי שיק דחוי ל-8.12.15
בהפקת המסמך יופיע תאריך 7.12.15
אם אני רוצה שיופיע 8.12.15 עלי לרשום 9.12.15

**Comment by adam2314** [comment]
צודק
תיקנתי
