### ISSUE TITLE
  בהתקנה לא הבנתי מה לעשות עם הקובץ Hosts אני לא מוצא אותה בבקשה עזרה!!

### ISSUE THREAD

**Issue by idomenashko** [adam2314/linet3#599]
בבקשה

**Comment by idomenashko** [comment]
דחוף

**Comment by aribhour** [comment]
תוריד תוכנה קטנה כאן
http://linet.org.il/component/jdownloads/viewdownload/3-linet-software-download/14-hosts-windows?Itemid=0 
תפעיל אותה והבעיה תיפתר. בהצלחה!

**Comment by idomenashko** [comment]
ניסיתי זה לא עובד אני נכנס אחרי ההתקנה ללינט וזה לא טוען את האינטרנט

**Comment by aribhour** [comment]
תתאר בבקשה במדויק מה אתה מפעיל ומה אתה מקבל

**Comment by idomenashko** [comment]
אני לוחץ על האיקון של לינט על שולחן העבודה זה נכנס לאינטרנט ואתה מכיר שאתר לא עובד והוא אומר לך לרענן אז זה משזה אומר לי
@aribhour

**Comment by aribhour** [comment]
כנראה שלא התקנת את התוכנה בדיוק לפי ההוראות. קרא כאן בתשומת לב את הוראות ההתקנה
http://linet.org.il/support/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%94%D7%AA%D7%A7%D7%A0%D7%94-%D7%9C%D7%9C%D7%99%D7%A0%D7%98-%D7%AA%D7%95%D7%9B%D7%A0%D7%AA-%D7%94%D7%A0%D7%94%D7%9C%D7%AA-%D7%97%D7%A9%D7%91%D7%95%D7%A0%D7%95%D7%AA/%D7%94%D7%AA%D7%A7%D7%A0%D7%AA-%D7%9C%D7%99%D7%A0%D7%98-%D7%A2%D7%9C-%D7%9E%D7%97%D7%A9%D7%91-windows
שים לב במיוחד לחלק שמדבר על הרצת קובץ ההתקנה בתצורת 
run as administrator

**Comment by idomenashko** [comment]
לא הבנתי יש לך סקייפ? @aribhour

**Comment by aribhour** [comment]
לא

**Comment by idomenashko** [comment]
מה אפשר לעשות @aribhour

**Comment by aribhour** [comment]
אני מציע לך לקרוא. אל תתעצל

**Comment by idomenashko** [comment]
אני קראתי שנייה אני מוחק אותה ומתקין אותה שוב @aribhour

**Comment by idomenashko** [comment]
אין זה לא עובד מחקתי והתקנתי שוב וגם את הקובץ ששלחת לי וזה לא עובד @aribhour

**Comment by aribhour** [comment]
גם את ההסרה של התוכנה אתה צריך לבצע ב
Run as administrator
אם אתה לא מבין איך להפעיל הסרה/התקנה בצורה כזו חפש בגוגל

**Comment by idomenashko** [comment]
יש להם תמיכה תכנית? @aribhour

**Comment by aribhour** [comment]
כן, בתשלום

**Comment by idomenashko** [comment]
שנייה אני ימחק את זה עם AdminAstrtor

**Comment by idomenashko** [comment]
@aribhour

**Comment by idomenashko** [comment]
והקובץ ששלחת לי שמתקינים אותה איפה צריך לשמור אותו @aribhour

**Comment by aribhour** [comment]
אתה לא קורא את ההוראות ולא עוזר לעצמך ומצפה לעזרה מאחרים. זה לא הולך ככה! בהצלחה לך

**Comment by idomenashko** [comment]
אני קראתי אבל זה לא עובד @aribhour

**Comment by idomenashko** [comment]
שנייה גבר במקום לעשות את זה עם הקובץ איך מגיעים לאיפה שמשנים את זה כמו שהם מסבירים
@aribhour

**Comment by aribhour** [comment]
עניין קובץ
HOSTS
לא קשור לעניין התוכנה אם היא תעבוד או לא. 
הפעולות בקובץ ה-
HOSTS
רק יכולות לגרום לתוכנה לעבוד יותר מהר כשיש בעיות של מהירות תגובה
הבעיה שלך כמו גם הפתרון שלה זה לא שם
