### ISSUE TITLE
קשיוצרים קבלה איך מכנסים לבפנים פריט

### ISSUE THREAD

**Issue by idomenashko** [adam2314/linet3#600]

**Comment by aribhour** [comment]
קבלה זה רק מסמך שמעיד על העברת כסף מיד ליד באמצעי תשלום שונים. לא מסמך שמעיד על העברת פריטים מיד ליד. בשביל זה יש חשבוני, תעודת משלוח ומסמכים רבים אחרים

**Comment by idomenashko** [comment]
באיזה אנינטרנט התוכנה עובדת יותר מהר @aribhour

**Comment by idomenashko** [comment]
?
 @aribhour
