### ISSUE TITLE
איזה סוג טופס צריך לעשות בשביל לעשות את המסמך עם פריטים

### ISSUE THREAD

**Issue by idomenashko** [adam2314/linet3#601]

**Comment by adam2314** [comment]
שלום עידו
אני מפציר בך לקרוא באתר לפני שאתה שואל
http://www.linet.org.il/support/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9-%D7%9C%D7%9C%D7%99%D7%A0%D7%98-3-x
