### ISSUE TITLE
לאחר התקנה ראשונית של גרסה 3.2 שתי בעיות

### ISSUE THREAD

**Issue by aribhour** [adam2314/linet3#608]
א. מקבלים הודעת שגיאה לאחר כניסה ראשונה לתוכנה בשלב ה
login
כנראה בגלל שהתוכנה מנסה להכניס לחברה הראשונה בברירת מחדל
ב. לסדר מחדש את השדות בפרטי העסק כך ששדה שם העסק בעברית יהיה הראשון
ג. אם לא קשה אז לסמן בדרך כלשהי את השדות שם העסק ומספר ע"/ח"פ כך שמשתמשים יבינו שאלה שדות חובה

**Comment by adam2314** [comment]
a.ok
b.ok
c only by validate wont mark fields
