### ISSUE TITLE
תשלום לספק לא יוצר ניכוי מס במקור למרות שמוגדר לספק  שיעור המס

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#609]
עד להשלמת הנושא לבטל שדה זה אצל ספקים 
עברנו על רישום פקודות היומן

**Comment by aribhour** [comment]
לא שייך לכאן

**Comment by starnetwork** [comment]
ארי, מה שלא שייך לכאן זה רק הדו"ח או כל עניין הניכוי מס במקור?

**Comment by aribhour** [comment]
זה היינו הך. אין אפשרות לנכות מס במקור כאשר אתה לא מדווח על כך בשני דוחות: דוח חודשי (102) ודוח שנתי (865) . תחשוב על זה: אתה לוקח כסף שבמקור היית אמור לשלם לספק, שם אותו בצד ומספר לו שאתה הולך להעביר את זה למס הכנסה אבל מצד שני לא מדווח על כך למס הכנסה ואין לך אפילו את הכלים בתוכנה לדעת אפילו כמה ניכית ממי ומתי...
