### ISSUE TITLE
?האם לינט תומכת בדווח מפורט מקוון ודו"ח תקופתי מקוון

### ISSUE THREAD

**Issue by plg1** [adam2314/linet3#617]
שלום,
עסק שמלא עד היום דוחות מע"מ באופן ידני, נתבקש להעביר דווח מפורט מקוון (לפי הבנתי, על כל חשבונית) וגם את הדו"ח התקופתי באופן מכוון.
האם לינט תומכת בזה? איך מבצעים את העברת הדוחות? ומעט אוף טופיק, אני חדש בנושא, איפה אפשר ללמוד יותר? הבנתי שצריך כרטיס חכם, יש דריברים ללינוקס (זובונטו)? איזה סוג מומלץ? תודה רבה

**Comment by aribhour** [comment]
בתפריט דוחות או מסים (תלוי בגרסה) יש לך דוח בשם
PCN874
זה דוח מע"מ מקוון, הדוח מפיק קובץ שאתה צריך לשלוח לרשות. תתייעץ עם הרו"ח שלך איך לעשות את זה בדיוק
אתה יכול ללמוד על התוכנה כאן:
http://linet.org.il/support/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9-%D7%9C%D7%9C%D7%99%D7%A0%D7%98-3-x 
וספציפית על כרטיס חכם וחתימות דיגיטאליות ספציפית כאן:
וגם כאן ב
Github
http://linet.org.il/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9-%D7%9C%D7%9C%D7%99%D7%A0%D7%98-%D7%9B%D7%9C%D7%9C%D7%99/%D7%94%D7%A4%D7%A7%D7%AA-%D7%9E%D7%A1%D7%9E%D7%9B%D7%99%D7%9D-%D7%97%D7%AA%D7%95%D7%9E%D7%99%D7%9D-%D7%93%D7%99%D7%92%D7%99%D7%98%D7%90%D7%9C%D7%99%D7%AA-%D7%91%D7%97%D7%AA%D7%99%D7%9E%D7%94-%D7%9E%D7%90%D7%95%D7%91%D7%98%D7%97%D7%AA
לגבי התקנת לינט על לינוקס ודרישות מערכת כאן
http://linet.org.il/support/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%94%D7%AA%D7%A7%D7%A0%D7%94-%D7%9C%D7%9C%D7%99%D7%A0%D7%98-%D7%AA%D7%95%D7%9B%D7%A0%D7%AA-%D7%94%D7%A0%D7%94%D7%9C%D7%AA-%D7%97%D7%A9%D7%91%D7%95%D7%A0%D7%95%D7%AA/%D7%94%D7%AA%D7%A7%D7%A0%D7%AA-%D7%9C%D7%99%D7%A0%D7%98-%D7%A2%D7%9C-%D7%9E%D7%97%D7%A9%D7%91-%D7%9C%D7%99%D7%A0%D7%95%D7%A7%D7%A1

**Comment by aribhour** [comment]
אנא ממך, להבא תפתח נושא חדש על כל שאלה

**Comment by plg1** [comment]
תודה רבה. אפתח בעתיד נושא אחד לשאלה.
