### ISSUE TITLE
תוכנה לעוסק פטור

### ISSUE THREAD

**Issue by navahu** [adam2314/linet3#618]
שלום,

לפני כשבועיים שוחחתי איתכם ונאמר לי שתוך שבוע יוצאת תוכנה חדשה ידידותית יותר ומותאמת לעוסק פטור.

רציתי לדעת אם יצא כבר ואם כן מה הקישור?

**Comment by aribhour** [comment]
עדיין לא. ממש בקרוב עניין של ימים.

**Comment by navahu** [comment]
אז עדיף לחכות ולא לעבוד עם התוכנה הישנה??

2016-01-07 9:53 GMT+02:00 aribhour <notifications@github.com>:

> עדיין לא. ממש בקרוב עניין של ימים.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adam2314/linet3/issues/618#issuecomment-169588788>.
>



-- 

*נאוה חורי*

*NAVART4U*

<http://www.sigbee.com/he?utm_campaign=signature&origUserUID=5e1918ef172e04e7345d90425cfd529a317a70d9&origSigUserImage=b7e0a2a1a79d3ad2.gif>

**Comment by aribhour** [comment]
בהחלט מומלץ לחכות
