### ISSUE TITLE
חתימה דיגיטלית מאושרת בתסריט ריבוי ישויות מס

### ISSUE THREAD

**Issue by alexbodn** [adam2314/linet3#619]
שלום לכם ותודה על השרות

אני שוקל להטמיע שירותי הנהלת חשבונות בתוך שירות ניהול מסחר אלקטרוני עם ריבוי ישויות מס.
קראתי את המסמך אך לא ברור לי השימוש בקורא הכרטיסים: 
האם יש להעביר כרטיס ידנית בכל דיווח, או שניתן לשמור את הכתוב על הכרטיס ולהשתמש בכל פעם?
ועד האם ניתן לקרוא את הכרטיס ידניתת ללא מכשיר קריאה?

תודה מראש,
אלכס

**Comment by aribhour** [comment]
אלכס שלום,
אני לא יודע לאיזה מסמך אתה מתייחס. לינט אינה תומכת בחתימה דגיטאלית מאושרת אלא רק בחתימה דיגיטאלית מאובטחת. אני מניח שהכרטיס שאתה מדבר עליו  הוא כרטיס הצפנה שמונפק על ידי חברת קומסיין -החברה המוסמכת על ידי המדינה להנפיק חתימה דיגיטאלית מאושרת- כרטיס כזה הוא חיוני לחתימה דיגיטאלית מאושרת אבל הוא מיותר לחלוטין על מנת לחתום מסמך בחתימה דיגיטאלית מאובטחת. אתה יכול ללמוד על ההבדל בין שתי חתימות דיגיטאליות אלה כאן: 
http://linet.org.il/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9-%D7%9C%D7%9C%D7%99%D7%A0%D7%98-%D7%9B%D7%9C%D7%9C%D7%99/%D7%94%D7%A4%D7%A7%D7%AA-%D7%9E%D7%A1%D7%9E%D7%9B%D7%99%D7%9D-%D7%97%D7%AA%D7%95%D7%9E%D7%99%D7%9D-%D7%93%D7%99%D7%92%D7%99%D7%98%D7%90%D7%9C%D7%99%D7%AA-%D7%91%D7%97%D7%AA%D7%99%D7%9E%D7%94-%D7%9E%D7%90%D7%95%D7%91%D7%98%D7%97%D7%AA
בקצרה ניתן לומר שאם העסק שלך אינו גובה כספים במזומן ו/או בצ'קים תוכל להשתמש בחתימה אלקטרונית מאובטחת בביטחון. ליתר ביטחון התייעץ עם רואה החשבון שלך לפני קבלת החלטה בעניין

**Comment by alexbodn** [comment]
תודה. שוחחנו בטלפון ועוד נחדד
