### ISSUE TITLE
postgresql

### ISSUE THREAD

**Issue by alexbodn** [adam2314/linet3#620]
שלום,

אני מכיר את אהבת phpל-mysql, 
אבל עד כמה חיבור לבסיס נתונים יותר רציני ייחשב שינוי שמחייב שינוי ברישוי?

למרות שברור כי שינויים רבים דורשים התערבות רוחבית, עד כמה תעזור בידול גרעין שמחייב רישוי ופיתוח שירותים שונים כמודולים שלא ידרשו רישוי מחדש בכל שינוי?

תודה מראש,
אלכס

**Comment by aribhour** [comment]
אני מניח שאתה מתכוון לאישור רישום התוכנה ברשות המסים ולא לרישוי התוכנה, כי רישוי התוכנה מאפשר שינוי קוד ללא הגבלה למעט מגבלת פרסום הקוד כולו, כולל התוספות והשינויים שביצעת במידה והינך מפיץ את התוכנה בצורת קבצים לאחרים.
אז אם השאלה שלך היא האם שינוי הקוד כך שיתמוך במסד נתונים מסוג
POSTGRESQL
במקום
MYSQL
מחייב אישור רישום חדש ברשות המסים היא כן נראה לי ששינוי רוחבי בקוד התוכנה ובסוג מסד הנתוניםפ שהיא עובדת איתו הוא שינוי משמעותי שיחייב אישור מחדש. אבל עדיין זה לא אמור לייאש אותך לא כל כך קשה לאשר תוכנה ברשות.

**Comment by aribhour** [comment]
אתה מוזמן ליעזר בנו באישור הרישום ברשות לךכשתצטרך

**Comment by alexbodn** [comment]
תודה רבה.
אכן ברור שזה שינוי משמעותי, אך מדובר בבסיס נתונים יותר יציב ומבוסס.
שאלת php כללית: האם יש דרייבר גנרי שיתאים לכמה מערכות rdbms 
כמו sqlalchemy, dbd, odbc, hibernate?

תודה מראש, 
אלכס

**Comment by starnetwork** [comment]
היי אלכס,
המע' מבוססת על
Yii2 Framework
לפחות מידיעה שלי, לא צריכה להיות בעיה מיוחדת להעביר את זה ל-DB אחר, גם postgresql...
מידע נוסף:
http://www.bsourcecode.com/yiiframework2/yii2-0-database-connection
מאמין שאדם יוכל להרחיב פה...

**Comment by adam2314** [comment]
בגדול מה ששלום כתב זה נכון ויש דרייבר גנרי.
מבחינתי יש 2 בעיות עיקריות
הinstaller 
לא מותאם לכתוב
 dsn
 כזה אז יצירת מסד הנתונים תהיה ידנית

יש שוני במבני הנתונים בין שתי המערכות לדוגמא אנחנו עושים שימוש בTINYINT

**Comment by alexbodn** [comment]
אכן ברור, תודה.

זהו תרגיל למשתמש, עם הדגש למי שהספיק להשתמש, כדי לזהות התנהגות שאולי התקלקלה עקב השינוי.
אני עשוי לעשות זאת, כשאוכל בעצמי להקרא משתמש, ומקווה להגיע לזה בקרוב.
ממה שהספקתי להבין, העקר אמור להיות הסבת main.sql & company.sql. שוב, כשהמערכת שלי תהיה ראויה להנהלת חשבונות ;)

אלכס
