### ISSUE TITLE
תפעול

### ISSUE THREAD

**Issue by alexbodn** [adam2314/linet3#621]
שלום

אני עמל על הקמת אתר מסחר אלקטרוני לשירות עצמי עבור חנויות רציניות ודי מורכבות.
לינט פתרון נהדר למי שירצה לפתוח חנות ואין לו מערכת הנה"ח אחרת. אולי אף ישאר איתה. 
מה שברור לי שגיוון התסריטים ידרוש מעורבות מעבר לממשק אוטומטי בין מודולי המסחר להנה"ח, 
ובוודאי בשלבי הממשק עם רשויות המס.
האם בין מפתחי ומשתמשי לינט יהיו המורשים והמעוניינים לספק שירות מקצועי משלים ובתשלום
לבעלי אתרי מסחר?

בתודה מראש,
אלכס

**Comment by aribhour** [comment]
בהחלט כן, תרים טלפון 0524780789
