### ISSUE TITLE
סליקה

### ISSUE THREAD

**Issue by alexbodn** [adam2314/linet3#622]
שלום

פוסט אחרון להיום
האם אפשר להתממשק עם סולקים אחרים, פלאכרד למשל?
כלומר ביצוע התשלום יהיה במערכת המסחר ויהיה צורך להביא את פרטי התשלום מהסולק.
לא תהיה אפילו לי בעיה לפתח את הממשק, אולם האם זה לא יפגע ברישוי עותק התוכנה?

תודה מראש,
אלכס

**Comment by aribhour** [comment]
היי אלכס,
כמו שעניתי לפוסט הקודם שלך. תרים טלפון

**Comment by alexbodn** [comment]
דיברנו, תודה
