### ISSUE TITLE
can't run Composer for new installation

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#624]
Hi,
I did the following steps and got this error:
git clone https://github.com/adam2314/linet3.git
curl -sS https://getcomposer.org/installer | php
html]# php composer.phar update
Composer could not find a composer.json file in /var/www/html
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

any suggestion?
I also don't see the composer.json in the project files...

Regards,

**Comment by adam2314** [comment]
please read the guide again especially the line: "then cd into the protected folder and run"  (after cloning)
