### ISSUE TITLE
Payment extra fields don't show up and several other bugs

### ISSUE THREAD

**Issue by tsurelad** [adam2314/linet3#626]
Hi,

First of all I've created a docker image for linet, so setting up a new linet installation is easier and faster: https://github.com/tsurelad/linet . You might want to consider building and publishing a docker image in docker hub, and saving the users the long composer updating steps.

I've created a new account on a fresh installation and played with it a bit. Encountered the following errors:

* When creating a Receipt, and choosing "Bank Transfer" or "Check" as the payment details, the extra fields don't show up (e.g., check number, bank account, etc.). When trying to finalize the receipt, you get to an error screen stating those fields are missing. I was able to finalize receipts only with the "Cash" payment method.

* The company logo doesn't show in the generated PDFs (shown correctly when I use the "print" option).

* After saving a document as a draft, there is no option to "produce" it - PDFs and mails and "Submit" are with the "Draft" title, it doesn't get a number, and the "Production Date" field is disabled, so I cannot set the date to effectively produce it.

* After sending a mail of some document, a "green" message is shown, saying that the mail has been sent successfully (and indeed it does), but below that message appear a "send mail" box. I'm not sure this is the behavior you want - probably you want the user to be taken to the document list screen.

* English version of the documents contains the Hebrew address and not the English one.

* English version of the documents has the header row aligned to the right, making the column names misaligned with the body of the table.

* Trying to update the initial balances of the account results a "field cannot be null" SQL error, probably for a column not mapped by a UI element.

Thanks for all of the effort you put in this project.

Elad.

**Comment by aribhour** [comment]
Hi Elad,
First thing, thanks for your efforts to simplify Linet installation on Linux platform and your long and detailed report of issues within Linet system.
You are kindly invited next time to open up new issue here in github for each bug/request that you came accross while using Linet accounting system. This way we can track each issue treatment separately.
As for the issues themselves: Some of the bugs you reported we cannot reproduce. Which version do you use?

**Comment by tsurelad** [comment]
master version... (cloning the git repo directly).

**Comment by tsurelad** [comment]
Now it is completely reproducible - I've uploaded the linet docker image to [docker hub](https://hub.docker.com/r/tsurelad/linet/).

Just run:

```
docker run --name linettest -p 8888:80 tsurelad/linet
```

and go to http://localhost:8888 to have the exact fresh system I've used.
Simply create a user, create a company, and try to make a first Receipt-Invoice document...

**Comment by aribhour** [comment]
New version is going to be released due this weekend. We would rather like you to test this version instead of working on recent release.
Sugest some 2-3 days of patiance...

**Comment by tsurelad** [comment]
I know you are releasing a new version in the next several days, and this is why I have tested the latest version of the code (today's master version) and immediately created the issue. Unless you have those things fixed locally and not committed, I think you'd want them fixed in the new version.

But I can just the same wait several more days, no rush...

**Comment by aribhour** [comment]
The upcoming release is a major one. This is the reason this time it is going to have better qa before publishing. The one you used passed minimum qa if any...

**Comment by shaulmani** [comment]
תפתח כרטיס בנק ותבדוק שוב
לגבי שאר ההערות כמו שארי הסביר נחכה לעדכון (:

**Comment by tsurelad** [comment]
As i've done before, I've opened a bank account and it still doesn't show the extra payment fields. The error I get when trying to make the PDF out of a draft invoice-receipt is:
```php
Class 'app\components\payments\Exception' not found in /app/protected/components/payments/Bank.php at line 50 (throw new Exception("NO due date was found for transaction", 401);)

    public function transaction($in,$out, $model) {
        $due_date = DocchequesEav::findOne(array("doc_id" => $model->doc_id, "line" => $model->line,'attribute'=>'due_date'));
        $account_id = DocchequesEav::findOne(array("doc_id" => $model->doc_id, "line" => $model->line, 'attribute' => 'account_id'));
        if($due_date==NULL)
            throw new Exception("NO due date was found for transaction", 401);
```

**Comment by adam2314** [comment]
update to latest commit and check again please. updates are welcome.
