### ISSUE TITLE
בפיירפוקס מופיע מנעול ירוק לאבטחה ומשולש אפור

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#642]
זה סימן שמראה שמפתח צריך לפתור בעיית אבטחה בדף 
 בכרום אישור פתר התצוגה מייד
בפיירפוקס לא

**Comment by adam2314** [comment]
ללחוץ F5

**Comment by shaulmani** [comment]
ניסיתי לא עוזר (:
בתאריך 31 בינו' 2016 17:49,‏ "adam2314" <notifications@github.com> כתב:
