### ISSUE TITLE
php curl failed

### ISSUE THREAD

**Issue by yosiftbt** [adam2314/linet3#644]
בנסיון התקנה בוינדוס 10, 64ביט בהתחלת ההתקנה נותן בעית 
php curl failed

**Comment by aribhour** [comment]
תעקוב אחרי הוראות ההתקנה כאן
<https://www.linet.org.il/support/linet-community-edition/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%94%D7%AA%D7%A7%D7%A0%D7%94-%D7%9C%D7%9C%D7%99%D7%A0%D7%98-%D7%AA%D7%95%D7%9B%D7%A0%D7%AA-%D7%94%D7%A0%D7%94%D7%9C%D7%AA-%D7%97%D7%A9%D7%91%D7%95%D7%A0%D7%95%D7%AA/%D7%94%D7%AA%D7%A7%D7%A0%D7%AA-%D7%9C%D7%99%D7%A0%D7%98-%D7%A2%D7%9C-%D7%9E%D7%97%D7%A9%D7%91-windows>
שים לב במיוחד לפסקה שמדברת על run as admin

2016-03-04 10:32 GMT+02:00 yosiftbt <notifications@github.com>:

> בנסיון התקנה בוינדוס 10, 64ביט בהתחלת ההתקנה נותן בעית
> php curl failed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adam2314/linet3/issues/644>.
>



-- 
בברכה
ארי בן חור
טל': 0772105001 , נייד: 0524780789 , פקס 037617315
