### ISSUE TITLE
בעיה בהפקת חשבונית מס קבלה

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#645]
בהפקת חשבונית מס קבלה לא מופיע מקום להזנת פרטי הקבלה (תקבולים)
![test-docs-create-9](https://cloud.githubusercontent.com/assets/626945/14088244/022c2a48-f537-11e5-8fde-473adb3f44ca.png)

**Comment by shaulmani** [comment]
בחלק העלון צריך להופיע סוג המסמך
אצלך לא רואים בטוח שזה חשבונית מס קבלה ?
ראה דוגמה :


[Invoice Receipt-900001.pdf](https://github.com/adam2314/linet3/files/198329/Invoice.Receipt-900001.pdf)

**Comment by starnetwork** [comment]
מדובר בחשבונית מס קבלה, יש באג עיצובי והשדות מופיעים רק אחרי שלוחצים על הכפתור "הוסף"
אתה מבצע בדיקות אולי על גרסה קהילתית ישנה יותר?
גרסת התשלום?

**Comment by shaulmani** [comment]
אני לא רואה בעיה
באיזה גירסה אתה עובד ?

**Comment by aribhour** [comment]
היי שלום, שלח כתובת שם משתמש וסיסמה בפרטי  בבקשה

**Comment by adam2314** [comment]
הייתה איזו תקלה בJS

צריך להיות בסדר עכשיו

**Comment by starnetwork** [comment]
שאלה, כשבוחרים ברטיס אשראי כאמצעי תשלום זה לא אמור להציג את פרטי הכרטיס?
וגם, אם בוחרים כרטיס אשראי בתשלומים זה לא אמור להציג את מס׳ התשלומים?

**Comment by aribhour** [comment]
סוגר ופותח 
ISSUE
חדש
