### ISSUE TITLE
בעיה בהפקת חשבונית מס קבלה

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#646]
הפקת חשבונית מס מציגה את המסמך כהעתק ולא מקור
ניסיון נוסף להפקה מציג אותו כמקור ולא העתק

**Comment by shaulmani** [comment]
מה סדר הפעולות שאתה עושה ?
אצלי זה לא קורה

**Comment by starnetwork** [comment]
היי שאול, אני נכנס למסך חשבונית מס קבלה, מזין את כל הפרטים, ולוחץ הפקה -> PDF
עשיתי את זה גם יחד עם אדם והוא ראה את זה קורה
אתה עובד על הגרסה הקהילתית? העדכנית?

**Comment by shaulmani** [comment]
נראה אם הבנתי
על המסך אתה רואה העתק
ב-PDF שאתה שומר/פותח מקור ?
אז הכל תקין
אין צורך בהפקה נוספת

**Comment by starnetwork** [comment]
1. אני מפיק ועל המסך אני רואה שרשום העתק (לפעמים גם הדפדפן חוסם את הורדת ה-PDF), וזה אגב קורה גם אם עושים הפקה למסך ולא רק ל-PDF
2. אני מנסה להפיק שוב, ואני מקבל מקור, וזה לא תקין, אלא צריך להציג העתק כי המקור הופק כבר...
אנחנו על הגרסה העדכנית המופיעה בגיט זה, ואדם גם ראה את הבעיה...

**Comment by adam2314** [comment]
לא נציג את מצב המסמך בכל תצוגה מקדימה פרט להדפסה.

**Comment by aribhour** [comment]
אדם מתכוון לכך שמצב המסמך, דהיינו אם הוא מקור או העתק, הוא רלוונטי אך ורק למסמך שהופק להדפסה. בהפקה ל"מסמך ממוחשב", מכיוון שהקובץ היחיד המהימן (והיחיד שנבדק בביקורת מס של הרשות) הוא הקובץ המקורי שכתוב עליו שהוא מקור וגם חתום דיגיטלית, אינה מותירה משמעות לשום דבר אחר.

**Comment by starnetwork** [comment]
הבעיה לא רלוונטית רק למסמכי
pdf
אלא גם למסמכי הדפסה, כל המנגנון שם לא תקין, למשל אם אני מייצר טיוטא ואחר כך לוחץ על הפקה -> הדפסה, זה ממשיך להציג לי חשבונית מס קבלה מס׳ טיוטה ולא מס קבלה מקור עם ספרור החשבונית

**Comment by aribhour** [comment]
בדקתי ואין שום בעיה במנגנון המקור/העתק חוץ מבעיה מאוד נקודתית שעליה פתחתי נושא #654 חדש. 
מנגנון מקור/העתק צריך למנוע הדפסת מקור יותר מפעם אחת ואינו רלוונטי לפי די אף. מסמך שהופק פעם ראשונה לפי די אף יתנהל עם הגיון שונה לחלוטין מזה של מסמך שהופק להדפסה

**Comment by starnetwork** [comment]
ארי, שלחתי לכם בנפרד גישה לחשבון שעשיתי בו את הבדיקות
תגיש בבקשה אל הקישור שאני שולח לך במייל, ותראה שלאחר לחיצה על הפקה -> הדפסה
זה מפיק טיוטה במקום חשבונית מס קבלה, שולח לך את הפרטים במייל

**Comment by aribhour** [comment]
סוגר ופותח נושא חדש
