### ISSUE TITLE
בעיה בהפקת חשבונית במטבע זר

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#647]
ניסיון להפקת מסמך במטבע זר ללא מע"מ מציג את התוצאה ומחשב מע"מ מתוך הסכום בכל זאת
כלומר 250 דולר ללא מע"מ מפיק מסמך על 250 דולר כולל מע"מ

**Comment by shaulmani** [comment]
מבחינת הנהלת חשבונות צריך להגדיר פריט ללא מעמ שיקושר לחשבון מכירות לחול
הצגת המסמך במטבע זר רק מציגה במטבע זר

**Comment by starnetwork** [comment]
כן, זה בוצע...

**Comment by adam2314** [comment]
לא מצליח לשחזר. תוודא ששיוך המשתמש לקטגורית המעמ לפריט נכונים
