### ISSUE TITLE
בעיה בעבודה עם מטבע זר

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#648]
1. מסמנים דולרים וזה רושם שקלים
2. בכל מקרה, לא מתבצעת המרת מטבע לסה"כ החשבונית

**Comment by shaulmani** [comment]
גם לי נעול על שקל בלבד

**Comment by adam2314** [comment]
מצורפת הדגמה 
מטבע דולר
מטבע דולר פטור
מטבע שח
בתוך מסמך שקלי
זה עובבד גם הפוך

לא ככ הבנתי מה הבעיה
![screenshot from 2016-04-03 17-14-45](https://cloud.githubusercontent.com/assets/4151250/14232895/9d578a5c-f9c0-11e5-83b1-a3bf97e3c291.png)
