### ISSUE TITLE
התאמות שפה ללינט

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#649]
תיקוני תרגום \ טקסט במסמך PDF
1. במסמך מופיע היחידה בשם
Units
ולא "יחידות"

2. במטבע, מופיע ILS ולא ש"ח או הסימון של ש"ח
ובכלל, אפשר להצמיד את סימן המטבע לסכום ולוותר על העמודה הזאת

**Comment by starnetwork** [comment]
לגבי הנושא של היחידות, מצאתי איפה עורכים את זה בממשק הניהול תחת מלאי -> יחידות

**Comment by adam2314** [comment]
1. מעולה
2. אין כרגע פונקציה שתחזיר סמל מטבע

אני רוצה לסגור את הנושא.

**Comment by starnetwork** [comment]
תודה על התשובה, רק שאלה לפני שסוגרים
יש מקום שאפשר לשנות בו את ה-
ILS
ל-ש״ח בעברית
?

**Comment by adam2314** [comment]
כרגע לא.
ILS 
הוא המזהה של המטבע

אפשר לנסות להעביר את מזהה המטבע
במעמד ההדפסה דרך
 דרך פונקציית התרגום של הYII
ואז לכתוב "תרגום" למזההים
