### ISSUE TITLE
Credit Card information for The reception area

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#651]
Hi,
how can I add the Credit card company, last 4 digits of card and transaction ID for the reception area?
needed for both GUI and add transaction via API

**Comment by adam2314** [comment]
at the moment credit card company is not supported.
you can save the others like this:
```php
[
    "type"=>3,
    ...
    "last_4_digtis"=>["value"=>"XXXX-XXXX-XXXX-0546"],
    "auth_number"=>["value"=>"12345"],
]
```
