### ISSUE TITLE
Edit Invoice template

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#652]
Hi,
where is located the file that I need to edit, if I want to edit the PDF Invoice template?

Regards,

**Comment by aribhour** [comment]
The mail templaits can be edited from settings->email templats

**Comment by starnetwork** [comment]
Hi,
sorry, I mean edit the PDF file, change the template of the PDF file that client get, not just the email content...

**Comment by adam2314** [comment]
make a copy of
```
protected/views/docs/templates/classic.php
```
change it as you wish
then change the file:
`protected/views/docs/print.php`
line 66 to point your new file:
```
echo $this->render('templates/classic', [...
```

**Comment by starnetwork** [comment]
thanks for that!
1. suggestion: we can add inside templates directory file with the name of the user, for example user1.linet.org.il will look for user1.php and user2.linet.org.il will look for user2.php, and if no custom file, it's will use the original classic.php

2. the design of the pdf is only with the html code inside classic.php or also using the css classes that set on that file?

Regards,

**Comment by adam2314** [comment]
1. I think you meant tenant and not user. the community version will not support this.
2.  You can use manual stylesheet tag at your template. it should work. print and pdf uses PrintAsset AssetBundle.
