### ISSUE TITLE
בחשבונית מס קבלה חלק הקבלה עדיין לא תקין ולא מציג את השדות המתאימים לאמצעי התשלום שנבחר

### ISSUE THREAD

**Issue by aribhour** [adam2314/linet3#653]
לא משנה איזה אמצעי תשלום בוחרים נשאר שדה אחד למלא כאילו שאמצעי התשלום הנבחר הוא מזומן

**Comment by adam2314** [comment]
תוקן כבר

**Comment by starnetwork** [comment]
לא יודע איפה בדקת, אצלי עדיין לא תקין, אני צריך לעדכן קובץ מסוים?

**Comment by aribhour** [comment]
אם לא עדכנת מהגיט. תעדכן

**Comment by starnetwork** [comment]
עובד, תודה, ניתן לסגור
