### ISSUE TITLE
Add support in Yii2 laste stable version

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#656]
Hi,
Linet 3.2 support Yii 2.0.6
it's not up-to date
Please add support in the last stable version of the framework
*** community request ***

**Comment by adam2314** [comment]
Now that yii2.0.7 is stable, as far as i can see, from the instructions we are compatible.
also my git installation uses 2.0.7 without an issue.

**Comment by starnetwork** [comment]
thanks, that mean that now we don't need to change "yiisoft/yii2": "*" to "yiisoft/yii2": "2.0.6"
in composer.phar?

Regards,

**Comment by adam2314** [comment]
yes, and you probably mean `composer.json`.

**Comment by starnetwork** [comment]
Yes, thanks!
