### ISSUE TITLE
שגיאה בעת כניסה אל הגדרות -> שייך תפקידים

### ISSUE THREAD

**Issue by starnetwork** [adam2314/linet3#659]
בעת כניס אל הגדרות -> שייך תפקידים מקבלים את השגיאה
Database Exception – yii\db\Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'table.files' doesn't exist
The SQL being executed was: SELECT * FROM `files` WHERE `id`=71
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'table.files' doesn't exist
)
↵
Caused by: PDOException

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'table.files' doesn't exist

in /protected/vendor/yiisoft/yii2/db/Command.php at line 837

**Comment by adam2314** [comment]
updated Linet3Helper::hasLogo()
