### ISSUE TITLE
License for project

### ISSUE THREAD

**Issue by copyhold** [adam2314/linet3#673]
Pls add LICENSE file
It is unclear now how this project may be used

**Comment by aribhour** [comment]
Kindley pay attention to readme file & the header of each code page:
 * The contents of this file are subject to the **GNU AFFERO GENERAL PUBLIC LICENSE** Version 3.0
 * ("License"); You may not use this file except in compliance with the GNU AFFERO GENERAL PUBLIC LICENSE Version 3.0
 * The Original Code is:  Linet 3.0 Open Source
 * The Initial Developer of the Original Code is Adam Ben Hur.
 * All portions are Copyright (C) Adam Ben Hur.
 * All Rights Reserved.

**Comment by aribhour** [comment]
It means that it doesn't matter if you make any changes to the code or not, you must publish all of the code both if you are distributing the code in any form and also if you offer the application as a web service

**Comment by copyhold** [comment]
> The contents of **this file** are subject to...
what about the whole project?
